### ISSUE TITLE
How do you a responder's id?

### ISSUE THREAD

**Issue by cycomachead** [github/hubot#1008]
I'm looking at the docs and I see there's a way to specify additional metadata for a listener. This is actually going to prove incredibly useful for our Hubot as I think it should allow us to easily add some basic protections for a few commands, and DRY out some of the logic.

My only question is: How do I access this metadata? It seems like a should be able to create a "wrapper" around all the listeners with certain properties, but I'm not sure how to best do that.

**Comment by bhuga** [comment]
This is underway in #803.

**Comment by cycomachead** [comment]
In that sense -- I can't do anything until #803 is merged right?

**Comment by bhuga** [comment]
Looking at it just now, I don't see a way to access the metadata from the listener itself. But that wouldn't be terribly useful anyway; the metadata would be defined right next to the listener.

I think it's best to think of it as a stepping stone to #803. Sorry about that, but it's underway.

**Comment by cycomachead** [comment]
> I think it's best to think of it as a stepping stone to #803. Sorry about that, but it's underway.

No worries! It might not be bad to add a small note to the docs though!
