### ISSUE TITLE
better brain control

### ISSUE THREAD

**Issue by kengz** [github/hubot#1010]
Can we allow a better control of the brain, aka the memory, by users?
1. Export/Import(load): Say I'm running hubot in the cloud and over time it saves data to its brain, and I want to export the memory (could be a JSON file) elsewhere.
   Perhaps I migrate or update my hubot, and wish to load its old memory.
2. Modularization of memory. This allows for specialization of task and better performance. e.g. `favfood.json` and `favdrink.json` keep track of my team's favorite food and drinks, with 10000 entries each. Each can be uploaded independently, and searching from separate file is def faster than searching a larger concatenated file.

**Comment by sdimkov** [comment]
Hi,

In general I believe improving the brain is greatly needed. But for your case I believe for the most part it is doable without change to hubot:

1: The most common hubot setup includes persistence via Redis. This pretty much solves the problem.
Your data will be stored to Redis each time you write to the brain and restored each time you boot Hubot. So you can safely reboot / update / modify your hubot installation.
If you wish to migrate to another host, you can just export / import your redis.

2: Why do you even bother with the performance of this task? How often will you import data to your hubot? And won't you be importing it prior to booting it?

**Comment by technicalpickles** [comment]
There are two requests here, and I think they can be discussed separately.

I agree there could be better support for importing and exporting the contents at the brain. At some point, it's just a JavaScript object (`robot.brain.data`), so it can be `JSON.stringify`d and exported to a file. Similarly, `robot.brain.data` could be replaced with data from another source. You could do most of that outside of hubot already.

For example, if you are using the file brain, there's a JSON blob on disk. If you wanted to switch to the redis brain, you'd stop hubot, create the appropriate key, and assign that JSON string to the value, update hubot to use redis-brain, and then start it back up.

As for modularizing the brain, I'm not really sure about that. The current implementation of the brain isn't awesome already, so adding that seems like a stretch. I would also point out that scripts are just javascript, so you can easily attach other things to the `robot` object and access them other places. For example, if you wanted to be using mysql directly for your data, you'd be able to initialize a `robot.mysql` client, and use that from your scripts.

**Comment by mose** [comment]
I bet we will have some deep thinking about the brain in hubot3. Be sure we'll dig into the issues archives. So I'm closing this.

**Comment by technicalpickles** [comment]
We're moving to [Hubot Evolution](https://github.com/hubotio/evolution/) for discussing future features of hubot if anyone is interested in writing something up about this.
