### ISSUE TITLE
Hubot disconnects and does not reconnect (Slack)

### ISSUE THREAD

**Issue by wylieswanson** [github/hubot#1013]
I'm not clear if this is a hubot issue or a slack-hubot issue... 

I also have the same problem as others; https://github.com/slackhq/hubot-slack/issues/203

[Sat Jul 18 2015 04:26:52 GMT+0000 (UTC)] ERROR Last pong is too old: 14.952
[Sat Jul 18 2015 04:26:52 GMT+0000 (UTC)] INFO Reconnecting in 1000ms
[Sat Jul 18 2015 04:26:53 GMT+0000 (UTC)] INFO Attempting reconnect
[Sat Jul 18 2015 04:26:53 GMT+0000 (UTC)] INFO Connecting...
[Sat Jul 18 2015 04:26:54 GMT+0000 (UTC)] INFO Logged in as hubot of team, but not yet connected
[Sat Jul 18 2015 04:27:22 GMT+0000 (UTC)] INFO Slack client closed

I'm not clear why it is disconnecting -- it usually happens when there is some idle -- it never reconnects (on it's own).  I see the code used to exit hubot but was updated at some point to not exit hubot. Since I run hubot with a supervisor, I'd actually prefer it exit -- since it would get restarted. But instead, it just sits until I manually restart with supervisor.

**Comment by eriklindebratt** [comment]
+1

**Comment by eriklindebratt** [comment]
+1

**Comment by kengz** [comment]
I experienced the same issue weeks ago, and fixed it. Certainly wasn't the problem with `hubot-slack`; it was with the configuration variables (the process.env bunch), and perhaps with the scripts being imported too.
Check your slack token to be sure.

**Comment by wylieswanson** [comment]
Unfortunately @kengz, this is not really an answer.  Can you suggest what you changed in "process.env bunch".  Keep in mind, Hubot can run for days, even weeks, before the problem resurfaces.

**Comment by kengz** [comment]
Yes I realized, my apologies; it was weeks ago and I've coded quite a lot on my hubot, I'll try my best to remember.

I set my tokens using the environment variables, thus the `process.env.HUBOT_SLACK_TOKEN` for example, and that's how hubot accesses them. Can't recall precisely, but I think one of the tokens were wrong, and it gave me that error. I corrected it and problem was solved.

**Comment by coldlamper** [comment]
I have this problem as well. It randomly disconnects but does exit. Is it supposed to exit? Are you supposed to use supervisord  or monit to handle this?

**Comment by wylieswanson** [comment]
It doesn't exit -- and since it doesn't exit, using supervisord or monit doesn't really help.   It looks like there were code changes made to hubot (proper, not hubot-slack) that make it not exit -- and that the previous behavior was to exit.  It's clearly possible to make it exit again -- but my personal preference (for my deployment) would be to have a solution that doesn't stray from the official hubot release.

**Comment by eriklindebratt** [comment]
@wylieswanson I think this is an issue with [hubot-slack](https://github.com/slackhq/hubot-slack). I'm running my forked version of that module in which I've modified [slack.coffee](https://github.com/eriklindebratt/hubot-slack/blob/master/src/slack.coffee) to not reconnect on disconnect, but instead exit the process completely. That way I can set supervisor to pick that up and restart Hubot again. Seems to work much better for me.

Made a [pull request](https://github.com/slackhq/hubot-slack/pull/215) for it.

**Comment by wylieswanson** [comment]
@eriklindebratt I'd like to think a better solution becomes formal.  In the meantime, sincerely appreciate that you turned up a pull request for the fix -- I have no doubt it will make the problem irrelevant.  :)

**Comment by kengz** [comment]
Just confirmed the issue with my multiple hubots running on a server. They died to the same error around the same time, so that's a disconnectedness issue as mentioned above. Seems like the adapter just closes after it gives up trying.

A different solution would be to run/restart your hubot using `forever`, which I'm using. Been working pretty well and I didn't even noticed they died until I check the logs.

**Comment by coldlamper** [comment]
@kengz can you show use how you are using forever to keep it running please?

**Comment by kengz** [comment]
Here's an example https://github.com/kengz/jarvis#forever

**Comment by kengz** [comment]
Solution to this problem:
Make the Slack connector wait for the PONG for longer before quitting.

Go into the file `client.js` at the path `node_modules/hubot-slack/node_modules/slack-client/src/client.js`
Then change line 129, `_this._lastPong > 1000` into something longer, like `_this._lastPong > 100000`

**Comment by KenPowers** [comment]
That line was `_lastPong > 10000` for me. I just upped it to `100000` but that seems really hacky.
