### ISSUE TITLE
usersForFuzzyName expects user.name to exist when it may not

### ISSUE THREAD

**Issue by mshwery** [github/hubot#1014]
In some cases, there may be user data missing the `name` property, but [usersForFuzzyName does not check to ensure this](https://github.com/github/hubot/blob/master/src/brain.coffee#L135) and instead throws an error:

```
ERROR TypeError: Cannot read property 'toLowerCase' of undefined
   at Brain.usersForRawFuzzyName (/app/node_modules/hubot/src/brain.coffee:135:7, <js>:123:22)
   at Brain.usersForFuzzyName (/app/node_modules/hubot/src/brain.coffee:144:20, <js>:132:27)
```

**Comment by AndrewGuenther** [comment]
In what scenario would the `name` property be missing?

**Comment by mshwery** [comment]
In my case, name is missing either because the user data is being overwritten by `redis-brain` or by `hubot-slack`.

It seems that once redis connects and robot.brain is populated there are some items in that list that do not have the name property. 

Tomorrow I'll do a little more debugging to see why.

**Comment by michaelansel** [comment]
Calling this a bug for now, though it derives largely from a poorly defined interface on the `User` class. Is `name` a required and expected property (i.e. doesn't need to be checked everywhere) or an optional property that should be gracefully handled when missing?

I *think* it is an expected property based on [the code](https://github.com/github/hubot/blob/master/src/user.coffee#L9) (hence the bug label), but I'm intrigued if there is a reason why the Slack adapter is producing `User` objects without a name.

**Comment by bhuga** [comment]
Even if it is a bug, I would be :+1: to some defense around users here, since adapters need to fill that in and we can't always control it. If we want to be prickly about it, we could just throw an error blaming the adapter. But there's no reason to be ornery unless this cascades into 10 other places with the same assumption.

@mshwery, since I'm not sure how to replicate this, are you willing to put together a PR with a guard for the nil case? Just to see how deep the rabbit hole goes?

**Comment by mshwery** [comment]
@michaelansel hm, that actually makes this issue seem even more unusual – I hadn't dug into the User constructor, but it seems unless explicitly removed, a user object _should_ have a `name`.

I have a fork looking at this issue to see if I can nail it to `hubot-slack` or something else, but haven't had time to get to it yet.

I would happily PR it @bhuga, hopefully sooner than later.

**Comment by technicalpickles** [comment]
> In my case, name is missing either because the user data is being overwritten by redis-brain or by hubot-slack.
> I have a fork looking at this issue to see if I can nail it to hubot-slack or something else, but haven't had time to get to it yet.

I ran into something similar with the hubot-slack adapter actually. Slack was sending back a user without a profile. https://github.com/slackhq/hubot-slack/pull/232 is the PR to fix it, and that's released now.
