### ISSUE TITLE
Disable default commands

### ISSUE THREAD

**Issue by ezgoodnight** [github/hubot#1018]
Hi, I'm hoping to limit the commands hubot uses. Deleting the node_module folders for the commands seems to simply redownload those nodes again, and disabling the dependencies in package.json makes the bot fail. I simply want to disable basic commands like pug me or help for users. What is the best way to go about this?

I'm already aware of https://github.com/github/hubot/issues/778

For my purposes this may be too complex and too granular. I don't need fine control, I simply need a bot with the default commands off.

**Comment by michaelansel** [comment]
Did you remove the module from both `package.json` and `external-scripts.json`? If you are still seeing errors, which module is causing problems, and what is the error you get when you remove it from `package.json`?

**Comment by tombell** [comment]
Make sure you don't disable **ALL** the dependencies in `package.json`, some are needed.

**Comment by ezgoodnight** [comment]
`    "hubot-google-images": "^0.1.5",
    "hubot-google-translate": "^0.2.0",
    "hubot-help": "^0.1.1",
    "hubot-heroku-keepalive": "0.0.4",
    "hubot-maps": "0.0.2",
    "hubot-pugme": "^0.1.0",
    "hubot-rules": "^0.1.1",
    "hubot-shipit": "^0.2.0", `

These are the ones I want to delete. I'm leaving "hubot" "diagnostics" "redis-brain" and "scripts."

Should I leave any of these?

**Comment by ezgoodnight** [comment]
I removed the above in both files Michael. This was the error it gives me:

`[Tue Aug 04 2015 14:09:59 GMT-0400 (EDT)] ERROR Error: listen EADDRINUSE
  at exports._errnoException (util.js:746:11)
  at Server._listen2 (net.js:1156:14)
  at listen (net.js:1182:10)
  at net.js:1280:9
  at dns.js:85:18
  at process._tickCallback (node.js:355:11)

therealfubot> Error parsing JSON data from external-scripts.json: SyntaxError: Unexpected token ]`

**Comment by michaelansel** [comment]
Yay! Good luck with your Hubot!
