### ISSUE TITLE
Add a delay to responses

### ISSUE THREAD

**Issue by jacobtomlinson** [github/hubot#1023]
To make hubot feel a little more human we would like to add a delay to responses, only a second or so.

It would make sense to add this as an environment variable which defaults to `0` seconds, that way it can be an optional addition if people want it.

It would also be nice if for that second it could trigger the "hubot is writing..." flag in chat clients which support it.

**Comment by technicalpickles** [comment]
That's an interesting idea, but I don't see that making it into hubot core functionality.

Maybe it could be implemented as a script after https://github.com/github/hubot/pull/1021 is implemented? Also worth noting 'hubot is writing' would be adapter specific.

**Comment by michaelansel** [comment]
You could also do this right now with listener middleware; you just wait to begin processing the message (versus waiting to send the replies).

**Comment by jacobtomlinson** [comment]
Ah I wasn't aware of the middleware, I'll have a go at building it then! Thanks!

I'm keen to contribute the 'hubot is writing' code to the adapters I use, however I guess there would need to be some API hook somewhere in the middleware to call this? Any recommendation about how I should implement this?

**Comment by technicalpickles** [comment]
@jacobtomlinson I'd start by looking at a specific adapter that supports it. Slack comes to mind, but I'd guess things like xmpp would have it too. With that, you could implement it on one adapter to start.

If the API makes sense, it could be added to `src/adapter.coffee`. I think there is some room for how it'd behave though.

**Comment by jacobtomlinson** [comment]
Thanks. Slack is our main usage so I'll definitely start there.

My initial thoughts would be that as soon as hubot received a message for processing which matched a rule then it would triggger the 'hubot is typing', then run the delay, then send a 'stop typing' call, then send the response.

I'm not sure how that fits with the middleware though, especially ensuring it has matched a rule.

**Comment by technicalpickles** [comment]
@jacobtomlinson my thought is if you could add it to the adapter, and getting it working in one script, you'd be able to take that and refactor it into an middleware.

**Comment by bkeepers** [comment]
> That's an interesting idea, but I don't see that making it into hubot core functionality.

…

> You could also do this right now with listener middleware

…

> Ah I wasn't aware of the middleware, I'll have a go at building it then! Thanks!

Closing since it sounds like that could be an acceptable solution.
