### ISSUE TITLE
Solutions to multiple Hubot issues

### ISSUE THREAD

**Issue by kengz** [github/hubot#1026]
Hello, I love Hubot, and have taken to my own hands to solve some of the issues in this repo.

Here's [jarvis](https://github.com/kengz/jarvis), and has as many functions as possible since I let it manage many tasks for my team.

I did not fork of this repo because it contains some deployment files. Design-wise, the hubot source code is kept, with several independent modules and scripts removed/replaced. So, jarvis is basically a hubot, with many issues solved, features added.
## 

A quick list of related open issues I could find:
#1024, #1022, #1011, #928, #875, #862, and a few more.

By no mean an exhaustive list of the issues addressed/improvements made:
- `hubot-keepalive` is no longer needed; solved via `cron`
- an auto-restart (with limit) script makes hubot quasi-immortal, using `forever-monitor`
- deploying multiple instances of hubot from the same source code, via the use of different `.env-<bot>`
- ability to custom-group help commands, design the help menu
- added admin-privilege (in `scripts/helper.coffee`)
- user aliasing and better fuzzyName search method that allows identification using alias, called `userId` (in `scripts/helper.coffee`)
- option to export/import `brain.data` memory to Github (if one maintains the hubot code in Github and wishes the memory to keep in sync with the repo)
- user serialization available to multiple built-in functions (see below)
- comes with many fundamental functions, including geolocation serialized with the user id and alias, used by timezone, weather, maps (i.e. one can do 'weather/map/time Alice` and it recognizes Alice's location provided from before.
- personal reminder/todo, serialized per user.
- Google APIs
- Twitter APIs
- News
- `lodash`-evaluation (available under `lomath`)
- a chatbot module, which can tell apart between a chat, and an actual command (won't chat in that case)
- of course, memes.
- easier deployment (literally setup `.env` and run `npm start` you'll get all the functions above)
## 

To see the complete list, here's the link again https://github.com/kengz/jarvis

Let me know if any of the design/improvements interest you, or if you wish to merge some features into this repo.

**Comment by cycomachead** [comment]
> ability to custom-group help commands, design the help menu

I'm curious about this, especially the later part. Could you explain a bit about what you've done?

Overall, I like a lot of this stuff, at least based on the list, but don't many of these tools belong inside hubot packages? TODOs, API integrations, news, etc all seem like things that can be bundled separately. Whic are the features which would require modifying the core of hubot to work?

**Comment by cycomachead** [comment]
> easier deployment (literally setup .env and run npm start you'll get all the functions above)

I like this! I've done the same thing in my personal Hubot. (though I also created a super duper simple one line bash script for convenience.)

**Comment by kengz** [comment]
@cycomachead :

Thank you. First of all I must admit jarvis' source code is not the most organized (he's only 2 weeks old).

The help menu is ultimately still text-based, but now you have the option to group them into types, and name them. For example [here](https://github.com/kengz/jarvis#cmd) where they're grouped into `bot, fun, util`, and under `util` you can further expand into `alias, google, lomath, map,...` 

This is handled by a simple JSON in [`scripts/helper.coffee`](https://github.com/kengz/jarvis/blob/master/scripts/helper.coffee), and that object also serves a purpose in muting the chat (i.e. skip the chat module if an input message matches the regex in here)

Essentially this opens up the option to have control over the help menu hubot displays. You have the freedom to have any grouping, any naming, and they will show up in the help menu, as shown in the example above.

-
Script-wise, yep some of them belong to the `improvements` mentioned. I've tried to do minimal work, so some of the familiar tools under `scripts` are actually modified from the original when I had no choice. For example, I wanted user location recognition to work with map, time, weather; or user aliasing to work with todo/remind.

Since I didn't want to touch hubot's source code, several of these functions (user-alias-and-search, serialization, location, etc.) are in an external script. However I think these can be absorbed into the core of hubot, so other scripts can use it nicely without importing this external one.

-
The motivation was simply my laziness, and that I have to deploy so many instances, on so many platforms (Google, Heroku, local machine), and `npm start` seems the standard way for running a Node app.

**Comment by kengz** [comment]
Also an interesting sidenote: 

In the roadmap I mention https://wit.ai . Having so many scripts, each captured only by regexes, is a pain and it's quickly hitting the bottleneck. The next phase of jarvis will have an NLP-based parsing: take an input, do some NLP input processing to extract the intent, if it exists then run the task, else pass the string to chat module. 

This will allow for a smarter capturing of commands, and of course a better user interface. The best way for it is to modify from within the core of hubot.
