### ISSUE TITLE
Seeing WARN deprecated CSSselect

### ISSUE THREAD

**Issue by webhamm** [github/hubot#1027]
I am getting warnings about CSSselect. Not sure if that is important but it is a little confusing. Is that hubot install or is that something else related?

$ sudo npm install -g yo generator-hubot
> spawn-sync@1.0.13 postinstall /usr/local/lib/node_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.4.7 postinstall /usr/local/lib/node_modules/yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
generator-hubot@0.3.1 /usr/local/lib/node_modules/generator-hubot
├── chalk@0.5.1 (escape-string-regexp@1.0.3, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── yosay@0.3.0 (ansi-regex@0.2.1, string-length@0.1.2, ansi-styles@1.1.0, pad-component@0.0.1, word-wrap@0.1.3, minimist@0.2.0, strip-ansi@0.2.2, chalk@0.4.0, taketalk@0.1.1)
├── npm-name@1.1.1 (log-symbols@1.0.2, meow@3.3.0, registry-url@3.0.3, got@3.3.1)
└── yeoman-generator@0.17.7 (dargs@2.1.0, isbinaryfile@2.0.4, class-extend@0.1.1, diff@1.4.0, text-table@0.2.0, mime@1.3.4, underscore.string@2.4.0, async@0.9.2, grouped-queue@0.3.0, nopt@3.0.3, cross-spawn@0.2.9, run-async@0.1.0, debug@1.0.4, shelljs@0.3.0, mkdirp@0.5.1, iconv-lite@0.4.11, glob@4.5.3, rimraf@2.4.2, file-utils@0.2.2, findup-sync@0.1.3, github-username@1.1.1, lodash@2.4.2, request@2.60.0, cheerio@0.17.0, download@1.0.7, gruntfile-editor@0.2.0, inquirer@0.7.3)

yo@1.4.7 /usr/local/lib/node_modules/yo
├── titleize@1.0.0
├── array-uniq@1.0.2
├── figures@1.3.5
├── user-home@1.1.1
├── async@1.4.2
├── opn@1.0.2
├── humanize-string@1.0.1 (decamelize@1.0.0)
├── sort-on@1.2.2 (arrify@1.0.0, dot-prop@2.2.0)
├── yeoman-character@1.0.1 (supports-color@1.3.1)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── string-length@1.0.1 (strip-ansi@3.0.0)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── root-check@1.0.0 (downgrade-root@1.1.0, sudo-block@1.2.0)
├── repeating@1.1.3 (is-finite@1.0.1)
├── meow@3.3.0 (object-assign@3.0.0, minimist@1.1.3, indent-string@1.2.2, camelcase-keys@1.0.0)
├── yosay@1.0.5 (ansi-regex@1.1.1, ansi-styles@2.1.0, pad-component@0.0.1, word-wrap@1.1.0, strip-ansi@2.0.1, minimist@1.1.3, taketalk@1.0.0, string-width@1.0.1)
├── configstore@1.2.1 (object-assign@3.0.0, os-tmpdir@1.0.1, graceful-fs@4.1.2, uuid@2.0.1, xdg-basedir@2.0.0, osenv@0.1.3, write-file-atomic@1.1.2, mkdirp@0.5.1)
├── update-notifier@0.5.0 (is-npm@1.0.0, latest-version@1.0.1, semver-diff@2.0.0)
├── package-json@1.2.0 (registry-url@3.0.3)
├── npm-keyword@1.2.0 (registry-url@3.0.3)
├── got@3.3.1 (lowercase-keys@1.0.0, timed-out@2.0.0, is-stream@1.0.1, is-redirect@1.0.0, prepend-http@1.0.2, object-assign@3.0.0, infinity-agent@2.0.3, nested-error-stacks@1.0.1, duplexify@3.4.2, read-all-stream@3.0.1)
├── fullname@1.1.0 (npmconf@2.1.2)
├── cross-spawn@0.4.1 (lru-cache@2.6.5, spawn-sync@1.0.13)
├── yeoman-environment@1.2.7 (log-symbols@1.0.2, escape-string-regexp@1.0.3, diff@1.4.0, text-table@0.2.0, untildify@2.1.0, debug@2.2.0, mem-fs@1.1.0, globby@2.1.0, grouped-queue@0.3.0)
├── insight@0.6.0 (object-assign@2.1.1, async@0.9.2, lodash.debounce@3.1.1, os-name@1.0.3, tough-cookie@1.2.0, request@2.60.0)
├── yeoman-doctor@1.4.0 (object-values@1.0.0, log-symbols@1.0.2, each-async@1.1.1, semver@4.3.6, bin-version-check@2.1.0, twig@0.8.2)
├── lodash@3.10.1
└── inquirer@0.8.5 (ansi-regex@1.1.1, cli-width@1.0.1, through@2.3.8, readline2@0.1.1, rx@2.5.3)

**Comment by technicalpickles** [comment]
It looks like it's related to `yo`. hubot itself, nor generator-hubot
uses CSSselect itself.

**Comment by webhamm** [comment]
It is a non issue for hubot. Closing out
