### ISSUE TITLE
Proposal: Route Namespacing

### ISSUE THREAD

**Issue by gerred** [github/hubot#1034]
It would be nice for repetitive commands to have namespacing. For example, I'd like the following code:

``` coffeescript
robot.namespace /admin/, (admin) ->
  admin.reply /do a thing/, (res) ->
    # command replies to "hubot admin do a thing".

  admin.hear /let's have a party/, (res) ->
    # command replies to "admin let's have a party"
```

If people like it for inclusion into core, and we nail down an API, I can open a PR for it.

**Comment by michaelansel** [comment]
Oooh, I really like this idea. cc #873, where I had some related ideas, but this feels super clean.

Namespaces could automatically add a prefix to the listener IDs as well.

**Comment by gerred** [comment]
We may be able to combine #873 really nicely with this.

Perhaps some sort of context command, where all of the options you specified can be made in a declarative way.

For example, with my API proposal, you could do something like:

```coffeescript
robot.namespace /admin/, (admin) ->
  admin.config "ADMIN_TOKEN", required: true, description: "Here's some token", validation: (value) ->
  admin.namespace /hosts/, (hosts) ->
    hosts.config "AWS_ACCESS_KEY", required: true

    hosts.preConfig (env, done) -> # preconfiguration, perhaps to retrieve information for the subroutes
      setupSomething (resp) -> 
        env.region = resp.region
        done()

    hosts.respond /for tag (.*)=(.*)/, (msg) -> # respond/hear should wait for done callback if preConfig is defined
      label = res.match[1]
      value = res.match[2]
      aws.getHosts({region: msg.message.env.region, label: label, value: value}) # get context from higher namespaces
     .done (hosts) -> msg.reply(JSON.stringify hosts)
````

**Comment by michaelansel** [comment]
I'll think on this more, but first pass: namespaces should probably be strings instead of regular expressions. Prevents weird problems like overlapping namespaces and allows for easy lookup of a namespace (imagine spreading listeners in the same namespace across multiple files or even multiple modules)

**Comment by gerred** [comment]
:+1: on that.

**Comment by bhuga** [comment]
I've got scripts that would benefit from this, but I think we can do even more. The usual pattern is:

 * Many commands start with a prefix.
 * All the commands use `msg.finish()`.
 * There's a final command that displays help if the prefix was used but no previous command matched.

This helps with the first of those three, but not the second two related issues. How would you feel about special semantics for the "matches a prefix but no other command" case?

**Comment by technicalpickles** [comment]
> This helps with the first of those three, but not the second two related issues. How would you feel about special semantics for the "matches a prefix but no other command" case?

We already have a pattern for this in hubot core: `catchAll`. I don't think this often gets used though. In the earlier example:

```
    # hubot admin hosts for tag (label)=(value)
    hosts.catchAll (msg) -> # respond/hear should wait for done callback if preConfig is defined
      msg.send "I don't know what you mean by #{msg.message.text}, maybe try one of these?"
     # insert help output here.
```

**Comment by michaelansel** [comment]
@bkeepers this should probably go in the v3 brainstorming

**Comment by bkeepers** [comment]
@michaelansel thanks. I'm imagining that "Commands" on the roadmap would replace this feature. I'll get the evolution repo set up soon and we can talk through it.
