### ISSUE TITLE
Hubot crashes when posting an image URL

### ISSUE THREAD

**Issue by edc1591** [github/hubot#1040]
My hubot is crashing anytime a plugin tries to post an image/gif URL. Plugins that just send text don't cause a crash. I've tried systematically removing plugins to narrow down the crash, but whenever I think I've found the offender, I re-add every other script and the crash starts happening again. So, it does not appear to be caused by a single script. Strangely, the crash only seems to happen on Heroku and my 1GB DigitalOcean Ubuntu 14.04 box. The crash does _not_ happen when running the hubot locally on my Mac. Here's what gets output into the console:

```
2015-08-29T13:21:52.062788+00:00 app[web.1]: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
2015-08-29T13:21:52.065640+00:00 app[web.1]: util.js:35
2015-08-29T13:21:52.065944+00:00 app[web.1]:   var str = String(f).replace(formatRegExp, function(x) {
2015-08-29T13:21:52.065999+00:00 app[web.1]:                       ^
2015-08-29T13:21:52.067055+00:00 app[web.1]: RangeError: Maximum call stack size exceeded
```

The first line gets repeated hundreds of times before the app actually crashes. This is a newly generated hubot, so all the libraries are up to date. Every plugin was copied over from an existing hubot which also runs on Heroku without any issues.

I'd appreciate any insight, as I've been banging my head against the wall with this for days.

**Comment by technicalpickles** [comment]
Some questions to help narrow down what's happening:

* Which hubot adapter are you using? WHen testing locally, are you using the shell adapter?
* What versions of hubot and the adapter are you using? `npm ls` should list all the dependencies you have, so you can include that or just pull out those two packages
* What version of node and npm are you using? `node --version` and `npm --version` should show you
* Does it happen with every single image URL, or just a few? Does it happen to non-image URLs? Can you share some URLs that cause it?
* What community scripts are you using? (ie what's in `external-scripts.json` and `hubot-scripts.json`

**Comment by edc1591** [comment]
> Which hubot adapter are you using? WHen testing locally, are you using the shell adapter?

In production I'm using the slack adapter. When testing locally I did use the shell adapter. However, when testing locally with the slack adapter, it does _not_ crash.

> What versions of hubot and the adapter are you using? npm ls should list all the dependencies you have, so you can include that or just pull out those two packages

[Here's the output of npm ls](https://gist.github.com/edc1591/004ea4ba2ea020db9678).

> What version of node and npm are you using? node --version and npm --version should show you

Node version is `v0.10.40` and npm is `1.4.28`.

> Does it happen with every single image URL, or just a few? Does it happen to non-image URLs? Can you share some URLs that cause it?

It seems to be any URL. Not just images.

> What community scripts are you using? (ie what's in external-scripts.json and hubot-scripts.json

[hubot-scripts.json](https://gist.github.com/edc1591/99aacf2a98db87fe5940)
[external-scripts.json](https://gist.github.com/edc1591/f0e65799f37c17810ac4)

**Comment by edc1591** [comment]
Hmm, updating node seems to have fixed the issue. Strange...
