### ISSUE TITLE
Hubot for Zopim?

### ISSUE THREAD

**Issue by denielleanne** [github/hubot#1044]
Hi,

I'm new to GitHub, and new to coding in general. Our company is currently using Zopim as a chat service, and was wondering is Hubot would be a good virtual agent for our waiting customers?

**Comment by michaelansel** [comment]
Potentially? Hubot is most commonly used in a group chat environment, but pretty much any service for sending/receiving messages can be integrated. Note that Hubot does not have much intelligence out of the box: it doesn't do any kind of NLP or phrase recognition. All of that work would be up to you (or search for a [prebuilt script](https://hubot.github.com/docs/#scripts) that meets your needs).

If you are relatively new to coding, this may not be a very quick setup for you. If you're up for the work though, feel free to [join #hubot on FreeNode](http://webchat.freenode.net/?channels=#hubot) with any questions/problems you run into!

**Comment by mose** [comment]
Now we are on [slack](https://hubot-slackin.herokuapp.com/) ! Feel free to come and have a chat :)
