### ISSUE TITLE
'animate me' has stopped returning animated images

### ISSUE THREAD

**Issue by WillPresley** [github/hubot#1045]
<ins>I am more than happy to provide any logs/info I need to provide</ins> (I may need minimal direction on how to gather them), but it seems like 'animate me' is simply returning static images. I even had it return a Giphy link once, but the \_s.gif version, essentially hubot _chose_ to grab the static version.

**Comment by technicalpickles** [comment]
Which script are you specifically using?

There used to be an included google image script, but it has since been refactored over to https://github.com/hubot-scripts/hubot-google-images

**Comment by WillPresley** [comment]
Ah okay, that would make a lot of sense. Sorry about the open issue, I try to keep on top of things, saw the YouTube script move out of the included package and changed things accordingly, but I missed this one apparently. Thanks for the link, I'm 99% sure you are correct and things will work again with that script.
