### ISSUE TITLE
Is possible to open external scripts with hubot?

### ISSUE THREAD

**Issue by oinirio** [github/hubot#1047]
I have some python scripts that I use to see financial data from google/yahoo finance and would like to see the output of those scripts in a irc channel, how can I execute those scripts with hubot and send the output as a response.

Thanks in advance.

**Comment by michaelansel** [comment]
Take a look at [childProcess.execFile](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback).
