### ISSUE TITLE
Heroku: "Cycling" Causes Hubot to go down? (Any auto-restart suggestions?)

### ISSUE THREAD

**Issue by cycomachead** [github/hubot#1051]
Hello all,

Apologizes if this isn't the best place, but I've noticed some odd behavior with our Hubot and Heroku recently, and so far I can't seem to find any concrete answers.

For the second time in the past week or so, I'll see logs which look like this:

```
2015-09-15T19:30:48.518150+00:00 app[web.1]: [Tue Sep 15 2015 12:30:48 GMT-0700 (PDT)] INFO keep alive ping!
2015-09-15T19:35:43.540522+00:00 heroku[web.1]: Cycling
2015-09-15T19:35:43.541086+00:00 heroku[web.1]: State changed from up to starting
2015-09-15T19:35:46.897769+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2015-09-15T19:35:47.884623+00:00 heroku[web.1]: Starting process with command `bin/hubot --adapter hipchat --name Alonzo --alias /`
2015-09-15T19:35:49.796781+00:00 heroku[web.1]: Process exited with status 0
2015-09-15T19:36:48.387234+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

Keep alive seems to be working just fine, and I'm even using the new version so I'm not running into any scheduling limits of Heroku's new dyno plan. So far this has been working great and we haven't gotten warning emails or anything.

So, I have a couple questions:
- Has anyone else seen similar behavior?
  Edit: From re-reading some Heroku docs, the "cycling" itself is intentional, and the app itself should auto-restart. So, it seems like something in Hubot, or likely one of my packages isn't playing nice...only I don't see a way that I can figure out how to tell which exactly is the problem...
- Is the best approach to use something like an auto-restart type tool? I've looked into something like PM2 and others, but since there's still only one process on Heroku that heroku can kill, it doesn't seem like this is a solution... Perhaps I'm misunderstanding this, so by all means, tell me I'm crazy!

Thanks for the help!

**Comment by estiens** [comment]
+1 We are having this problem too recently

**Comment by technicalpickles** [comment]
What adapters are y'all using? I'm wondering if it's a general problem, or adapter specific.

**Comment by estiens** [comment]
@technicalpickles we're using the slack adapter

**Comment by estiens** [comment]
(looks like @cycomachead is using hipchat based on the logs they posted)

**Comment by cycomachead** [comment]
Yup, Hipchat adapter for me. I haven't seen this issue in the last week, but we've done quite a few deployments, so I wonder if I've just been avoiding the chances of this occurring by pushing code...

**Comment by technicalpickles** [comment]
From https://devcenter.heroku.com/articles/dynos#restarting

> Dynos are also restarted (cycled) at least once per day to help maintain the health of applications running on Heroku. Any changes to the local filesystem will be deleted. The cycling happens once every 24 hours (plus up to 216 random minutes, to prevent every dyno for an application from restarting at the same time).
>
> In addition, dynos are restarted as needed for the overall health of the system and your app. For example, the dyno manager occasionally detects a fault in the underlying hardware and needs to move your dyno to a new physical location. These things happen transparently and automatically on a regular basis and are logged to your application logs.

@cycomachead To your point about:

> . I haven't seen this issue in the last week, but we've done quite a few deployments, so I wonder if I've just been avoiding the chances of this occurring by pushing code...

According those same docs:

>  Manual restarts (heroku ps:restart) and releases (deploys or changing config vars) will reset this 24 hour period

So I think by deploying, you are avoiding this problem.

---

If I'm reading the original logs correctly, heroku is (expectedly) restarting your dyno. What's not expected is that it doesn't seem to be starting up in the 60 seconds heroku gives it. It's weird there aren't more logs from hubot starting up.

I don't have any good ideas on what to check next though :sweat:

**Comment by cycomachead** [comment]
@technicalpickles thanks for taking a look.

That was my hunch too, about deployments. I also agree about the expected and unexpected behavoirs.It's been a few weeks now, and so far things have been pretty good, and I don't think the bot has gone down! (Knock on wood!) 60s is definitely quite a while for a node app to start, especially for a fairly small one like a hubot. I'm starting to wonder if there were perhaps subtle changes in Heroku's architecture about a month ago...though there's not really a way of confirming that.

**Comment by bruno** [comment]
I started seeing the same thing recently on Heroku as well ... wasn't a problem before October as we never had any issues ... might be something to follow up with Heroku support.

**Comment by magicstone1412** [comment]
same problem with me

**Comment by cesarvarela** [comment]
Same issue for me, and suggestions?

**Comment by dish615** [comment]
anything new on this?
