### ISSUE TITLE
Strip formatting from messages?

### ISSUE THREAD

**Issue by callumacrae** [github/hubot#1053]
We have a script which starts like this:

``` coffeescript
robot.hear /some sentence here/i, (msg) ->
```

However, it doesn't hear it if the words are formatted at all, e.g. "some _sentence_ here".

Would it be possible / desired to remove formatting from messages before parsing them?

**Comment by tonydaly** [comment]
:+1:

**Comment by technicalpickles** [comment]
That is a good question. It's going to depend on the adapter I think, because not every one has rich formatting.

Which adapter are you using? I'd guess Slack.

**Comment by bhuga** [comment]
Receive middleware can solve this elegantly. It can edit the message before listeners attempt to match it. Here's an example that would let `/ping` also respond to a typo, `/pnig`:

```coffeescript
module.exports = (robot) ->
  robot.receiveMiddleware (context, next, done) ->
    context.response.message.text = context.response.message.text.replace("pnig", "ping")
    next()
```

```shell
Hubot> /pnig
Hubot> PONG
```

If you can write a function to strip the formatting, you could replace the message text with the stripped message in a similar way.

**Comment by callumacrae** [comment]
Yeah, we're using Slack.

A middleware would work. Not sure I can think of any cases where I would want `robot.hear` to be specifically matched against a formatted message, though.

**Comment by technicalpickles** [comment]
Slack already has a place it strips formatting for links. That'd be a good place to do it for other things: https://github.com/slackhq/hubot-slack/blob/master/src/slack.coffee#L153-L192

I think it is going to be up to the adapters to strip formatting like this. They probably should preserve the raw message in case an adapter-specific script wants to do something about, like hubot-slack does here: https://github.com/slackhq/hubot-slack/blob/master/src/slack.coffee#L112-L120

**Comment by technicalpickles** [comment]
This is adapter specific, so I filed https://github.com/slackhq/hubot-slack/issues/241 to track Slack doing something special with formatting.

**Comment by bkeepers** [comment]
Closing since this is being tracked in https://github.com/slackapi/hubot-slack/issues/241
