### ISSUE TITLE
Hubot to read slack bots?

### ISSUE THREAD

**Issue by lilnate22** [github/hubot#1059]
I want hubot to alert me when git "things" happen.

I have a github bot (slack official) that pings a channel when certain things are happing (open PR, Close, comment etc).

I have written hubBot to listen to these strings and act accordingly.

i.e when PR submitted, it will message devs to code review.

The string github sends looks like this:

![image](https://cloud.githubusercontent.com/assets/882236/10254959/f529372c-6914-11e5-8ba4-d67c689215d2.png)

but my hubbot doesnt seem to read the message correctly... when i manually C+P the message, it works as intended...

Is it because slack bots are not sending "messages" ? if so how do i have my hubot to listen to slack bots?

**Comment by bhuga** [comment]
Have you looked at github webhooks and, in particular, github services?

https://developer.github.com/webhooks/#service-hooks

These let you do pretty much anything you want. I think you can probably cut out the middleman of hubot and slack entirely.

**Comment by michaelansel** [comment]
:+1: to @bhuga's comment. To directly address your question, I believe Slack doesn't allow bot-to-bot communication. I'm not sure that was necessarily a conscious decision in the beginning, but I doubt they are going to try to change it (protects against bot-to-bot loops).

**Comment by mose** [comment]
This seems to be sorted out. Feel free to come back if you need more information :)
