### ISSUE TITLE
Hubot is silent locally after initial install.

### ISSUE THREAD

**Issue by jamespwright** [github/hubot#1061]
I ran through the Yeoman generator as suggested [here](https://github.com/github/hubot/blob/master/docs/index.md) using the Flowdock adapter.

After the initial install I run hubot from the bin directory and get no responses to commands like help.
As you can see in the image below, hubot echos "hubot help" on the first occurrence, then nothing after that.  

I don't even know where to begin looking for the problem here.  It seems to make it through the whole process fine and "configCheck" returns "OK".

![image](https://cloud.githubusercontent.com/assets/90216/10339315/516de73a-6cd0-11e5-839b-91d7c4f8759a.png)

**Comment by michaelansel** [comment]
That doesn't sound right! I'll try to repro...

**Comment by jamespwright** [comment]
I completely forgot one (probably important) thing.  

As you can see I ran the Yeoman generator under "C:\code\cr-hubot".
Initially "cr-hubot/bin/hubot.cmd" had this line:
    npm install && node_modules\.bin\hubot.cmd --name "hubot" %* 

On running hubot the very first time, this errored out with "The system cannot find the path specified."  
I changed it to:  
    npm install && ..\node_modules\.bin\hubot.cmd --name "hubot" %* 

To get it to actually run.  Which is when it does the originally reported problem.  It seems like it expects the node_modules to be installed directly under the /bin/ folder.  

Other than that I don't believe I made any changes.

**Comment by framerate** [comment]
I am seeing this as well. Node 4.2.1 + npm 3.3.9

It was a working hubot that I just popped open to write some new scripts for

**Comment by michaelansel** [comment]
Haven't had time to look at this :sob:

I wonder if it has something to do with updated versions of node/npm?

**Comment by framerate** [comment]
I'm not crazy familiar with hubot (yet) but I know NPM3 is a flat structure of node_modules. Could that mess anything up internally?

**Comment by framerate** [comment]
Also, just updated my package.json to make sure I had latest hubot core stuff and saw this:

```├── concat-stream@1.5.1  extraneous
├── estraverse@4.1.1  extraneous
├── esutils@2.0.2  extraneous
├── globals@8.11.0  extraneous
├── hubot-google-images@0.2.3
├── hubot-help@0.1.2
├── hubot-slack@3.4.1
├── inquirer@0.11.0  extraneous
├── js-yaml@3.4.3  extraneous
├── json-stable-stringify@1.0.0  extraneous
├─┬ mongoose@4.2.5
│ ├─┬ mongodb@2.0.48
│ │ ├── UNMET PEER DEPENDENCY kerberos@~0.0
│ │ └── mongodb-core@1.2.21
│ └─┬ mquery@1.6.3
│   └── bluebird@2.9.26
├── optionator@0.6.0  extraneous
├── shelljs@0.5.3  extraneous
├── to-double-quotes@2.0.0  extraneous
├── to-single-quotes@2.0.0  extraneous
└── user-home@2.0.0  extraneous

npm WARN EPEERINVALID mongodb-core@1.2.21 requires a peer of kerberos@~0.0 but none was installed.```

NPM3 changed peerdependencies, could that be an issue? (or maybe I corrupted something in my package)

**Comment by michaelansel** [comment]
Both of those could easily be causing problems. Hubot does some funky stuff where the core (a module) requires things in the parent's (bot's) node_modules directory (adapter, script modules).

**Comment by framerate** [comment]
Erased the peer thing because I'm pretty sure I added mongoose to the project, not you guys.

**Comment by framerate** [comment]
I tried with npm 2.14.10 (to get rid of the flat node_modules structure) and strangely see the same empty command list behavior.

**Comment by L3K0V** [comment]
Hi, I have same issue. Cannot perform clean install of my hubot.
```
npm --version
3.4.1
```

```
node --version
v5.0.0
```

Is there some workaround?

**Comment by wojtas911** [comment]
The same here.
After installation via "yo", hubot is not working.

wojtas@ubuntu:~/hubot3$ yo hubot
                     _____________________________  
                    /                             \ 
   //\              |      Extracting input for    |
  ////\    _____    |   self-replication process   |
 //////\  /_____\   \                             / 
 ======= |[^_/\_]|   /----------------------------  
  |   | _|___@@__|__                                
  +===+/  ///     \_\                               
   | |_\ /// HUBOT/\\                             
   |___/\//      /  \\                            
         \      /   +---+                            
          \____/    |   |                            
           | //|    +===+                            
            \//      |xx|                            

? Owner User <user@example.com>
? Bot name hubot
? Description A simple helpful robot for your Company
? Bot adapter (campfire) shellgot back true
? Bot adapter campfire
   create bin/hubot
   create bin/hubot.cmd
   create Procfile
   create README.md
   create external-scripts.json
   create hubot-scripts.json
   create .gitignore
   create package.json
   create scripts/example.coffee
   create .editorconfig
                     _____________________________  
 _____              /                             \ 
 \    \             |   Self-replication process   |
 |    |    _____    |          complete...         |
 |__\\|   /_____\   \     Good luck with that.    / 
   |//+  |[^_/\_]|   /----------------------------  
  |   | _|___@@__|__                                
  +===+/  ///     \_\                               
   | |_\ /// HUBOT/\\                             
   |___/\//      /  \\                            
         \      /   +---+                            
          \____/    |   |                            
           | //|    +===+                            
            \//      |xx|                            

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "--save"
npm ERR! node v5.0.0
npm ERR! npm  v3.4.0
npm ERR! code ENOSELF

npm ERR! Refusing to install hubot as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wojtas/hubot3/npm-debug.log

[npm-debug.log.txt](https://github.com/github/hubot/files/39850/npm-debug.log.txt)

**Comment by dcrec1** [comment]
@wojtas911 you're getting this error because your `package.json` name is also `hubot`, you should change it to some other value.

**Comment by tony4d** [comment]
In other words, when `yo hubot` asks you what you want to name your bot do not choose `hubot` choose another name.

**Comment by RyFisher** [comment]
For anyone who found this via Google and is having the same issue (like I did two hours ago), I figured this out.  Rather than navigating into bin, and then running hubot, you HAVE to run it from the parent folder using
> bin\hubot

This way, you don't have to edit the bat file in the bin folder, and hubot starts responding as normal.

**Comment by loleg** [comment]
Same issue here, tested on separate Linux machines using node stable (6.2.0) as well as LTS (4.4.4). Redis is working fine, getting "Data for hubot brain retrieved from Redis".

**Comment by wulfmann** [comment]
@loleg I just want to say, you have made me feel quite stupid. after coming across this thread and seeing your comment, that's exactly what I was doing. 

Thank you.

**Comment by loleg** [comment]
If it makes you feel any better, you're definitely not alone in the
confusion. The docs should be clearer on this point, it could be echoed on
startup, etc.

**Comment by markusvanlaak** [comment]
Thansk very much. Had the same "issue"

**Comment by bkeepers** [comment]
Looks like @RyFisher [solved this](https://github.com/github/hubot/issues/1061#issuecomment-179422364). Let me know if it's still an issue for anyone.
