### ISSUE TITLE
Remove 0.8 tests because it's been EOL

### ISSUE THREAD

**Issue by technicalpickles** [github/hubot#1070]
Our tests on 0.8 have been failing for awhile, mostly related to npm install. That was a workaround in and of itself because we required a newer npm than was available on travis.

Did some looking around, and 0.8 seems to be EOL'd anyways, so I think it's safe to just remove these tests.

cc https://github.com/github/hubot/pull/1068 which updates to include newer nodes in travis

**Comment by michaelansel** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by michaelansel** [comment]
Fixed by #1068
