### ISSUE TITLE
Hubot won't start on Heroku because of node modules

### ISSUE THREAD

**Issue by joanrodriguez** [github/hubot#1071]
I installed Hubot with the yo generator and it worked fine locally. However it crashed on Heroku, throwing `node_modules/.bin/hubot not found`

yo had installed every modules in the local folder but left package.json empty. Because it also generated a gitignore containing node_modules, no dependency was getting installed on Heroku.

I solved my problem by nuking the node_modules folder with `rm -r node_modules` and then reinstalling every module with `npm install --save`

Is this normal?

**Comment by gpeden** [comment]
yes

**Comment by technicalpickles** [comment]
@joanrodriguez did you generate with https://github.com/github/generator-hubot? If so, that's a bug because it should be updating your `package.json`.

I'm going to close here since it belongs on another repo, but please let us know if you are still seeing a problem!
