### ISSUE TITLE
hubot - ES6 support

### ISSUE THREAD

**Issue by JensDebergh** [github/hubot#1072]
Hey fellow hubotters

I was wondering if it was feasible to start creating scripts for hubot in ES6/7? I know it is possible because it's just javascript.

The only reason why I'm reluctant to start developing scripts is because the hubot commands aren't listed unless they are written in coffeescript comments.

Anyone had any luck on writing scripts in vanilla javascript/ES6 and getting the hubot commands to list properly?

**Comment by michaelansel** [comment]
TL;DR; Only with unsupported hacks

The tomdoc parser only supports coffeescript right now. You can manually inject commands (not recommended) by modifying `robot.commands`, but that functionality will likely be going away soon in favor of a defined "addHelpEntry" function (or something like that).

**Comment by JensDebergh** [comment]
Thanks for the heads up. I'll wait and keep the helper function in mind.

**Comment by raine** [comment]
It would be awesome to be able to write scripts in ES6.

What are the problems aside from hubot not being able to parse JS comments?

Where would one have to do `require('babel-core/register')` to allow babel to compile ES6 in runtime?

**Comment by michaelansel** [comment]
> Where would one have to do `require('babel-core/register')` to allow babel to compile ES6 in runtime?

I would assume at the beginning of any script that uses ES6? I don't know enough about it, but that is the general pattern for any script that does something special.

**Comment by raine** [comment]
`require('babel-core/register')` would have to happen before any ES6 files are required.

**Comment by michaelansel** [comment]
Ah okay. In that case, you'd probably want to do something like this:
`000-es6-support.js`:
```javascript
require('babel-core/register')
```

`my-awesome-script.js`:
```javascript
// All the awesomeness of ES6
```

**Comment by raine** [comment]
Thanks, that seems to work great.

Is there a way to get rid of these log messages?
```
[Sat Nov 07 2015 18:20:17 GMT+0200 (EET)] INFO /hubot/scripts/000-es6-support.js is using deprecated documentation syntax
```

**Comment by michaelansel** [comment]
I think this should make it go away:
1. Change to CoffeeScript
2. Put in a tomdoc header at the top

So, `000-es6-support.coffee`:
```coffeescript
# Description:
#   Enables ES6 support
#
# Dependencies:
#   "babel-core": "<module version>"

require 'babel-core/register'
```

You'll probably still get that warning for your ES6 files though. :cry: The Hubot doc parser is CS-only, I believe.

**Comment by raine** [comment]
> The Hubot doc parser is CS-only, I believe.

Weirdly, just adding 

```
// Description:
//   whatever
```

makes warnings go away in ES6 scripts. So it seems to understand JS on some level.

**Comment by cycomachead** [comment]
The parser mostly understands JS and CS comments. :) [this-line](https://github.com/github/hubot/blob/master/src/robot.coffee#L489)

Also, just for reference, any file that gets `require`d by a script that is loaded that is loaded like normal, doesn't need documentation in a tomdoc format. It's only the stuff that goes through the `robot`'s loadFile command.

**Comment by michaelansel** [comment]
Thanks for finding that, @cycomachead! Shows how much time I've spent in that part of the code... :confused:
