### ISSUE TITLE
Steam + Hubot

### ISSUE THREAD

**Issue by jeremybras** [github/hubot#1076]
Hi,

I have a steam bot allowing me to start game servers, or simply write fun messages to the user.
Is there a way for my app to transfer the received message to hubot and then transfer hubot's answer back to the user?

Thx for any answer,
Jeremy

**Comment by michaelansel** [comment]
Sure, just write some javascript/coffeescript that will call `Robot.receive` with each message. Docs here: https://hubot.github.com/docs/adapters/development/
