### ISSUE TITLE
hubot script not being loaded by adapter, send not  being triggered.

### ISSUE THREAD

**Issue by renanvicente** [github/hubot#1078]
Hi Guys,

I am trying to create an Adapter for mattermost.
Mattermost has an outgoing webhook to hear new messages and an incoming to send messages to it.

I created an adapter that is able to send messages if I manually trigger send with the message but is not being triggered by hubot scripts.
with what I have so far I am able to receive any message and also able to send message manually triggering send like if I override receive with something like:

``` coffescript
  receive: (msg) ->
    @robot.send msg
```

every message that I send in Mattermost I receive one back from the hubot. So the communication works.

I read that `@emit "connected"` is what load the scripts but does not seems to work on this case.
I am also calling `@receive` with the TextMessage for every message.
Am I doing something wrong?

https://github.com/mattermost/platform/blob/master/doc/integrations/webhooks/Incoming-Webhooks.md
https://github.com/mattermost/platform/blob/master/doc/integrations/webhooks/Outgoing-Webhooks.md#to-be-released-in-mattermost-v12-available-now-on-master

``` coffescript
try
  {Robot,Adapter,TextMessage,User} = require 'hubot'
catch
  prequire = require('parent-require')
  {Robot,Adapter,TextMessage,User} = prequire 'hubot'
class Mattermost extends Adapter

  constructor: (robot) ->
    super robot
    @robot.logger.info "Constructor"

  send: (envelope, strings...) ->
    console.log envelope.text
    @robot.logger.info "Send"
    data = JSON.stringify({
      text: envelope.text
    })
    @robot.http(@url)
      .header('Content-Type', 'application/json')
      .post(data) (err, res, body) ->
        console.log body

  reply: (envelope, strings...) ->
    @robot.logger.info "Reply"
    for str in strings
      @send envelope.user, "@#{envelope.user.name}: #{str}"

  run: ->
    @robot.logger.info "Run"
    @token = "xxxxxxxxxxx" // some token
    @channel = "Town Square" // some channel
    @endpoint = '/hubot/incoming' // url that outgoing webhook will send to
    @url = 'http://127.0.0.1:8065/hooks/xxxxxxxxxxxxxx' // incoming webhook to send message
    @robot.router.post @endpoint, (req, res) =>
     console.log req.body
     console.log @robot.name
     if @token is req.body.token
       # Tell Hubot we're connected so it can load scripts
       @emit "connected"
       text = req.body.text
       user = @robot.brain.userForId(req.body.user_id)
       user.name = req.body.user_name
       user.room = req.body.channel_name
       message = new TextMessage(user, text)
       @receive message
       console.log message
       res.writeHead 200, 'Content-Type': 'text/plain'
       res.end()

exports.use = (robot) ->
  new Mattermost robot
```

**Comment by michaelansel** [comment]
It looks like you are emitting 'connected' on every message received? I would expect that you do that at the bottom of `run` instead (as soon as Express is configured)

**Comment by renanvicente** [comment]
I tried something like this as well but it didn't work:
```
  run: ->
    @emit "connected"
    @robot.logger.info "Run"
    @token = "xxxxxx"
    ...emitted 
```

**Comment by renanvicente** [comment]
Although, it actually seems to be loading the scripts because as soon as I do the @emit "connected" I receive the message on the console:

[Wed Nov 04 2015 00:20:19 GMT+0000 (GMT)] INFO hubot-redis-brain: Using default redis on localhost:6379

So, it is loading the scripts.
For the scripts to be able to process my messages I should only need to send all messages using @receive right?

Since I can send manually , emit seems to be working, seems like my problem is related to something that I may be doing wrong on @receive.

**Comment by michaelansel** [comment]
Correct, and your usage of `receive` looks right... Or is it supposed to be `@robot.receive`? I don't remember

**Comment by renanvicente** [comment]
I tried with @receive, @robot.receive, even tried to create a self = @ and then do a self.receive. None of them worked.

**Comment by michaelansel** [comment]
Hmmm, not sure then. Haven't messed with the adapter side of things recently. I'll try to look at this when I get some free time, but that might not be for a while... :sob: :sweat:

**Comment by renanvicente** [comment]
Thanks, I will keep messing with it in the meantime to see if I can get it working.

**Comment by renanvicente** [comment]
I took a look in how some scripts respond and I saw that it does using robot.respond
from the docs:
"""
The robot.respond /open the pod bay doors/i callback is only called for messages that are immediately preceded by the robot's name or alias. If the robot's name is HAL and alias is /, then this callback would be triggered for:

    hal open the pod bay doors
    HAL: open the pod bay doors
    @HAL open the pod bay doors
    /open the pod bay doors
"""
I printed ```@robot.name``` to be sure the name was correct
```
myhubot
```
the print of my TextMessage
```
{ user: 
   { id: 'mgwaxxxxxn8ip8nw7xxxxxxx',
     name: 'renan',
     room: 'town-square' },
  text: 'myhubot help',
  id: undefined,
  done: false,
  room: 'town-square' }
```

I don't know if the id: undefined could be something related. So, I pass some id just to test
```
{ user: 
   { id: 'mgwaxxxxxn8ip8nw7xxxxxxx',
     name: 'renan',
     room: 'town-square' },
  text: 'myhubot help',
  id: 'mgwaxxxxxn8ip8nw7xxxxxxx',
  done: false,
  room: 'town-square' }
```
From what I saw from other adapter seems like my text is in the correct syntax as well. Could this done: false be something related? When is it changed to true?

**Comment by renanvicente** [comment]
I also noticed that the example on https://github.com/github/hubot/blob/master/docs/adapters/development.md
has in run:

```
    user = new User 1001, name: 'Sample User'
    message = new TextMessage user, 'hubot test', 'MSG-001'
    @robot.receive message
```
 but it doesn't trigger send as well if I create any script fro it:
```
  send: (envelope, strings...) ->
    @robot.logger.info "Send"
```

script:
```
  robot.respond /test/i, (res) ->
    console.log 'test passed'
    robot.send "test passed"
    res.send "test passed"
```

**Comment by renanvicente** [comment]
Found the issue, was the damn import.
changed my import to the follow and it worked:
```
Robot = require("hubot").Robot
Adapter = require("hubot").Adapter
{TextMessage} = require("hubot").TextMessage
```

**Comment by renanvicente** [comment]
I didn't solve it actually but I found the problem.

If I import it passing the whole path for the hubot it works like:
```
Robot         = require '/Users/renanvicente/hubot-project-mattermost/hubot/node_modules/hubot/src/robot'
Adapter       = require '/Users/renanvicente/hubot-project-mattermost/hubot/node_modules/hubot/src/adapter'
{TextMessage} = require '/Users/silrenan/hubot-project-mattermost/hubot/node_modules/hubot/src/message'
```
but if I try something like:
```
Robot = require("hubot").Robot
Adapter = require("hubot").Adapter
{TextMessage} = require("hubot").TextMessage
```
or
```
  {Robot,Adapter,TextMessage,User} = require 'hubot'
```
it doesn't work.

I found that it is because when I use the two methods that are not working it uses the hubot on the node_modules of the adapter instead of the hubot on my hubot directory.

I am using to have the dependency on hubot on my adapter as follow on my package.json
```
  "dependencies": {
  },
  "peerDependencies": {
    "hubot": ">=2.1.6"
  },
  "devDependencies": {
    "coffee-script": ">=1.2.0"
  }
```
is there a special way I should create for development environment?

**Comment by michaelansel** [comment]
Try this:
```coffeescript
Robot = require 'hubot/src/robot'
Adapter = require 'hubot/src/adapter'
{TextMessage} = require 'hubot/src/message'
```

Also, you shouldn't need to have hubot installed globally: `npm uninstall -g hubot`

**Comment by renanvicente** [comment]
It didn't work. It just does not work when using with npm link. If I publish a package to use it. It works fine with all kind of import that I tried before. The problem is just when developing. For now I am doing a symbolic link manually to the node_modules of my hubot. So I wonder if I am doing something wrong or if the docs in https://hubot.github.com/docs/adapters/development/ are outdated.

**Comment by technicalpickles** [comment]
> It just does not work when using with npm link

I think we've had problems in general with npm link, not just for adapters: https://github.com/github/hubot/issues/804

>  So I wonder if I am doing something wrong or if the docs in https://hubot.github.com/docs/adapters/development/ are outdated.

I think it's less likely they are out of date as just incomplete. There historically haven't been many docs for adapters, and what we have there is an improvement to what there has been before :sweat:

**Comment by robbiet480** [comment]
This also just bit me! I just undid the `npm link` and instead did an `npm install` and am modifying the local node_modules version of my adapter and then will save changes back upstream.
