### ISSUE TITLE
Hubot - robot.http get method returns null body & res.  Suspecting hubot timing out

### ISSUE THREAD

**Issue by sggncucumber** [github/hubot#1080]
Hubo hear is invoking rest api (written node.js) which in turn returns the screenshot url post processing.  Since the call would take few mins(3 mins max) hubot is timing out hence I am getting NULL body and res so I could not even check the status code or so.

How to fix the time out issue with hubot.  Need your help at the earliest.

sample code,

  robot.hear /(.*)command text/i, (res) ->
    robot.http("http://localhost:9050/command")
    .get() (err, res1, body) ->
      res.reply "#{body}"

Here body is displaying as NULL in the rocket chat message.  and suspecting the hubot's timeout.  Your help is much appreciated...

Regards,
Ganesan S

**Comment by sggncucumber** [comment]
Following error is what I am getting as part of get method call...

Error: socket hang up

**Comment by sggncucumber** [comment]
Anybody there for the help!!!

**Comment by sggncucumber** [comment]
The flow is like this,

1.  user would type the command in ROCKET CHAT
2.  It would be heared by HUBOT which in turn calls another rest api (built on nodejs)
Since node js would trigger the another script to get the result URL sometimes it would take more time to respond back.
3.  If rest api takes more time then HUBOT simply timedout and return NULL as message body instead of resultant URL.  However NodeJS works properly how it suppose to be.

Need your helpt o tweak the HUBOT so that it would wait for longer running scripts.  Anything like timeout etc., at HUBOT end???

Your help is much appreciated!!!

**Comment by technicalpickles** [comment]
In general, it's important to do error handling when making http calls. `body` will be undefined if there's an `error`. See https://github.com/github/hubot/blob/master/docs/scripting.md#error-handling for some examples.

There's not a timeout as far that's hubot specific. `robot.http` is using https://github.com/technoweenie/node-scoped-http-client which is just a wrapper around the builtin http/https clients. There is a way to configure a timeout, but your code snippet didn't include it (just add `.timeout(2000)` for example).

It sounds like a problem with the rest API. Are you able to use the /command endpoint from something that isn't hubot?

**Comment by bostonaholic** [comment]
@technicalpickles When I add the timeout like you suggested I get the following error:

**Comment by technicalpickles** [comment]
@bostonaholic I would make sure you are able to use `url` from something aside from hubot, ie `curl` from the command line.

**Comment by bostonaholic** [comment]
@technicalpickles I can. And the code works fine without the `.timeout`. I want to add the timeout because the response can take a few seconds, maybe even up to 10, to respond sometimes.

**Comment by huiminzeng** [comment]
@technicalpickles , i have got the same problem. However, i can't use my     url normally, because it is secured. I ran curl command line, and i got this:

    curl performs SSL certificate verification by default, using a "bundle"
     of Certificate Authority (CA) public keys (CA certs). If the default
     bundle file isn't adequate, you can specify an alternate file
     using the --cacert option.
    If this HTTPS server uses a certificate signed by a CA represented in
     the bundle, the certificate verification probably failed due to a
     problem with the certificate (it might be expired, or the name might
     not match the domain name in the URL).
    If you'd like to turn off curl's verification of the certificate, use
    the -k (or --insecure) option.

Can Hubot call this secured API ?
