### ISSUE TITLE
Depressing Pug Picture

### ISSUE THREAD

**Issue by ecerta** [github/hubot#1084]
So, after I put in a "pug me" command, one of the pictures I got back was this one:

http://29.media.tumblr.com/tumblr_lix7oiibrm1qbx3hwo1_500.jpg

It was a bit startling to see an abused, emaciated pug come up, and I was wondering if there was any way to maybe edit the pug picture base (wherever that is).

**Comment by michaelansel** [comment]
Unfortunately not something we have much control over: https://github.com/hubot-scripts/hubot-pugme/blob/master/src/pugme.coffee

@technicalpickles do you know anything about the Heroku app?

**Comment by technicalpickles** [comment]
I've tried to track it down at different points, but either I've forgotten or never found it :sweat:  I think at best we can filter that URL in the pugme script though, but it's not something we can do in this repo.

cc @maddox as someone who might now about pugme.herokuapp.com?

**Comment by maddox** [comment]
:+1: Took care of it. No more sad pugs.
