### ISSUE TITLE
bug(hubot@2.17.0): adapters don't run script

### ISSUE THREAD

**Issue by douglasduteil** [github/hubot#1086]
Hi

I tried to run a separate Shell adapter from the code source to find out how to make our own at @ze-jarvis .
But I had a strange result while cloning the exact Shell adapter from the source code.

---

I clone the Shell adapter code form the last commit https://github.com/github/hubot/blob/b9069d0dde6923380dde173d7b5949882dc50f79/src/adapters/shell.coffee

And publish it as a separate adapter named `SShell` here : https://www.npmjs.com/package/hubot-sshell

Then I generate a brand new hubot form the generator and install my adapter with

```sh
npm i -S hubot-sshell
```

Then run the 

```sh
./bin/hubot -a sshell 
```

Aaaand my hubot fails to ping :(

```sh
Hubot> hubot ping
Hubot> 
```

---

Do you have any clue of why the scripts, like `hubot-diagnostics` in my `external-scripts.json`, are not running ?

Thanks

\cc @linsolas @paulsouche @astotz

**Comment by michaelansel** [comment]
Does it work if you "npm install hubot@2.16.0"?

**Comment by bhuga** [comment]
Worried that this is a 2.17 regression, I dug into this a bit and replicated it. I'm not sure what's happening yet. Using the regular shell adapter works fine.

What I came up with is that the `TextMessage`s this adapter produces have a `message.constructor.name` of `TextMessage`, but `message instanceof TextMessage` is `false`. The matcher only attempts to match `TextMessage`s so all messages are misses. I'm still trying to figure out why this might be.

**Comment by michaelansel** [comment]
@douglasduteil did you update this line? https://github.com/github/hubot/blob/b9069d0dde6923380dde173d7b5949882dc50f79/src/adapters/shell.coffee#L9

That `require` should be failing unless you pointed it to 'hubot/src/message'

**Comment by douglasduteil** [comment]
Hum... not working with hubot@2.16.0 either

**Comment by douglasduteil** [comment]
@michaelansel I'm using the `TextMessage` from hubot like in the doc 
https://github.com/douglasduteil/hubot-sshell/blob/b1c54a8adb02ec4bfdb62296674c2fc51e9182d6/src/sshell.coffee#L2 (see https://hubot.github.com/docs/adapters/development/#gotchas)

**Comment by douglasduteil** [comment]
@bhuga 

> What I came up with is that the TextMessages this adapter produces have a message.constructor.name of TextMessage, but message instanceof TextMessage is false

Alright your trick is working for me too. I mean, I had to uninstall the hubot in the linked package to make it work...

**Comment by douglasduteil** [comment]
I publish a new version of the [SShell](https://www.npmjs.com/package/hubot-sshell) with `hubot@2.17.0` that seems to work. But the development process is a bit broken now.

The `npm link` will always create a sub-`hubot` dependency that is not the running one like

```sh
abot@0.0.0 /home/x/tmp/abot
├── hubot@2.17.0 
└─┬ hubot-sshell@1.0.0 -> /home/x/github/douglasduteil/hubot-sshell
  └── hubot@2.17.0 
```

So I guess that there are two solutions

- We can manually remove the second `hubot` dependency after `npm link` in the adapter folder
- We can use Duck Typing instead of `instanceof` for critical public constructor like `TextMessages`

What you think ?

**Comment by bhuga** [comment]
I'd be up for replacing the `message.instanceof TextMessage` with a `typeof message.matcher is "function"` if you want to make a PR for that. @michaelansel or @technicalpickles might have a different opinion though.

**Comment by michaelansel** [comment]
If we want to go the ducktyping route, we need to define what it means to be a TextMessage and document it. I'm fine with ducktyping as long as we can be consistent.

**Comment by technicalpickles** [comment]
I think this is related to https://github.com/github/hubot/issues/804 , check that out for some workarounds.

**Comment by technicalpickles** [comment]
Specifically: `NODE_PATH=node_modules bin/hubot` should work when you have an npm-linked hubot or adapter.
