### ISSUE TITLE
Propose adding Hubot-Mattermost to list of Hubot adapters

### ISSUE THREAD

**Issue by it33** [github/hubot#1089]
[Mattermost](mattermost.org) is an open source Slack-alternative written in Golang and React. The [Hubot-Mattermost](https://github.com/renanvicente/hubot-mattermost) adapter now works on [Mattermost v1.2.1 and higher](http://www.mattermost.org/mattermost-v1-2-easy-onboarding-enhanced-search-community-applications/). 

Propose including Hubot-Mattermost on https://hubot.github.com/docs/adapters/

Huge thanks to @renanvicente!

**Comment by heitorlessa** [comment]
+1

**Comment by tarebyte** [comment]
@it33 you could open a PR to this file https://github.com/github/hubot/blob/master/docs/adapters.md if you really want it on the list.

**Comment by heitorlessa** [comment]
PR created: https://github.com/github/hubot/pull/1090

Only awaiting for Github CLA to be updated

**Comment by technicalpickles** [comment]
This was added, thanks!
