### ISSUE TITLE
Rename Hubot at runtime

### ISSUE THREAD

**Issue by pchaigno** [github/hubot#1093]
Is there a way to rename Hubot at runtime (using a script)?
I tried the following code with no effect.

``` coffee
robot.name = 'hubot_'
```

How should I proceed if I want to add this functionality?

**Comment by bhuga** [comment]
This will be pretty tough. `robot.respond` invocations resolve hubot's name at load time and create a regex from it. Each `respond` listener's regex would need to be updated, and it's not particularly simple to identify `respond` vs `hear`.

The guts of this behavior are in in `respond` and `responsePattern` in `robot.coffee` if you want to dig deeper.

**Comment by pchaigno** [comment]
Wouldn't reloading the scripts achieve the same result?

**Comment by michaelansel** [comment]
@pchaigno yes, but reloading is non-trivial and currently unsupported cc #715
