### ISSUE TITLE
hubot shell adapter output hard to read on light terminal

### ISSUE THREAD

**Issue by glensc** [github/hubot#1102]
hubot shell adapter output hard to read on light terminal

![screenshot at 2015-12-19 02 06 30](https://cloud.githubusercontent.com/assets/199095/11909865/3bbc01de-a5f5-11e5-8c61-2ed4c4a9df0b.png)

that bold green is too light and small contrast

**Comment by technicalpickles** [comment]
How does bold text look for you? Right now the output is bold green, but we can remove green. Relevant code is https://github.com/github/hubot/blob/master/src/adapters/shell.coffee#L20

**Comment by glensc** [comment]
bold text should be ok, as it will be just black
