### ISSUE TITLE
Allow disabling external script(s) via ENV variable

### ISSUE THREAD

**Issue by radeksimko** [github/hubot#1107]
I personally run hubot in multiple environments, also locally and I would like to be able to disable certain scripts per environment.

For example I'd like to be able to set the following:

```
export HUBOT_EXCLUDE_EXT_SCRIPTS=hubot-s3-brain
```

and put it into my `docker-compose.yml` or generally anywhere where it gets loaded for myself & other devs when debugging Hubot locally.

Then devs don't have to deal with accessing the brain or even creating mock for the brain or changing `external-scripts.json` manually (then forgetting to put things back before sending a PR).

Another solution may be `HUBOT_EXTERNAL_SCRIPTS_PATH` or `HUBOT_EXCLUDE_EXTERNAL_SCRIPTS_PATH` for a json file similar to `external-scripts.json` that would be excluding scripts.

I'm happy to send a pull request for this if there's any chance it will get merged (i.e. if there's any interest in such feature).

**Comment by technicalpickles** [comment]
I can definitely appreciate wanting to do this. I'm not sure about using environment variables to do this though. Environment variables and `hubot-scripts.json` and `external-scripts.json` are a bit opaque.

I started working in https://github.com/github/hubot/pull/1110 to make it possible to programatically build a hubot. I'm imagining having more control of what is being loaded there, rather than making a ton of different environment variables.

Some other ideas:

* add support to an option hubot-s3-brain to be a no-op
* iterate on `external-scripts` format to make it possible to customize when those scripts are loaded

**Comment by radeksimko** [comment]
> add support to an option hubot-s3-brain to be a no-op

That's also something that came up on my mind before submitting this issue, but I realised that such concept isn't very well scalable. We can't expect each brain or another module to add this to the codebase. This approach seems a bit hacky to me.

> iterate on external-scripts format to make it possible to customize when those scripts are loaded

I kind of like the current simple format (list of strings) of that file. Also using ENV variables seems to be the preferred approach to control environment differences in docker deployments & [12-Factor apps](http://12factor.net/config) generally.

I understand the first suggestion may not fit well into the current concept, but what do you think of the alternative solutions - i.e. `HUBOT_EXTERNAL_SCRIPTS_PATH` or `HUBOT_EXCLUDE_EXTERNAL_SCRIPTS_PATH`?

The idea was to have something like `dev-exclude-ext-scripts.json` and point `HUBOT_EXCLUDE_EXTERNAL_SCRIPTS_PATH` to that filename:
```json
[ "hubot-s3-brain" ]
```

and then let hubot to load both `external-scripts.json` & `dev-exclude-ext-scripts.json`, do simple matching one-by-one and only load the scripts that are actually allowed.

I personally like the last option as user doesn't have to repeat themselves per each environment, but it also means some extra logic in hubot itself, the first option `HUBOT_EXTERNAL_SCRIPTS_PATH` would be probably just 3 lines of code.

**Comment by technicalpickles** [comment]
I'm really leaning towards doing this  as I'm talking about in https://github.com/github/hubot/pull/1110, that is:

```
if process.env.HUBOT_PERSISTENCE is 's3'
  robot.loadScriptPackage require('hubot-help')
```

That would be in your own hubot, so you can turn things on and off with environment variable, but you have a lot more control over the end product.

> I personally like the last option as user doesn't have to repeat themselves per each environment, but it also means some extra logic in hubot itself, the first option HUBOT_EXTERNAL_SCRIPTS_PATH would be probably just 3 lines of code.

The lines of code aren't what I'm worried about even if it's 'only' 3. Right now there are just a ton of different ways to configure hubots (hubot-scripts.json, external-scripts.json, your own `scripts`, and tons of a ways to configure, and they aren't always very discover.
