### ISSUE TITLE
Hubot behind a proxy v.2

### ISSUE THREAD

**Issue by CezaryRynkowski** [github/hubot#1108]
Hi i have a problem, yesterday i was trying to deploy hubot with HipChat adapter, on centos server with proxy :(.
I know this problem was few times in Issues but none of the solutions didn't work for me. 
I cant ever deploy it, when i trying i have this statements:

``` bash
HUBOT_HIPCHAT_JID="1234321@chat.hipchat.com" HUBOT_HIPCHAT_PASSWORD="password" HUBOT_HIPCHAT_XMPP_DOMAIN="chat.hipchat.com" HUBOT_LOG_LEVEL="debug" bin/hubot -a hipchat > /tmp/log.txt

[hubot@sql2 AI]$ cat /tmp/log.txt
AI@0.0.0 /opt/AI
+¦¦ hubot-xmpp@0.2.1  extraneous
L¦¦ proxy-agent@2.0.0  extraneous

[Thu Jan 07 2016 17:04:11 GMT+0100 (CET)] DEBUG Loading adapter hipchat
[Thu Jan 07 2016 17:04:11 GMT+0100 (CET)] DEBUG HipChat adapter options: {"jid":"1234321@chat.hipchat.com","password":"password","token":null,"rooms":"All","rooms_blacklist":"","rooms_join_public":true,"host":null,"bosh":{"url":null},"autojoin":true,"xmppDomain":"chat.hipchat.com","reconnect":true}
[Thu Jan 07 2016 17:04:11 GMT+0100 (CET)] INFO Connecting HipChat adapter...
[Thu Jan 07 2016 17:04:11 GMT+0100 (CET)] DEBUG Disconnecting here
[Thu Jan 07 2016 17:04:11 GMT+0100 (CET)] INFO Connection went offline
```
And so on to
```
[Thu Jan 07 2016 17:04:11 GMT+0100 (CET)] ERROR RangeError: Maximum call stack size exceeded
```

I tried to modify node_modules/scoped-http-client/src/lib/index.js as one of u guys suggested. 
I dont know docker very well, maybe this could solved my problem? 
Please help

**Comment by technicalpickles** [comment]
Check out https://github.com/github/hubot/pull/1092/files for some updated documentation. It's possible that it's going to be specific ot the hipchat adapter though.

**Comment by 415DomSmith** [comment]
Hey @CezaryRynkowski, I'm having the same problem... like exactly. I'm deploying to an OpenStack node with CentOS, using Terraform and Chef, behind a proxy.... and it's kicking my butt.

Did pickles link help? Were you able to solve your issue?

**Comment by michaelansel** [comment]
I think the problem here is that you are trying to connect prior to script loading (the documentation only addresses HTTP connections _after_ scripts have loaded and only those using `robot.http`). Without programmatic launching or hand-modifying `robot.coffee`/the hipchat adapter, there isn't an easy way to do this in code. I'm not sure, but there might be a way to do this at the OS level (proxychains comes to mind).

**Comment by 415DomSmith** [comment]
That's exactly the issue @michaelansel

**Comment by CezaryRynkowski** [comment]
[This](https://github.com/markstory/hubot-xmpp) solved my problem

**Comment by pixelrebel** [comment]
@CezaryRynkowski How did that solve your problem?  I followed the example here:

https://github.com/github/hubot/pull/1092/files

but the xmpp adapter doesn't seem to be using the proxy.
