### ISSUE TITLE
Upgrade coffeescript version

### ISSUE THREAD

**Issue by clayreimann** [github/hubot#1112]
Is there a reason that the version of coffee is pinned to `1.6.3`, it's nearly 2 years old?

**Comment by technicalpickles** [comment]
That's only what hubot (the library) depends on. If you `npm install --save coffee-script`, that version will be used instead.

**Comment by technicalpickles** [comment]
https://github.com/github/hubot/pull/863 for some background

**Comment by technicalpickles** [comment]
If anyone would be interested in testing updating this dependency to a newer version, I'd be happy to review a PR. The main concern would be this potentially affects any existing hubot install unless they have their own version specified in `package.json`.

**Comment by yash14123** [comment]
Is this open? I wish to contribute to this.

**Comment by technicalpickles** [comment]
It is. https://github.com/github/hubot/blob/master/package.json#L21 shows the version is pinned at 1.6.3

The biggest worry is that there have been versions of coffeescript between then and now that haven't been fully backwards compatible, combined with the installed `bin/hubot` calls the `npm install` versioned (`node_modules/.bin/coffee`). The upside is that a user of hubot can `npm install --save coffee-script` to get a more recent version, and that would replace `node_modules/.bin/coffee`.

**Comment by technicalpickles** [comment]
This will be addressed by moving hubot's core to javascript, and letting users configure their own coffeescript version.
