### ISSUE TITLE
Allow for non-integer user id in the shell adapter.

### ISSUE THREAD

**Issue by kengz** [github/hubot#1117]
Under `hubot/src/adapters/shell.coffee` line 45, the user id is parsed as integer. For generality, can we remove the `parseInt` and allow for `string` type id? Many adapters and chat clients use non-integers too.

**Comment by technicalpickles** [comment]
That is what I'm proposing in https://github.com/github/hubot/pull/1052

**Comment by kengz** [comment]
@technicalpickles my bad; didn't see that when I was searching for the issue.
