### ISSUE TITLE
Hubot adapter for Skype for Business?

### ISSUE THREAD

**Issue by pholleran** [github/hubot#1118]
**Background**

I am working with a customer that is piloting ChatOps. They have installed and configured Hubot against trial installations of Slack and HipChat to compare their options. However, the customer's enterprise chat solution is Skype for Business (formerly Microsoft Lync) deployed on-prem.

**Question**

Is there a way to use Hubot with Skype for Business on-prem? The existing solutions on GitHub and elsewhere make use of the deprecated Skype API, and I am fairly certain Skype for Business does not support that API anyway, as it is more aligned with the former Lync than the consumer Skype product.

**Comment by technicalpickles** [comment]
> the existing solutions on GitHub and elsewhere make use of the deprecated Skype API

Are you referring to https://github.com/netpro2k/hubot-skype? There is also https://www.npmjs.com/package/hubot-skype-web cc @sdimkov

> Is there a way to use Hubot with Skype for Business on-prem? 

I'm not aware, but I haven't done any research either. It does seem to have an API (https://msdn.microsoft.com/en-us/office/mt124990.aspx) so it'd be feasible for someone to implement a hubot adapter.

**Comment by pholleran** [comment]
> Are you referring to https://github.com/netpro2k/hubot-skype?
Yes
>> Microsoft has stated that they will be dropping support for the Skype desktop API. This adapter will likely stop working in the very near future (If it hasn't already... this change was slated for December 2013).

>https://www.npmjs.com/package/hubot-skype-web
Yes, but this solution requires Skype web (not on-prem)

Thanks for the quick follow-up @technicalpickles.

**Comment by sdimkov** [comment]
Just to confirm - None of the mentioned adapters (including mine) is capable of running Skype for Business on-premise.

The only potential solution I can think of right now is XMPP.
Lync sever supports XMPP gateway which means you could use [hubot-xmpp](https://github.com/markstory/hubot-xmpp) or you could write a Skype-for-Business adapter based on it. You'll need to deploy Edge Server as part of your setup. Read more [here](https://technet.microsoft.com/en-us/library/dn933894.aspx)

**Comment by jd-carroll** [comment]
@pholleran @sdimkov I would be **very** interested in collaborating on a Skype for Business on-premise integration.  I might even be able to get a couple of resources dedicated to helping on this.

I'll see what I can make of the resources listed above.

**Comment by drobati** [comment]
I've also got interest in this functionality. I'm almost tempted to take a shot at it.

**Comment by cyberkov** [comment]
Hello!
I tried to get this running the last few weeks and failed miserably. I am using Lync 2013 and at least for this release the XMPP functionality does not provide access to the persistent chatrooms. But I found a workaround which might be interesting:
The [libpurple-sipe](http://sipe.sourceforge.net) plugin supports persistent chats and therefore I've been able to access them with Pidgin. [bitlbee](https://www.bitlbee.org) is a bridge between IM and IRC (which hubot supports :-) ) and I've been able to connect to Lync with that and use direct messaging. 
Unfortunately joining the chatroom with bitlbee does not yet work, but I think it's going to be only a matter of time. A bug report for that has been filed at https://bugs.bitlbee.org/ticket/1219

I hope this helps.
Cheers
Hannes

**Comment by amandadebler** [comment]
The right approach probably involves the Persistent Chat Server role, which provides the rough equivalent of Slack channels. According to Tom Morgan (https://github.com/tomorgan), who is definitely one of the foremost experts on Skype for Business dev (http://www.thoughtstuff.co.uk/lync-development-101/), you would probably target the Persistent Chat SDK: https://msdn.microsoft.com/en-us/library/office/dn454982(v=office.16).aspx. The fact that it's still called the "Lync Server 2013 Persistent Chat SDK," however, makes me wonder if one of the newer Skype for Business Web APIs might be a better fit for Hubot. Microsoft claims that the Persistent Chat SDK works with Skype for Business on-prem, but not Skype for Business Online.

(caveat: I am a Skype for Business admin who mucks around a bit with PowerShell, NOT a hard-core dev!)

**Comment by mbettan** [comment]
Hello,

I am wondering if there is any update on this thread? Any success for this integration?
What would be the best way to integrate with Skype for business on-prem?

Thanks

**Comment by soumya-digi** [comment]
Any updates?  What about using the Microsoft Bot Framework?
