### ISSUE TITLE
Create a function

### ISSUE THREAD

**Issue by astus08** [github/hubot#1125]
Hello everyone, 
I am just getting started with hubot and I would like to know how to create a function that we can use several times in the same code.
When I try to make a function I get this error line in the console:

> SyntaxError: reserved word "function"

I have used several code and I got always the same error.
So my question is: How do we create a function with Hubot?

Thanks for your help

**Comment by technicalpickles** [comment]
Can you share the code that caused the error? It's hard to say without it. Also are you using javascript or coffeescript?

My only guess is you are trying to declare a function in coffeescript, but the syntax is a little different than you are used to in javascript:

```coffeescript
yourFunction = (firstArg, secondArg) ->
  # do stuff here
```

**Comment by astus08** [comment]
Thanks, it's now working.

But now, I would create a function and include it in the other files.
I have created a function to manage the user's  permissions. But I can't call it in an other file.
I have 1 file for my permission function and I would be able to create new files.

I'm actually using coffescript.

thank you for your help.

**Comment by technicalpickles** [comment]
At this point, this is a pretty general nodejs / coffeescript question, so it's hard to include documentation for everything. I will suggest something like https://arcturo.github.io/library/coffeescript/06_applications.html for covering structuring your project, including files & functions from one place in other parts of the application.

For hubot's I work on, it usually looks like:

* `lib/your_function.coffee`
* `scripts/your-awesome-script.coffee`

In `lib/your_function.coffee`:

```coffeescript
modules.exports = () ->
  # rest of function here
```

In `scripts/your-awesome-script.coffee`:

```coffeescript
yourFunction = require('../lib/your_function.coffee')

# rest of file here, but call yourFunction() to use the function.
```
