### ISSUE TITLE
res.getHeader() method not found

### ISSUE THREAD

**Issue by john-grandy-opentable** [github/hubot#1129]
[scripting.md](https://github.com/github/hubot/blob/master/docs/scripting.md) contains code that retrieves response headers via method `res.getHeader()`

```
robot.http("https://midnight-train")
  .get() (err, res, body) ->
...
rateLimitRemaining = parseInt res.getHeader('X-RateLimit-Limit') if res.getHeader('X-RateLimit-Limit')
```

but this throws runtime error : 

> ERROR TypeError: Object #<IncomingMessage> has no method 'getHeader'

**Comment by pchaigno** [comment]
I had the same issue. Worked with `headers` instead ;)

**Comment by mklemme** [comment]
@pchaigno Mine didn't like `headers`. Ended up having to use `resp.headers['Content-Type']`.

**Comment by pchaigno** [comment]
@mklemme That's what I meant ;)
I should have post the full line of code

**Comment by bzz** [comment]
Hit the same issue. Would be nice to have scripting docs updated if that is how it's supposed to work now

**Comment by technicalpickles** [comment]
This was fixed over in https://github.com/hubotio/hubot/pull/1332

**Comment by derekriemer** [comment]
the docs at https://hubot.github.com/docs/scripting/ still use this old method.
