### ISSUE TITLE
A new adapter for Chinese pop App weixin/wechat

### ISSUE THREAD

**Issue by KasperDeng** [github/hubot#1139]
I created a new adapter for hubot for the chinese popular IM app weixin (another name is wechat) which is created by Tencent.

The hubot-weixin-adapter is running very well, it serves us in lots of scenarios and makes lots of fun for us.
In order to get more idea/enhancement and being widely used in the world, we decided to contribute the source code.
The github repo is https://github.com/KasperDeng/Hubot-WeChat

Could you help update the [adapters.md](https://github.com/github/hubot/blob/master/docs/adapters.md) for the [page](https://hubot.github.com/docs/adapters/), to add this new hubot-weixin into the adapter list and link to our github repo? Thanks in advance.

The main contributors for this adapter are
- bumblebee team 
  - [Jeff Zhu](https://github.com/kfchu)
  - [Yinsong Ma](https://github.com/eyinsma)
  - [Kasper Deng](https://github.com/kasperdeng)
- [Shouxi Huang](https://github.com/hsx1612727380)

**Comment by bkeepers** [comment]
The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320
