### ISSUE TITLE
Help setting up Hubot for development

### ISSUE THREAD

**Issue by portgasd666** [github/hubot#1141]
So I was trying to set up hubot for development and I followed the instructions and did npm link from my local clone and npm link hubot in my test hubot. But when I run the hubot it fails when requiring modules from external-scripts saying that they are not found despite them being installed in my test hubot's node_modules folder

**Comment by technicalpickles** [comment]
This is a duplicate of https://github.com/github/hubot/issues/804 The workaround is in https://github.com/github/hubot/issues/804#issuecomment-116659253:

```
export NODE_PATH=$NODE_PATH:./node_modules
```

**Comment by portgasd666** [comment]
perhaps this should be added to CONTRIBUTING.md ?

**Comment by bkeepers** [comment]
Closing a duplicate.
