### ISSUE TITLE
Content of brain.users

### ISSUE THREAD

**Issue by pchaigno** [github/hubot#1143]
Quick question: What is the intended content for [brain.users](https://github.com/github/hubot/blob/master/src/brain.coffee#L94-L98)?

0. A list of all users currently connected?
0. A list of all past and current users? 

This will help write adapters with the correct expected behavior.
Thank you.

**Comment by technicalpickles** [comment]
When hubot encounters a message from a user, the user added to the brain, so not quite either. The effect would be a list of all past and current users though if hubot has been running.

Example:

* https://github.com/github/hubot/blob/master/src/adapters/campfire.coffee#L60 calls brain.userForId
* https://github.com/github/hubot/blob/master/src/brain.coffee#L100-L113 finds the existing user or adds one

**Comment by portgasd666** [comment]
@technicalpickles but of the hubot uses some kind of persistence such as the redis-brain then the brain has all the users ever encountered across various runs of the hubot correct ?

**Comment by technicalpickles** [comment]
To step back a second:

* without an scripts like redis-brain, `brain.users` would only contain users encountered so far of this run of hubot (ie the specific process)
* with a script like redis-brain
  * the script loads the brain at startup, so previously encountered users would be available
  * new users encountered are added to `brain.users`
  * the script flushes the entire `brain` to whatever is backing it

**Comment by portgasd666** [comment]
That clears things up for me. Thanks a lot

**Comment by pchaigno** [comment]
Thanks a lot for the explanation @technicalpickles!
Do you think I should document this somewhere (and open a PR)? If so, does it make more sense as a code comment or in `scripting.md`? This issue might be sufficient though...

**Comment by technicalpickles** [comment]
There is already https://github.com/github/hubot/blob/master/docs/implementation.md for implementation details. Maybe a separate doc for persistence, or part of that one. A PR for documentation would be better than referencing a comment on a PR.

**Comment by pchaigno** [comment]
Closing in favor of #1151.
