### ISSUE TITLE
Heroku no longer works with Hubot

### ISSUE THREAD

**Issue by dylanh724** [github/hubot#1144]
`heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=`

This was on a branch that 100% worked - tried rolling back, just in case, and that one doesn't work either.

Heroku is dead to hubot now or what? Any 2016 guides? Seems like most documentation is long expired

**Comment by mklemme** [comment]
Looks like you need to spin up a web dyno. Try `heroku ps:scale web=1` or doing it from the dashboard. Here's Heroku's reference for [managing dynos](https://devcenter.heroku.com/articles/scaling#scaling)
