### ISSUE TITLE
hubot not working with systemd

### ISSUE THREAD

**Issue by marceloslacerda** [github/hubot#1152]
I have tried to configure hubot according to the example[1], but the service does not connect.

Here is what happens when I run hubot manually:

https://gist.github.com/marceloslacerda/13b8f27621b8939b694f

Notice how the "Connecting..." info is displayed correctly.
So I tried to configure hubot for systemd. This is the service file:

https://gist.github.com/marceloslacerda/cf2e24df1aad1af95acf

And the log after running # systemctl daemon-reload; systemctl start hubot

https://gist.github.com/marceloslacerda/ef1ed465a18d647011b8

Notice how the "Connecting..." message does not appear and how hubot does not respect the log level(INFO).

What am I doing wrong?

**Comment by marceloslacerda** [comment]
Looking at it more closely looks like the error message is related to hubot-slack. Nevertheless the log level is not being respected. So I guess the bug is still valid.

**Comment by bkeepers** [comment]
Looks like the other issue was resolved. Closing, but let us know if this is still an issue.
