### ISSUE TITLE
Loading .env file from within hubot

### ISSUE THREAD

**Issue by twellspring** [github/hubot#1153]
Hubot currently uses environment variables to configure the hubot instance.  bootstrap files also show the ability to load from .env.  Example:

```
# Load environment specific environment variables
if [ -f .env ]; then
  source .env
fi
```

This works as long as the .env file has `export` in front of all the variables.  
`export HUBOT_SLACK_TOKEN=xoxb-xxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx`

Common node.js practice is to use modules like dotenv or node-env-file to load variables from .env in the format 
`HUBOT_SLACK_TOKEN=xoxb-xxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx`

But that format does not work with the `source .env` method above.  

Adding `node-env-file` to bin/hubot would resolve this issue and be compatible with current functionality

```
env      = require 'node-env-file'
env('.env', {verbose: false, raise: false})
```

This will 
- only load items in .ssh that do not have export in front of them ( so will not conflict with existing .env files being sourced )
- not overwrite any environment variables that are already populated via the environment

**Comment by twellspring** [comment]
# Tests

## Gets read 
.env
```
HUBOT_SLACK_TOKEN=xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxxx
```
**Results**
```
# bin/hubot -a slack
[Mon Mar 21 2016 10:00:41 GMT-0700 (PDT)] INFO Connecting...
[Mon Mar 21 2016 10:00:42 GMT-0700 (PDT)] INFO Logged in as hubot of xxxxx, but not yet connected
[Mon Mar 21 2016 10:00:43 GMT-0700 (PDT)] INFO Slack client now connected
```

## Not read if export 
.env
```
export HUBOT_SLACK_TOKEN=xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxxx
```
**Results**

```
# bin/hubot -a slack
[Mon Mar 21 2016 10:03:00 GMT-0700 (PDT)] ERROR No services token provided to Hubot
```

## Will not overwrite
bin/hubot 
```
export HUBOT_SLACK_TOKEN=xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxxx
exec node_modules/.bin/hubot --name "hubot" --alias "!"  "$@"
```
.env
```
HUBOT_SLACK_TOKEN=this-is-a-bad-token
```
**Results**
```
# bin/hubot -a slack
HUBOT_SLACK_TOKEN
[Mon Mar 21 2016 09:54:08 GMT-0700 (PDT)] INFO Connecting...
[Mon Mar 21 2016 09:54:10 GMT-0700 (PDT)] INFO Logged in as hubot of xxxxxx, but not yet connected
[Mon Mar 21 2016 09:54:10 GMT-0700 (PDT)] INFO Slack client now connected
```

**Comment by twellspring** [comment]
## Works if .env is not present and no error messages
bin/hubot
```
export HUBOT_SLACK_TOKEN=xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxxx
exec node_modules/.bin/hubot --name "hubot" --alias "!"  "$@"
```
**Results**
```
# ls -l .env
ls: .env: No such file or directory
# bin/hubot -a slack
[Mon Mar 21 2016 10:08:07 GMT-0700 (PDT)] INFO Connecting...
[Mon Mar 21 2016 10:08:09 GMT-0700 (PDT)] INFO Logged in as hubot of xxxxxx, but not yet connected
[Mon Mar 21 2016 10:08:09 GMT-0700 (PDT)] INFO Slack client now connected
```

**Comment by SabareeshIyer** [comment]
Hi.
I'm facing a "ERROR No services token provided to Hubot" error while running Hubot on my Windows machine.
I've tried including both of the following (separately) in the bin\hubot file:
export HUBOT_SLACK_TOKEN=xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxxx
HUBOT_SLACK_TOKEN=xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxxx

A few days ago, using the first version got it working. But now it does not work anymore.

Things I did: installed yo, installed generator-hubot, ran yo hubot, added the above line to bin\hubot, then tried running ".\bin\hubot -a slack"

Any help would be appreciated. Thank you.

**Comment by SabareeshIyer** [comment]
Hi.
I fixed it. 
For anybody who's fixing the same problem:
Open up PowerShell and set environment variables like so:
[Environment]::SetEnvironmentVariable("HUBOT_ADAPTER", "slack", "Machine")
[Environment]::SetEnvironmentVariable("HUBOT_SLACK_TOKEN", "xoxb-xxx-xxx"", "Machine")

Did the job.
