### ISSUE TITLE
Add hubot-spark to list of adapters

### ISSUE THREAD

**Issue by tonybaloney** [github/hubot#1156]
please add my npm package - https://github.com/tonybaloney/hubot-spark https://www.npmjs.com/package/hubot-spark to the list, it's an adapter for Cisco Spark.

**Comment by bkeepers** [comment]
The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320
