### ISSUE TITLE
Customize Hubot's Robot boot up script

### ISSUE THREAD

**Issue by mklemme** [github/hubot#1158]
It looks like some work might be in the works for this (https://github.com/github/hubot/pull/1110) but it here any way to add an `app.use()` to the hubot boot file right now?

Trying to get Galileo setup on the hubot instance and it requires

``` javascript
var express = require('express')
var app = express()

// Require and setup mashape analytics
var analytics = require('mashape-analytics')
var agent = analytics('API', 'default-environment', {
  queue: {
    batch: 1, // turn batching on
    entries: 1 // number of entries per batch
  }
})

app.use(agent)
```

Is there a way to add this today?

**Comment by pitbull163** [comment]
I honestly tired of this development already : ' (
You can help with kiwi program ?
I need to register bot programa so he took the payment verifying that she
entered the room and gave tel goods!

24.03.2016 2:33 пользователь "Myk Klemme" <notifications@github.com>
написал:
>
> It looks like some work might be in the works for this (#1110) but it
here any way to add an app.use() to the hubot boot file right now?

**Comment by pitbull163** [comment]
boolFalse#bc799737 = Bool;
boolTrue#997275b5 = Bool;

true#3fedd339 = True;

vector#1cb5c415 {t:Type} # [ t ] = Vector t;

error#c4b9f9bb code:int text:string = Error;

null#56730bcc = Null;

inputPeerEmpty#7f3b18ea = InputPeer;
inputPeerSelf#7da07ec9 = InputPeer;
inputPeerContact#1023dbe8 user_id:int = InputPeer;
inputPeerForeign#9b447325 user_id:int access_hash:long = InputPeer;
inputPeerChat#179be863 chat_id:int = InputPeer;

inputUserEmpty#b98886cf = InputUser;
inputUserSelf#f7c1b13f = InputUser;
inputUserContact#86e94f65 user_id:int = InputUser;
inputUserForeign#655e74ff user_id:int access_hash:long = InputUser;

inputPhoneContact#f392b7f4 client_id:long phone:string first_name:string
last_name:string = InputContact;

inputFile#f52ff27f id:long parts:int name:string md5_checksum:string =
InputFile;
inputFileBig#fa4f0bb5 id:long parts:int name:string = InputFile;

inputMediaEmpty#9664f57f = InputMedia;
inputMediaUploadedPhoto#2dc53a7d file:InputFile = InputMedia;
inputMediaPhoto#8f2ab2ec id:InputPhoto = InputMedia;
inputMediaGeoPoint#f9c44144 geo_point:InputGeoPoint = InputMedia;
inputMediaContact#a6e45987 phone_number:string first_name:string
last_name:string = InputMedia;
inputMediaUploadedVideo#133ad6f6 file:InputFile duration:int w:int h:int
mime_type:string = InputMedia;
inputMediaUploadedThumbVideo#9912dabf file:InputFile thumb:InputFile
duration:int w:int h:int mime_type:string = InputMedia;
inputMediaVideo#7f023ae6 id:InputVideo = InputMedia;
inputMediaUploadedAudio#4e498cab file:InputFile duration:int
mime_type:string = InputMedia;
inputMediaAudio#89938781 id:InputAudio = InputMedia;
inputMediaUploadedDocument#ffe76b78 file:InputFile mime_type:string
attributes:Vector<DocumentAttribute> = InputMedia;
inputMediaUploadedThumbDocument#41481486 file:InputFile thumb:InputFile
mime_type:string attributes:Vector<DocumentAttribute> = InputMedia;
inputMediaDocument#d184e841 id:InputDocument = InputMedia;

inputChatPhotoEmpty#1ca48f57 = InputChatPhoto;
inputChatUploadedPhoto#94254732 file:InputFile crop:InputPhotoCrop =
InputChatPhoto;
inputChatPhoto#b2e1bf08 id:InputPhoto crop:InputPhotoCrop = InputChatPhoto;

inputGeoPointEmpty#e4c123d6 = InputGeoPoint;
inputGeoPoint#f3b7acc9 lat:double long:double = InputGeoPoint;

inputPhotoEmpty#1cd7bf0d = InputPhoto;
inputPhoto#fb95c6c4 id:long access_hash:long = InputPhoto;

inputVideoEmpty#5508ec75 = InputVideo;
inputVideo#ee579652 id:long access_hash:long = InputVideo;

inputFileLocation#14637196 volume_id:long local_id:int secret:long =
InputFileLocation;
inputVideoFileLocation#3d0364ec id:long access_hash:long =
InputFileLocation;
inputEncryptedFileLocation#f5235d55 id:long access_hash:long =
InputFileLocation;
inputAudioFileLocation#74dc404d id:long access_hash:long =
InputFileLocation;
inputDocumentFileLocation#4e45abe9 id:long access_hash:long =
InputFileLocation;

inputPhotoCropAuto#ade6b004 = InputPhotoCrop;
inputPhotoCrop#d9915325 crop_left:double crop_top:double crop_width:double
= InputPhotoCrop;

inputAppEvent#770656a8 time:double type:string peer:long data:string =
InputAppEvent;

peerUser#9db1bc6d user_id:int = Peer;
peerChat#bad0e5bb chat_id:int = Peer;

storage.fileUnknown#aa963b05 = storage.FileType;
storage.fileJpeg#7efe0e = storage.FileType;
storage.fileGif#cae1aadf = storage.FileType;
storage.filePng#a4f63c0 = storage.FileType;
storage.filePdf#ae1e508d = storage.FileType;
storage.fileMp3#528a0677 = storage.FileType;
storage.fileMov#4b09ebbc = storage.FileType;
storage.filePartial#40bc6f52 = storage.FileType;
storage.fileMp4#b3cea0e4 = storage.FileType;
storage.fileWebp#1081464c = storage.FileType;

fileLocationUnavailable#7c596b46 volume_id:long local_id:int secret:long =
FileLocation;
fileLocation#53d69076 dc_id:int volume_id:long local_id:int secret:long =
FileLocation;

userEmpty#200250ba id:int = User;
userSelf#7007b451 id:int first_name:string last_name:string username:string
phone:string photo:UserProfilePhoto status:UserStatus inactive:Bool = User;
userCon






24.03.2016 3:20 пользователь "Иван Попов" <pittbul163region163@gmail.com>
написал:
>
> I honestly tired of this development already : ' (
> You can help with kiwi program ?
> I need to register bot programa so he took the payment verifying that she
entered the room and gave tel goods!
>
> 24.03.2016 2:33 пользователь "Myk Klemme" <notifications@github.com>
написал:
>
> >

**Comment by pitbull163** [comment]
boolFalse#bc799737 = Bool;
boolTrue#997275b5 = Bool;

true#3fedd339 = True;

vector#1cb5c415 {t:Type} # [ t ] = Vector t;

error#c4b9f9bb code:int text:string = Error;

null#56730bcc = Null;

inputPeerEmpty#7f3b18ea = InputPeer;
inputPeerSelf#7da07ec9 = InputPeer;
inputPeerContact#1023dbe8 user_id:int = InputPeer;
inputPeerForeign#9b447325 user_id:int access_hash:long = InputPeer;
inputPeerChat#179be863 chat_id:int = InputPeer;

inputUserEmpty#b98886cf = InputUser;
inputUserSelf#f7c1b13f = InputUser;
inputUserContact#86e94f65 user_id:int = InputUser;
inputUserForeign#655e74ff user_id:int access_hash:long = InputUser;

inputPhoneContact#f392b7f4 client_id:long phone:string first_name:string
last_name:string = InputContact;

inputFile#f52ff27f id:long parts:int name:string md5_checksum:string =
InputFile;
inputFileBig#fa4f0bb5 id:long parts:int name:string = InputFile;

inputMediaEmpty#9664f57f = InputMedia;
inputMediaUploadedPhoto#2dc53a7d file:InputFile = InputMedia;
inputMediaPhoto#8f2ab2ec id:InputPhoto = InputMedia;
inputMediaGeoPoint#f9c44144 geo_point:InputGeoPoint = InputMedia;
inputMediaContact#a6e45987 phone_number:string first_name:string
last_name:string = InputMedia;
inputMediaUploadedVideo#133ad6f6 file:InputFile duration:int w:int h:int
mime_type:string = InputMedia;
inputMediaUploadedThumbVideo#9912dabf file:InputFile thumb:InputFile
duration:int w:int h:int mime_type:string = InputMedia;
inputMediaVideo#7f023ae6 id:InputVideo = InputMedia;
inputMediaUploadedAudio#4e498cab file:InputFile duration:int
mime_type:string = InputMedia;
inputMediaAudio#89938781 id:InputAudio = InputMedia;
inputMediaUploadedDocument#ffe76b78 file:InputFile mime_type:string
attributes:Vector<DocumentAttribute> = InputMedia;
inputMediaUploadedThumbDocument#41481486 file:InputFile thumb:InputFile
mime_type:string attributes:Vector<DocumentAttribute> = InputMedia;
inputMediaDocument#d184e841 id:InputDocument = InputMedia;

inputChatPhotoEmpty#1ca48f57 = InputChatPhoto;
inputChatUploadedPhoto#94254732 file:InputFile crop:InputPhotoCrop =
InputChatPhoto;
inputChatPhoto#b2e1bf08 id:InputPhoto crop:InputPhotoCrop = InputChatPhoto;

inputGeoPointEmpty#e4c123d6 = InputGeoPoint;
inputGeoPoint#f3b7acc9 lat:double long:double = InputGeoPoint;

inputPhotoEmpty#1cd7bf0d = InputPhoto;
inputPhoto#fb95c6c4 id:long access_hash:long = InputPhoto;

inputVideoEmpty#5508ec75 = InputVideo;
inputVideo#ee579652 id:long access_hash:long = InputVideo;

inputFileLocation#14637196 volume_id:long local_id:int secret:long =
InputFileLocation;
inputVideoFileLocation#3d0364ec id:long access_hash:long =
InputFileLocation;
inputEncryptedFileLocation#f5235d55 id:long access_hash:long =
InputFileLocation;
inputAudioFileLocation#74dc404d id:long access_hash:long =
InputFileLocation;
inputDocumentFileLocation#4e45abe9 id:long access_hash:long =
InputFileLocation;

inputPhotoCropAuto#ade6b004 = InputPhotoCrop;
inputPhotoCrop#d9915325 crop_left:double crop_top:double crop_width:double
= InputPhotoCrop;

inputAppEvent#770656a8 time:double type:string peer:long data:string =
InputAppEvent;

peerUser#9db1bc6d user_id:int = Peer;
peerChat#bad0e5bb chat_id:int = Peer;

storage.fileUnknown#aa963b05 = storage.FileType;
storage.fileJpeg#7efe0e = storage.FileType;
storage.fileGif#cae1aadf = storage.FileType;
storage.filePng#a4f63c0 = storage.FileType;
storage.filePdf#ae1e508d = storage.FileType;
storage.fileMp3#528a0677 = storage.FileType;
storage.fileMov#4b09ebbc = storage.FileType;
storage.filePartial#40bc6f52 = storage.FileType;
storage.fileMp4#b3cea0e4 = storage.FileType;
storage.fileWebp#1081464c = storage.FileType;

fileLocationUnavailable#7c596b46 volume_id:long local_id:int secret:long =
FileLocation;
fileLocation#53d69076 dc_id:int volume_id:long local_id:int secret:long =
FileLocation;

userEmpty#200250ba id:int = User;
userSelf#7007b451 id:int first_name:string last_name:string username:string
phone:string photo:UserProfilePhoto status:UserStatus inactive:Bool = User;
userCon

---------- Переадресованное сообщение ----------
От: "Myk Klemme" <notifications@github.com>
Дата: 24.03.2016 2:33
Тема: [hubot] Customize Hubot's Robot boot up script (#1158)
Кому: "github/hubot" <hubot@noreply.github.com>
Копия:

> It looks like some work might be in the works for this (#1110) but it
here any way to add an app.use() to the hubot boot file right now?

**Comment by pitbull163** [comment]
boolFalse#bc799737 = Bool;
boolTrue#997275b5 = Bool;

true#3fedd339 = True;

vector#1cb5c415 {t:Type} # [ t ] = Vector t;

error#c4b9f9bb code:int text:string = Error;

null#56730bcc = Null;

inputPeerEmpty#7f3b18ea = InputPeer;
inputPeerSelf#7da07ec9 = InputPeer;
inputPeerContact#1023dbe8 user_id:int = InputPeer;
inputPeerForeign#9b447325 user_id:int access_hash:long = InputPeer;
inputPeerChat#179be863 chat_id:int = InputPeer;

inputUserEmpty#b98886cf = InputUser;
inputUserSelf#f7c1b13f = InputUser;
inputUserContact#86e94f65 user_id:int = InputUser;
inputUserForeign#655e74ff user_id:int access_hash:long = InputUser;

inputPhoneContact#f392b7f4 client_id:long phone:string first_name:string
last_name:string = InputContact;

inputFile#f52ff27f id:long parts:int name:string md5_checksum:string =
InputFile;
inputFileBig#fa4f0bb5 id:long parts:int name:string = InputFile;

inputMediaEmpty#9664f57f = InputMedia;
inputMediaUploadedPhoto#2dc53a7d file:InputFile = InputMedia;
inputMediaPhoto#8f2ab2ec id:InputPhoto = InputMedia;
inputMediaGeoPoint#f9c44144 geo_point:InputGeoPoint = InputMedia;
inputMediaContact#a6e45987 phone_number:string first_name:string
last_name:string = InputMedia;
inputMediaUploadedVideo#133ad6f6 file:InputFile duration:int w:int h:int
mime_type:string = InputMedia;
inputMediaUploadedThumbVideo#9912dabf file:InputFile thumb:InputFile
duration:int w:int h:int mime_type:string = InputMedia;
inputMediaVideo#7f023ae6 id:InputVideo = InputMedia;
inputMediaUploadedAudio#4e498cab file:InputFile duration:int
mime_type:string = InputMedia;
inputMediaAudio#89938781 id:InputAudio = InputMedia;
inputMediaUploadedDocument#ffe76b78 file:InputFile mime_type:string
attributes:Vector<DocumentAttribute> = InputMedia;
inputMediaUploadedThumbDocument#41481486 file:InputFile thumb:InputFile
mime_type:string attributes:Vector<DocumentAttribute> = InputMedia;
inputMediaDocument#d184e841 id:InputDocument = InputMedia;

inputChatPhotoEmpty#1ca48f57 = InputChatPhoto;
inputChatUploadedPhoto#94254732 file:InputFile crop:InputPhotoCrop =
InputChatPhoto;
inputChatPhoto#b2e1bf08 id:InputPhoto crop:InputPhotoCrop = InputChatPhoto;

inputGeoPointEmpty#e4c123d6 = InputGeoPoint;
inputGeoPoint#f3b7acc9 lat:double long:double = InputGeoPoint;

inputPhotoEmpty#1cd7bf0d = InputPhoto;
inputPhoto#fb95c6c4 id:long access_hash:long = InputPhoto;

inputVideoEmpty#5508ec75 = InputVideo;
inputVideo#ee579652 id:long access_hash:long = InputVideo;

inputFileLocation#14637196 volume_id:long local_id:int secret:long =
InputFileLocation;
inputVideoFileLocation#3d0364ec id:long access_hash:long =
InputFileLocation;
inputEncryptedFileLocation#f5235d55 id:long access_hash:long =
InputFileLocation;
inputAudioFileLocation#74dc404d id:long access_hash:long =
InputFileLocation;
inputDocumentFileLocation#4e45abe9 id:long access_hash:long =
InputFileLocation;

inputPhotoCropAuto#ade6b004 = InputPhotoCrop;
inputPhotoCrop#d9915325 crop_left:double crop_top:double crop_width:double
= InputPhotoCrop;

inputAppEvent#770656a8 time:double type:string peer:long data:string =
InputAppEvent;

peerUser#9db1bc6d user_id:int = Peer;
peerChat#bad0e5bb chat_id:int = Peer;

storage.fileUnknown#aa963b05 = storage.FileType;
storage.fileJpeg#7efe0e = storage.FileType;
storage.fileGif#cae1aadf = storage.FileType;
storage.filePng#a4f63c0 = storage.FileType;
storage.filePdf#ae1e508d = storage.FileType;
storage.fileMp3#528a0677 = storage.FileType;
storage.fileMov#4b09ebbc = storage.FileType;
storage.filePartial#40bc6f52 = storage.FileType;
storage.fileMp4#b3cea0e4 = storage.FileType;
storage.fileWebp#1081464c = storage.FileType;

fileLocationUnavailable#7c596b46 volume_id:long local_id:int secret:long =
FileLocation;
fileLocation#53d69076 dc_id:int volume_id:long local_id:int secret:long =
FileLocation;

userEmpty#200250ba id:int = User;
userSelf#7007b451 id:int first_name:string last_name:string username:string
phone:string photo:UserProfilePhoto status:UserStatus inactive:Bool = User;
userCon
24.03.2016 2:33 пользователь "Myk Klemme" <notifications@github.com>
написал:

**Comment by michaelansel** [comment]
I think #1110 and #1134 are the direction we want to go. If you need something short term, feel free to run a fork with #1134 merged, but I don't think we will have it merged in the short term and the interface might change.

**Comment by bkeepers** [comment]
Looks like @michaelansel answered this, so closing. But let us know if you have any other questions.
