### ISSUE TITLE
Problem with news.coffee. Didn't fetch latest news based on my keywords.

### ISSUE THREAD

**Issue by thinhduckhoi** [github/hubot#1159]
Hi everyone, 
So i just found out about this useful script and used it on my Slack channel.
The point is sometimes it works and sometimes it doesn't.
For example, with the topic like; smartphone, technology it always give me a long list of latest news.
But when i use keywords like: aws, azure, it didn't reply anything.
So could someone tell me how to fix this problem, please?

**Comment by pitbull163** [comment]
чё?

**Comment by thinhduckhoi** [comment]
I didn't speak Russian, man!

**Comment by pchaigno** [comment]
@thinhduckhoi You should open an issue on the repository where this script is hosted. I don't think here is the right place ;)

**Comment by pitbull163** [comment]
yes,russian
24.03.2016 11:32 пользователь "thinhduckhoi" <notifications@github.com>
написал:

**Comment by pitbull163** [comment]
help the program for the bot in the telegrams,please.
I appreciate it!
24.03.2016 11:32 пользователь "thinhduckhoi" <notifications@github.com>
написал:

**Comment by thinhduckhoi** [comment]
@pchaigno To be honest, i opened this issue on all github related to hubot just i know to make sure to get help from people :(

**Comment by thinhduckhoi** [comment]
7@pitbull163 Sorry, i didn't get what you meant. :(

**Comment by pitbull163** [comment]
there is a program of communication and not only"telegrams" in it, you can
create a bot,I have it,but can't fit in their team for sale it is my store
and my details!
24.03.2016 13:59 пользователь "thinhduckhoi" <notifications@github.com>
написал:

**Comment by thinhduckhoi** [comment]
Seems like it was related to the times you're allowed to fetch news per day. But i don't understand how many times i get because 24 hours passed by and then i tried fetching news, it still didn't work.

**Comment by sprngr** [comment]
@thinhduckhoi I'm going to take a guess that if you're using the old hubot-scripts news script, that's using the google news v1 api which was deprecated in 2011. It's still functional but insanely limited for use.

**Comment by thinhduckhoi** [comment]
@sprngr Your guess is absolutely right. The coffee.news is using news v1 api. So i guess there's no other ways to fetch news, right? My intention is to get latest news in Japanese based on specific keyword.

**Comment by sprngr** [comment]
@thinhduckhoi At this point in time not from Google News, an alternate solution would have been to use the RSS feed as an alternate source but it appears they do not support it in that language.

**Comment by thinhduckhoi** [comment]
@sprngr I realized in this code, they didn't use API but still got the result from the website. Is it possible to fetch news that way? I mean from some Japanese source, for example:
http://cgi2.nhk.or.jp/news/nsearch/query.cgi?col=news&charset=utf-8&qi=3&qt=%E8%8A%B1%E8%A6%8B


https://github.com/github/hubot-scripts/blob/master/src/scripts/whatis.coffee

**Comment by sprngr** [comment]
@thinhduckhoi yep, absolutely. In this script they're using CSS selectors to parse the dom in the response body since it's just fetching a full page.

**Comment by thinhduckhoi** [comment]
@sprngr In case of urban dictionary, it has 
definitons = []
        $(".meaning").each (idx, item) ->
          definitons.push $(item).text()

I don't know how to refine this line:  $(".meaning").each (idx, item) ->

**Comment by sprngr** [comment]
@thinhduckhoi At this point I'm going to assume you don't have a strong understanding of how CSS selectors work.

In the instance of the referenced script, it's selecting all elements with the class `meaning` and iterating over it with the Array each method. It is then using the Array push method to put the text of "item", or the current element from the results of selecting all elements with the `meaning` class.

Based on the link you provided earlier, to use the similar format of the referenced script:
To get an array of search results, `.search--list li a`. For the title and text snippet you could utilize the jquery `find` method to further refine the result set. The selectors for title and text snippet respectively are `p em.title` and `p.search-note`.

Through my own research, I found that you could further simplify the contents of the script to something like:
```coffee
jsdom = require('jsdom').jsdom

module.exports = (robot) ->
    robot.respond /news (.*)$/i, (msg) ->
        jsdom.env 'http://cgi2.nhk.or.jp/news/nsearch/query.cgi?col=news&charset=utf-8&qi=3&qt=' + (encodeURIComponent msg.match[1]),
            (err, window) ->
                $ = require('jquery')(window)

                search = ''
                $(".search--list li a").each (idx, item) ->
                    search += $(item).find('p em.title').text() + '\n'
                    search += $(item).find('p.search-note').text() + '\n\n'

                msg.send if search != '' then search else 'No results found'
```

This should be a good point for you to wrap it up however you like.

A good source for further reading on selectors can be found [here](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_Started/Selectors). More info on working with jquery can be found [here](https://learn.jquery.com/).

Also, if this was sufficient to solving your problem, I'd suggest closing the other issues you had opened in the other repositories relating to this issue and any of the others that have become resolved/irrelevant in this repo to signify to others that no further assistance is required.

**Comment by thinhduckhoi** [comment]
@sprngr Thank you for taking the time to explain to me in great detail again.
I tested the code on Slack but somehow i didn't get any response.
On my terminal running hubot, it said sth like this when i was taking a test by typing: news 花見 

[Wed Mar 30 2016 15:20:22 GMT+0900 (JST)] ERROR Error: Cannot find module 'jquery'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.done (/root/myhubot/scripts/nhk.coffee:7:17, <js>:10:13)
  at /root/myhubot/node_modules/jsdom/lib/jsdom.js:271:18
  at _combinedTickCallback (node.js:376:9)
  at process._tickCallback (node.js:407:11)

**Comment by sprngr** [comment]
@thinhduckhoi That error means you need to perform an `npm install` of the missing module since your code is trying to use it. Since you want to be able to use it whenever everything is setup for your hubot instance, you'll want to run `npm install --save jquery`. That will guarantee it is added to the `package.json` file so whenever an `npm install` is run, it'll include that module.

You'll notice in the original script and the one provided, there is are the lines:
```coffee
jsdom = require('jsdom').jsdom
...
$ = require('jquery')(window)
```

Those are referring to node modules. For more information on working with Node modules, here is a link to the [official doc](https://nodejs.org/api/modules.html).

**Comment by thinhduckhoi** [comment]
@sprngr Ah thank you so much. Worked perfectly! 
Btw, may i ask you one more question?
How did you find the value .search--list li a, p em.title and p.search-note?
I took a look at page's source but didn't find anything like that.

**Comment by sprngr** [comment]
@thinhduckhoi Those values are CSS selectors; 
`.search--list` will not be found in that form since it's referring to a class value, same thing with `.title` and `.search-note`. `li`, `a`, `p`, and `em` are all HTML elements. A further explanation on how this works can be found in the link I posted earlier on [working with selectors](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_Started/Selectors).

**Comment by thinhduckhoi** [comment]
@sprngr Thanks Michael. :+1:
