### ISSUE TITLE
use hubot-mockadapter instead of hubot-mock-adapter 

### ISSUE THREAD

**Issue by gasolin** [github/hubot#1160]
I ported hubot-mock-adapter to hubot-mockadapter (plain JS), add some missing mocks like emote function, so we can get more test coverage from tests

I've done the related work on https://github.com/gasolin/webbybot

https://github.com/gasolin/webbybot/commit/845830fe8607f779317aa3ec1a2410f118ee22d9

with preference to do the following work directly on ES6 based hubot instead of coffee version #1138

**Comment by bkeepers** [comment]
The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320
