### ISSUE TITLE
Adding hubot-messenger-platform to the list of adapter

### ISSUE THREAD

**Issue by MohamedBassem** [github/hubot#1167]
Hi all,

FB announced yesterday the launch of the bots for messenger. I've created an adapter for it : https://github.com/MohamedBassem/hubot-messenger-platform

**Comment by bkeepers** [comment]
The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320
