### ISSUE TITLE
Add hubot-fb to list of adapters

### ISSUE THREAD

**Issue by chen-ye** [github/hubot#1168]
Hey!  I created a FB Messaging Platform adapter with support for:
- botside autoverification
- send/receive
- truncating messages which are too long
- image attachments
- templates and hookbacks
- delivery events
- user -> profile resolution
- responding to rich messages (images, location, etc)

Setup is very straightforward and only requires configuration facebook side, and setting a few env variables.  

https://github.com/chen-ye/hubot-fb

**Comment by chen-ye** [comment]
Now supports user (name, profile picture) resolution!

**Comment by kengz** [comment]
That's fast! link to your github repo/npm here? Btw is adding the template capability coming soon too?

**Comment by chen-ye** [comment]
whoops, forgot the url!  https://github.com/chen-ye/hubot-fb

thinking about how to implement templates.  does hubot just send raw strings, and it's up to the adapter to interpret them?

**Comment by chen-ye** [comment]
aha, i see you can add custom objects to the envelope.  I'll work on an implementation later today!

**Comment by kengz** [comment]
Not sure, I should let the hubot team member reply to that. What I know is you can implement a `customMessage` method in your adapter for sending rich format replies. 

For example the [Slack adapter has it](https://github.com/slackhq/hubot-slack/blob/1c49569b52b7774e07e158f4909b3a8e3a3a72c2/src/slack.coffee#L44) for sending attachments, by calling `robot.adapter.customMessage(<attachment>)`, where `<attachment>` [conforms to their format](https://api.slack.com/docs/attachments). An [example here](https://github.com/slackhq/hubot-slack/issues/170#issuecomment-113315455).

**Comment by chen-ye** [comment]
![templates](https://cloud.githubusercontent.com/assets/1904031/14495012/fc90fbb4-018d-11e6-9144-c694ad7c17ec.PNG)

template support!  i'll look at adapting to the custommessage syntax

will work on hookbacks next

**Comment by chen-ye** [comment]
![hookbacks](https://cloud.githubusercontent.com/assets/1904031/14503332/f9a5dcd6-01af-11e6-8a90-f8d08ff33e85.PNG)
hookbacks (and delivery events) have been implemented (see readmefor details)

**Comment by bkeepers** [comment]
The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320
