### ISSUE TITLE
Restyaboard integration

### ISSUE THREAD

**Issue by reidharry** [github/hubot#1169]
I'm looking to integrate HUBOT with [Restyaboard](https://github.com/RestyaPlatform/board)

Can I get the integration document, if any?

**Comment by ngenerio** [comment]
Hubot has documentation on how to integrate other services. There is an adapter documentation [here](https://hubot.github.com/docs/adapters/development/). You can also check out the source code of [hubot-slack](https://github.com/slackhq/hubot-slack) to get a fair idea of how adapters work. I hope this helps.

**Comment by reidharry** [comment]
Thanks a lot.

**Comment by peterdalydickson** [comment]
@reidharry Did you get anywhere with this? I'm looking at the same thing.

**Comment by reidharry** [comment]
@peterdalydickson Not yet.

**Comment by bkeepers** [comment]
Closing since there's nothing actionable to do on this repo, but let us know if you find a Restyaboard integration.
