### ISSUE TITLE
Which port is hubot running on?

### ISSUE THREAD

**Issue by thinhduckhoi** [github/hubot#1170]
Hi everyone,
I'm running hubot on my Centos 7 on AWS Instance EC2 for a few weeks with all of port open.
But now i don't want to open all port because it's very dangerous.
But i don't know which port needed to open to run hubot.
How could i do now?

**Comment by tombell** [comment]
https://github.com/github/hubot/blob/master/src/robot.coffee#L416

**Comment by ngenerio** [comment]
@thinhduckhoi hubot runs on a port specified by either `EXPRESS_PORT` or  `PORT` environment variable. It defaults to `8080`.

**Comment by technicalpickles** [comment]
It's as @ngenerio said.

**Comment by thinhduckhoi** [comment]
Thank you, guys!

**Comment by Lutacon** [comment]
Thank you!

**Comment by prashanth-sams** [comment]
@ngenerio which port actually hubot points if the 8080 is pre-occupied
