### ISSUE TITLE
Hubot & hangoutsbot integration help please

### ISSUE THREAD

**Issue by munzerelli** [github/hubot#1172]
Hi & thank you for taking the time to read this.... I have hangouts bot running in a few chats.... i started trying to set up hubot yesterday, im on an ubuntu system at the moment, both are local to this system. If i run hangoutsbot in one terminal and hubot (bin/hubot --adapter web) in another I can see the chats in both so i know hubot is seeing the chats and looks like it tries to respond but gets an error.... my hubot's name is "r386" below is a section of the log. Any help you can offer would really be great!!!

[Fri Apr 15 2016 16:40:41 GMT-0400 (EDT)] ERROR Error: listen EADDRINUSE
at errnoException (net.js:901:11)
at Server._listen2 (net.js:1039:14)
at listen (net.js:1061:10)
at net.js:1143:9
at dns.js:72:18
at process._tickCallback (node.js:415:13)

[Fri Apr 15 2016 16:40:43 GMT-0400 (EDT)] ERROR hubot-heroku-al[Fri Apr 15 2016 16:40:58 GMT-0400 (EDT)] WARNING @userForName() is going to be deprecated in 3.0.0 use @robot.brain.userForName()
[Fri Apr 15 2016 16:40:58 GMT-0400 (EDT)] WARNING @userForId() is going to be deprecated in 3.0.0 use @robot.brain.userForId()
[UgyYuUmLEfK8IYIJrwF4AaABAQ] 105280169937788698899 => r386 ping
[UgyYuUmLEfK8IYIJrwF4AaABAQ] => PONG
[Fri Apr 15 2016 16:40:58 GMT-0400 (EDT)] ERROR Error: Invalid URI "undefinedUgyYuUmLEfK8IYIJrwF4AaABAQ"
at Request.init (/home/r386/myhubot/node_modules/hubot-web/node_modules/request/main.js:170:24)
at new Request (/home/r386/myhubot/node_modules/hubot-web/node_modules/request/main.js:105:8)
at request (/home/r386/myhubot/node_modules/hubot-web/node_modules/request/main.js:995:11)
at WebAdapter.send (/home/r386/myhubot/node_modules/hubot-web/index.coffee:46:7, :60:9)
at runAdapterSend (/home/r386/myhubot/node_modules/hubot/src/response.coffee:82:34, :87:50)
at allDone (/home/r386/myhubot/node_modules/hubot/src/middleware.coffee:44:37, :34:16)
at /home/r386/myhubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
at Object.async.eachSeries (/home/r386/myhubot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
at Object.async.reduce (/home/r386/myhubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
at /home/r386/myhubot/node_modules/hubot/src/middleware.coffee:49:7, :37:22
at process._tickCallback (node.js:415:13)

[Fri Apr 15 2016 16:43:37 GMT-0400 (EDT)] WARNING @userForName() is going to be deprecated in 3.0.0 use @robot.brain.userForName()
[UgyYuUmLEfK8IYIJrwF4AaABAQ] 105280169937788698899 => /r386 whereami
[Fri Apr 15 2016 16:45:17 GMT-0400 (EDT)] WARNING @userForName() is going to be deprecated in 3.0.0 use @robot.brain.userForName()
[Fri Apr 15 2016 16:45:17 GMT-0400 (EDT)] WARNING @userForId() is going to be deprecated in 3.0.0 use @robot.brain.userForId()

**Comment by mose** [comment]
Well, it's been a year. Sorry for that very late reply and you may very well have found a solution on your own in the while. Or do you still need help?

**Comment by technicalpickles** [comment]
```[Fri Apr 15 2016 16:40:41 GMT-0400 (EDT)] ERROR Error: listen EADDRINUSE```

I think this is part of the problem. Hubot listens on port 8080, and it seems like you had something already running. You have a few options to fix that:

- run hubot with `--disable-httpd` if you don't want/need to serve HTTP from hubot
- set `PORT` environment to something else, like 8181: `PORT=8081 bin/hubot`

**Comment by technicalpickles** [comment]
Looking at the error a little more, it looks like this is coming from the adapter, hubot-web: https://www.npmjs.com/package/hubot-web

Might be be better to file an issue over on the repo for that https://github.com/sklise/hubot-web
