### ISSUE TITLE
Hubot Brain set/get Does Not Persist Between Scripts

### ISSUE THREAD

**Issue by richardwlu** [github/hubot#1173]
I have a script that sets a userId `robot.brain.set('userId', body.data.userId)` to the brain on start up but when I try to access that value from a different script `robot.brain.get('userId')` I receive a null. I can only get the value within the same script.

Is this the intended behavior? I'm looking for a way to set a key/value of userId and auth token that I can access from other scripts for persistence. 

In my `external-scripts.json` file, hubot-redis-brain exists.

**Comment by ngenerio** [comment]
@richardwlu At start up when `hubot-redis-brain` is loaded, it sets new information in the brain's data overriding or clearing anything you set in the brain. Check out #619 and #963. 

cc @technicalpickles

**Comment by richardwlu** [comment]
@ngenerio Thank you for your response! I suppose I can live with it clearing on start up (prefer persistence), but what about if this is all happening in one instance without a restart? Since I am setting the value in one script but can't access it from another script when I haven't restarted and I am using the documented get/set methods.

I am not sure if this is a bug or enhancement then. If this brain isn't truly persistent, I am curious to know how everyone else is solving this?

**Comment by ngenerio** [comment]
@richardwlu I'm curious to find out how you use the `get` method in the other script. Do you use it after the brain's `loaded` event??

**Comment by richardwlu** [comment]
@ngenerio How do I determine when its loaded? My steps are as follows:

1) I have a script where it just sits in my `/scripts` directory and starts up and makes a rest call to get auth token info and sets it to the brain
2) Then after the bot is ready, the bot will hear/listen for a command from the user and it will run another script that is supposed to get that auth token that was already set in step 1 but when I do that get, it returns `null`.

There is definitely enough time between step 1 and 2 for things to be all set and loaded unless there is a process I am missing entirely here.

**Comment by ngenerio** [comment]
I have a some simple scripts over here: I do a `set` in one and `get` in another on the `loaded` event and I get the right results.

> There is definitely enough time between step 1 and 2 for things to be all set and loaded unless there is a process I am missing entirely here.

Probably think so.

**Comment by richardwlu** [comment]
When you say on the `loaded` event, am I supposed to be calling this event?

In the snippet below, I am setting it after a successful rest call to get auth token:
```
         try
             if(body)
                 body = JSON.parse(body)
                 if body.status == 'success'
                     robot.logger.info 'Successfully logged in ' + process.env.ROCKETCHAT_USER + ' to Rocket.Chat API.\n' + util.inspect(body)
                     robot.brain.set('userId', body.data.userId)
                     robot.brain.set('apiAuthToken', body.data.authToken)
                     robot.logger.debug('apiAuthToken: ' + robot.brain.get('apiAuthToken'))
```

Then in my other script when the bot is ready, a simple `robot.brain.get('apiAuthToken')` returns `null`.

**Comment by richardwlu** [comment]
Maybe there is a conflict because I'm using a rocketchat-hubot adapter?
