### ISSUE TITLE
Add hubot-icq to a list of adapters

### ISSUE THREAD

**Issue by sclown** [github/hubot#1176]
Please add my adapter to the list. It's an adapter for ICQ with latest protocol.
https://www.npmjs.com/package/hubot-icq
https://github.com/sclown/hubot-icq

**Comment by bkeepers** [comment]
The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320
