### ISSUE TITLE
mqtt in hubot?

### ISSUE THREAD

**Issue by TinajaLabs** [github/hubot#1179]
I'd like to hook up some publish and subscribe hooks into hubot scripts but not sure where to start.  I've searched for anyone doing anything with mqtt in hubot but was unsuccessful.

I have a node-red setup where my home sensors are publishing topics that describe themselves and I have lights and "things" that subscribe to those topics.  The next thing is to create some coffee scripts that subscribe to events and publish requests, for example, to turn lights on and off.

I appreciate any advice,
Chris.

PS: Sorry if this is the wrong venue for assistance but I'll step in anyway and beg forgiveness instead of permission.

**Comment by technicalpickles** [comment]
I don't have anything concrete to suggest unforutnately. I googled `hubot mqtt` and found https://github.com/mokjpn/hubot-mqtt . There's some code in there for subscribing to stuff.

I think the main thing I can suggest is that anything you can do in node in general, you should be able to do from hubot. So as long as you can write some code in nodejs (or coffeescript), you could put it in a script and either have listeners (`robot.respond`) to call stuff or use events to post into a room (`robot.messageRoom`).

**Comment by jameswhite** [comment]
I've got some working node.js with client-side certificate authentication [over here](https://github.com/websages/standing-water/blob/master/scripts/client_cert.js) it connects to a mosquitto server with [this config](https://github.com/websages/standing-water/blob/master/etc/mosquitto/mosquitto.conf). I use it to control my lights with a [perl worker](https://github.com/websages/standing-water/blob/master/scripts/huecuba.pl).

I plan to convert the node.js to coffeescript for a hubot plugin :soon:.

**Comment by bhuga** [comment]
> I plan to convert the node.js to coffeescript for a hubot plugin 🔜.

@jameswhite hubot can load javascript without an issues; no need to convert it 😄

**Comment by jameswhite** [comment]
@bhuga you just made my day. ☀️

**Comment by jameswhite** [comment]
And @rick pointed me to http://js2.coffee/

```
mqtt = require('mqtt')
fs = require('fs')

### cleartext settings [FUNCTIONAL]
var HOST = 'test.mosquitto.org';
var PORT = 1883;
###

### test.mosquitto.org ssl settings [FUNCTIONAL]
var TRUSTED_CA_LIST = fs.readFileSync('/etc/ssl/certs/mosquitto.org.crt');
var HOST = 'test.mosquitto.org';
var PORT = 8883;
###

### bikeshed settings ###

KEY = fs.readFileSync('/etc/ssl/private/localhost.ckey')
CERT = fs.readFileSync('/etc/ssl/certs/localhost.crt')
TRUSTED_CA_LIST = fs.readFileSync('/etc/ssl/certs/ca.crt')
HOST = 'mqtt.hq.thebikeshed.io'
PORT = 8883

######

options = 
  port: PORT
  host: HOST
  ca: TRUSTED_CA_LIST
  rejectUnauthorized: false
  secureProtocol: 'TLSv1_method'
  key: KEY
  cert: CERT
  ciphers: 'ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-RSA-RC4-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES128-SHA:AES256-SHA256:AES256-SHA:RC4-SHA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!EDH'
  will:
    topic: 'node/status'
    payload: new Buffer('offline')
client = mqtt.connect('mqtts://' + HOST, options)
client.on 'connect', ->
  console.log 'Connected'
  client.subscribe '#'
  client.publish 'presence', 'Hello mqtt'
  client.publish 'presence', 'Current time is: ' + new Date
  return
client.on 'message', (topic, message) ->
  # message is Buffer
  console.log '[' + topic.toString() + '] ' + message.toString()
  client.end()
  return

# ---
# generated by js2coffee 2.2.0
```

**Comment by jameswhite** [comment]
@TinajaLabs https://github.com/mokjpn/hubot-mqtt/pull/1/files

**Comment by bkeepers** [comment]
Closing since it looks like the link @jameswhite shared solves this issue, but let me know if it doesn't.
