### ISSUE TITLE
Please add a SkypeBots adapter to the list of adapters

### ISSUE THREAD

**Issue by ivadim** [github/hubot#1181]
Hello I'm a developer of https://github.com/ivadim/hubot-skypebots adapter for Skype. 
This adapter is using new Bots API provided by Skype (http://blogs.skype.com/2016/03/30/skype-bots-preview-comes-to-consumers-and-developers/).

**Comment by bkeepers** [comment]
The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320
