### ISSUE TITLE
"heroku addons:add rediscloud" is old on the document deploying heroku 

### ISSUE THREAD

**Issue by shigemk2** [github/hubot#1182]
When I was completing the steps for deploying heroku with https://hubot.github.com/docs/deploying/heroku/, I found a warning by executing "heroku addons:add rediscloud"

```sh
$ heroku addons:add rediscloud
WARNING: `heroku addons:add` has been deprecated. Please use `heroku addons:create` instead.
```

Maybe [the source code of the document](https://github.com/github/hubot/blob/master/docs/deploying/heroku.md) is updated.

**Comment by technicalpickles** [comment]
This is fixed now. It was reported in https://github.com/github/hubot/pull/1122 but the hubot website might not have gotten the update.

**Comment by shigemk2** [comment]
Thank you!
