### ISSUE TITLE
Custom listenerMiddleware Problem

### ISSUE THREAD

**Issue by justdaver** [github/hubot#1183]
Hi All,

I'm working on an additional security layer feature for hubot involving two factor authentication with Verisign VIP and am just battling to get my head around how hubot and middleware work. 

My middleware code seems to work as expected when chatting directly to hubot (private message) but it's not working correctly when it receives messages from users in a room.

Here is my middleware code:
```
module.exports = (robot) ->

  robot.listenerMiddleware (context, next, done) ->

    allowed_commands = [ "help", "ping" ]
    # Grab just the command issued, eg "ping" and not "hubot ping"
    command = context.response.message.text.slice(10)

    # Allow if any of our excluded commands are issued otherwise deny
    if command in allowed_commands
      next(done)
    else
      context.response.send "That command is not allowed"
      done()
```
My aim with the code above is:
- if "hubot help" or "hubot ping" is issued, run it as normal...
- if anything else is issued to hubot, deny and stop

Testing from a private chat message with hubot:
```
dave> hubot blah
hubot> That command is not allowed
```
```
dave> hubot ping
hubot> pong!
```
That worked just the way I expected it too: allow certain commands and deny the rest.

Now a test from a chat room to hubot:
```
dave> hubot blah
hubot> That command is not allowed
```
Great, just as expected but now when I try issue an allowed command I get the following:
```
dave> hubot ping
hubot> That command is not allowed
hubot> That command is not allowed
```
This is my problem. I'm not sure why it's not allowing that command or why it's sending a double response back. I'm using Hubot 2.18.0 and the hubot-hipchat adapter 2.12.0

Unfortunately my coffeescript and coding skills are not great. If anyone could shed some light on this problem or possibly point me in the right direction I'd really appreciate it!

Thanks!
Dave

**Comment by justdaver** [comment]
Managed to solve this one. There were 2 issues.

When I issued something like this to hubot:
```
dave> hubot blah
```
In a room, **context.response.message.text** is:
```
hubot blah
```
While in a private message to hubot, **context.response.message.text** is:
```
Hubot:  blah
```
So to grab just the command issued to hubot, I had to check if it was issued from a room first and if so then apply a different slice..
```
    # Strip the first characters so we're left with just the command issued...
    if context.response.message.user.room?
      # hubot blah
      command = context.response.message.text.slice(6)
    else
      # Hubot:  blah
      command = context.response.message.text.slice(8)
```
Now it works the same for a room or a private message.

The next issue was where it was returning "That command is not allowed" twice in a room. This was solved by dropping the last **done()**.

For anyone interested, here's the full middleware code I'm using to intercept messages and first check if a user has verified with 2 factor authentication before the command runs. There are any pieces which work together here but this is just the middleware I'm using:
```
  # Catch all attempted commands and first check that the user is verified before allowing them
  # to run any commands. If not verified, tell them how it's done...

  robot.listenerMiddleware (context, next, done) ->

    name = context.response.message.user.name
    user = robot.brain.userForName(name)

    # Exclude some commands as all users need to be able to use verification funtions
    excluded_commands = [ "status", "users", "help", "ping" ]

    # Verify needs some regex magic...
    regex_verify = /// ^                # begin of line
      verify                            # the word "verify"
      .                                 # followed by a single space
      [0-9.]{6}                         # then exactly 6 digits, can also use [0-9][0-9][0-9][0-9][0-9]
      ///i                              # end

    # Strip the first characters so we're left with just the command issued...
    if context.response.message.user.room?
      # hubot blah
      command = context.response.message.text.slice(6)
    else
      # Hubot:  blah
      command = context.response.message.text.slice(8)

    # Allow if any core commands are issued
    if command in excluded_commands or command.match regex_verify
      next (done)
    else
      # Allow if user is currently verified
      if user.vip_status == "verified"
        next (done)
      else
        # Deny if user is not verified
        if user.vip_status == "never" or user.vip_status == "failed" or user.vip_status == "expired"
          context.response.send "Bot access denied. You need to verify first using two-factor authentication before I can trust you."
          context.response.send "To verify, type: #{robot.name} verify <your 6 digit OTP number>"
```

Thanks!
Dave

**Comment by justdaver** [comment]
@michaelansel I would really love to see how you guys are handling this with 2 factor authentication! :)

**Comment by michaelansel** [comment]
Didn't get a chance to respond right away, but a few comments:
- Use `robot.respondPattern(/(.*)/).match(context.response.message.text)` (or something pretty close to that), not sure it is official API, but I promise it is better than using `slice`.
- You should be calling `done` when denying access. If you are seeing double responses, figure out why rather than breaking the API (and potentially any other middleware). Adding in receiveMiddleware is one way to get a lot of debugging information (hooks into message processing before listener matching occurs, so you can see if there are double messages coming from the adapter or if you just have multiple listeners matching, which triggers multiple executions of the middleware stack).
- Take a look at these docs if you haven't already: https://hubot.github.com/docs/patterns/#restricting-access-to-commands
- The 2FA code I wrote is kinda gross (hence no open source yet), but I ended up separating out validation completely like it looks like you have. Currently unwritten is token expiration. I would recommend doing something like `robot.auth.hasValidSecondFactor(user)` and shoving all the logic in there. Building an API for that is somewhere on my backlog, but maybe just hacking in whatever (like what you have) is fine. I need more hours in my life... 😓 

Overall, I think this is a great use of middleware. Good luck!

**Comment by cycomachead** [comment]
Thanks for sharing this @justdaver!

(Also, thanks for posting _how_ you solved your problems, since that's always helpful!)

**Comment by justdaver** [comment]
Thanks @cycomachead no problem, much appreciated! When I've completed this project I'll upload all the bits and pieces that work together with it, hopefully someone out there might find it useful :)

**Comment by justdaver** [comment]
Thank you for taking the time to respond to my post and include some great tips @michaelansel :) Really appreciate that. I'm busy ironing out some of the bugs and reworking a few things as you suggested, once done I'll post my solution and see if anyone finds it useful. 

Please let us know when you code up a hubot module to help us all find more hours in our lives :laughing:
