### ISSUE TITLE
Installation fails at specifying adapter step

### ISSUE THREAD

**Issue by chuckdries** [github/hubot#1190]
Dumping my console output:

```
chuckdries@ubuntu1604-1:~/catlady$ yo hubot
                     _____________________________  
                    /                             \ 
   //\              |      Extracting input for    |
  ////\    _____    |   self-replication process   |
 //////\  /_____\   \                             / 
 ======= |[^_/\_]|   /----------------------------  
  |   | _|___@@__|__                                
  +===+/  ///     \_\                               
   | |_\ /// HUBOT/\\                             
   |___/\//      /  \\                            
         \      /   +---+                            
          \____/    |   |                            
           | //|    +===+                            
            \//      |xx|                            

? Owner User <user@example.com>
? Bot name catlady
? Description A simple helpful robot for your Company
? Bot adapter (campfire) 


/home/chuckdries/.node/lib/node_modules/yo/node_modules/rx/dist/rx.js:77
    throw e;
    ^
true
chuckdries@ubuntu1604-1:~/catlady$ 
```
No matter what I do, the hubot generator fails at the set adapter step. Above, I literally just pressed enter every time leaving everything (including adapter) at their defaults. No adapter I try works. If I run `yo hubot --defaults` it works, but then obviously I can't set the adapter or anything I need to set.\

**Comment by chuckdries** [comment]
If it helps, I'm running Ubuntu Server 16.04, Node 4.2.6, NPM 3.9.0 and Yeoman 1.8.1. My NPM install initially failed. I'll dump any log files if you guys tell me where to find them.

**Comment by chuckdries** [comment]
For posterity: The issue disappears if you specify the adapter with the --adapter flag, therefore skipping that part of the interactive setup. This probably still needs fixing though.

**Comment by mhnsn** [comment]
Having the same issue trying an install with Windows 8.1, Node 4.3.0, NPM 3.9.0. Not sure of Yeoman version.

**Comment by jasenhuang** [comment]
having the same issue , anyone know how to fix it ?

**Comment by chuckdries** [comment]
Specify the adapter with the “--adapter” launch flag
this skips the adapter step and seems to work for me.

On May 17, 2016, at 12:07 AM, JasenHuang <notifications@github.com> wrote:

having the same issue , anyone know how to fix it ?

**Comment by technicalpickles** [comment]
I just confirmed this. I've been able to previously run on this machine, so trying to identify what's changed. For people running into it, can you let me know the output of:

* `node --version`
* `npm --version`
* `yo --version`

**Comment by technicalpickles** [comment]
cc https://github.com/github/generator-hubot/issues/64 for the first reports of this

**Comment by technicalpickles** [comment]
A fix for this released in `generator-hubot@0.4.0`. Anyone running into this should `npm install -g generator-hubot` to get the latest.

**Comment by mhnsn** [comment]
Awesome! I actually was just posting my yo version. Comment's updated, but guess it wasn't needed.

**Comment by chuckdries** [comment]
:)
On May 19, 2016, at 5:38 PM, Mark Hansen <notifications@github.com> wrote:

Awesome! I actually was just posting my yo version. Comment's updated, but guess it wasn't needed.
