### ISSUE TITLE
Robot adapterPath parameter seems not used anywhere

### ISSUE THREAD

**Issue by gasolin** [github/hubot#1191]
According to https://github.com/github/hubot/blob/master/src/robot.coffee#L43
The parameter does not used any where

**Comment by technicalpickles** [comment]
See https://github.com/github/hubot/pull/1109 for background.  Specifically:

> The constructor still takes it as an option so it remains backward compatible
to anything that might be specifying it.

**Comment by bkeepers** [comment]
Looks like @technicalpickles answered this. Let us know if that's not accurate.
