### ISSUE TITLE
Hubot not responding to ping on OSX

### ISSUE THREAD

**Issue by bharadwajh** [github/hubot#1192]
Installed hubot but it's not responding to Pinging on OSX. Message I get when I type "bin/hubot":

bin/hubot botname> [Sun May 22 2016 00:24:06 GMT-0400 (EDT)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.

Your hubot-scripts.json is empty, so you just need to remove it. [Sun May 22 2016 00:24:06 GMT-0400 (EDT)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2) [Sun May 22 2016 00:24:06 GMT-0400 (EDT)] INFO hubot-redis-brain: Using default redis on localhost:6379

**Comment by bharadwajh** [comment]
Message when I type "hubot help":

Hubot> [Sun May 22 2016 01:09:19 GMT-0400 (EDT)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.

The following scripts have known replacements. Follow the link for installation instructions, then remove it from hubot-scripts.json:

The following scripts don't have (known) replacements. You can try searching https://www.npmjs.com/ or http://github.com/search or your favorite search engine. You can copy the script into your local scripts directory, or consider creating a new package to maintain yourself. If you find a replacement or create a package yourself, please post on https://github.com/github/hubot-scripts/issues/1641:
* hubot-shipit

You an also try updating hubot-scripts to get the latest list of replacements: npm install --save hubot-scripts@latest
[Sun May 22 2016 01:09:19 GMT-0400 (EDT)] ERROR Error loading scripts from npm package - Error: Cannot find module 'hubot-diagnostics'
  at Function.Module._resolveFilename (module.js:440:15)
  at Function.Module._load (module.js:388:25)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Robot.loadExternalScripts (/usr/local/lib/node_modules/hubot/src/robot.coffee:401:11)
  at /usr/local/lib/node_modules/hubot/bin/hubot:160:26
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)

**Comment by bkeepers** [comment]
@bharadwajh sorry for the lack of response here. Hubot was unmaintained for a while, but we're back now. I assume you've moved on from this, but let me know if you're still having issues and want help working through it.
