### ISSUE TITLE
Loop and Sleep within the robot function

### ISSUE THREAD

**Issue by Buzzele** [github/hubot#1193]
Hi,

I have tried, to sending a message to rocketchat in a loop 10 times. This works. But if I want to pause the function between the messages, it does not work, because the messages are all sent together until the end of the robot function. How can I get a break in?

My target is, to send a sqlquery all 30 seconds. So I want to practice this case with simple messages, but even that does not work

Best Regards

**Comment by RichardFoxworthy** [comment]
Any idea in this? We interested to send longer messages as a sequence of smaller messages, with a pause between each message

**Comment by technicalpickles** [comment]
Is there any code examples you can share to demonstrate what you are trying to do? The more you can share the more I can understand to better offer feedback and ideas.

Hubot runs on node, so you can use the builtin functions like [`setTimeout`](http://www.w3schools.com/jsref/met_win_settimeout.asp) for doing something after a delay and [`setInterval`](http://www.w3schools.com/jsref/met_win_setinterval.asp) to do something on an interval.

**Comment by bkeepers** [comment]
> Is there any code examples you can share to demonstrate what you are trying to do?

Closing as stale, but @Buzzele let us now if you have any examples.
