### ISSUE TITLE
Run function after delay

### ISSUE THREAD

**Issue by ngzaharias** [github/hubot#1194]
Apologies for posting here, I haven't found any resources that cover this issue (and it may come from a lack of knowledge of Node.js as to whether it is possible).

I have a script working for hubot that gathers all important information for what a build parameters are and then sends a http.get locally to Jenkins to kick off a build.

What I'm hoping to add in is a delay between when hubot hears the request and when the Jenkins build is kicked off so that users can cancel the build or change parameters.

Any help or pointers would be greatly appreciated!

**Comment by ngenerio** [comment]
This is just a suggestion. You can use something like a scheduler that can be started and cancelled which runs a specific function specified by time like *cron jobs*.

**Comment by ngzaharias** [comment]
just dropping back in to say cron jobs worked great for what I needed. thanks!

**Comment by ngenerio** [comment]
Glad I could help.
