### ISSUE TITLE
robot.brain.save() does not make the data persistent.

### ISSUE THREAD

**Issue by punit1108** [github/hubot#1195]
Although i am saving the data to the brain it is not persistent.

```
var brain = robot.brain.userForName(handle);
if(brain['keys'] === undefined) {
  brain['keys'] = [];
}
brain.keys.push(publicKeyObj);
robot.brain.save();
```

**Comment by ngenerio** [comment]
Data saved to the brain is not persistent. If you want to the brain data to be persisted, you can use [hubot-redis-brain](https://github.com/hubot-scripts/hubot-redis-brain)

**Comment by bkeepers** [comment]
Looks like @ngenerio answered your question, but let us know if you have any others.
