### ISSUE TITLE
Was middleware intended to work on the HTTP path?

### ISSUE THREAD

**Issue by ngawor** [github/hubot#1198]
Listeners don't work on the HTTP path.  Is this a bug or explicitly left out functionality?  We'd like to use listeners to implement security for our bot, but we receive commands both via HTTP and slack.

**Comment by technicalpickles** [comment]
That's correct. Hubot by default really have a way to receive commands by HTTP and by the adapter in the same way. A number of scripts do create HTTP endpoints to post messages into chat rooms, and have similar functionality for listeners to do the same thing. In those cases, you can factor out the functionality you are trying to do from both, and call both from the http endpoint and the listener.

If you could share an example of what you are trying to do, or more specifically how you are trying to secure the bot via both HTTP and Slack, may be able to offer some more concrete suggestions.
