### ISSUE TITLE
Optionally require pmx for http analysis through pm2

### ISSUE THREAD

**Issue by aliasfalse** [github/hubot#1199]
If user specifies an environment, like `HUBOT_USE_PMX`, then require pmx to allow for accurate HTTP analysis

**Comment by technicalpickles** [comment]
You are talking about https://www.npmjs.com/package/pmx , correct? I'm can't say I'm familiar at all with it, so I can't say how it'd integrate with hubot.

If you or anyone else is interested in looking into this, I'd encourage y'all to participate in (the new) [Hubot Evolution](https://github.com/hubotio/evolution) for adding new features to hubot.
