### ISSUE TITLE
Can Hubot run in AWS Lambda?

### ISSUE THREAD

**Issue by EugeneLiang** [github/hubot#1204]
Hi there!

Awesome job with Hubot, was playing around and it feels really cool.

Here's a newbie question: may I know how I can run a Hubot in AWS Lambda?
Do I package the hubot-script as per the instructions from AWS Lambda ( http://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html ) ?

Thanks!

**Comment by wilrnh** [comment]
Thought of the same thing, and just came across:

http://stackoverflow.com/questions/37872640/deploy-hubot-on-aws-lambda

**Comment by davidlinse** [comment]
No reaction for a descent amount of time.. Any news on this ?

**Comment by technicalpickles** [comment]
Not as it exists now, unfortunately.

One difficulty in doing this is similar to what is described in https://github.com/github/hubot/issues/613 . Basically, hubot would need to be able to start up, process one message, and then exit. Currently, hubot doesn't have anyway to signal the completion of a message being processed. There is some talk of adopting Promises in hubot (https://github.com/github/hubot/issues/1338), and if that was widely applied to the code base, could be one way.

The other part of it I think is that there'd need to be an adapter for lambda, that is, receiving a message from it. You'd also probably need some sort of proxy that is connected to a real chat thing, that then sends messages for the lambafied hubot to then process, and then have a way to send messages back to chat.

If anyone is interested in implementing this, I'd suggest checking out the new [Hubot Evolution](https://github.com/hubotio/evolution/) we are using to propose, discuss, and accept new features into hubot ✨
