### ISSUE TITLE
A newbie guide on how to make hubot hang out in IRC?

### ISSUE THREAD

**Issue by antdude** [github/hubot#1205]
Hello.

If I am reading correctly, Hubot can hang out in IRC servers like old Rbots, Markovsky, Howie, etc. https://hubot.github.com/docs/ and https://hubot.github.com/docs/deploying/unix/ (using 64-bit Debian stable/Jessie) doesn't seem to mention anything about connecting to IRC. Did I miss it?

Thank you in advance. :)

**Comment by mose** [comment]
For that you may want to look at https://github.com/nandub/hubot-irc there are a lot of adapters on https://hubot.github.com/docs/adapters/

**Comment by antdude** [comment]
Thanks Mose. I posted in https://github.com/nandub/hubot-irc/issues/164 since I cannot seem to set it up so far.

**Comment by bkeepers** [comment]
Looks like @mose got you pointed in the right direction.
