### ISSUE TITLE
Incorrect scripts link in docs/scripting.md

### ISSUE THREAD

**Issue by SummerSun** [github/hubot#1207]
In the first para, the second sentence: There are [hundreds of scripts written and maintained by the community](https://hubot.github.com/docs/#scripts/) and it's easy to write your own. 

The link: https://hubot.github.com/docs/#scripts/ is incorrect. Be redirected back to the getting started.

**Comment by ouadie-lahdioui** [comment]
I worked at a PR to fixe this one ;)

**Comment by bkeepers** [comment]
This has been fixed. Thanks
