### ISSUE TITLE
Reread the environment variables without restarting Hubot

### ISSUE THREAD

**Issue by khanly** [github/hubot#1213]
Hello:

I set environment variables in (hubot) adapter.  How do I get hubot to reload/reread the environment variables without restarting hubot?

Thanks.

**Comment by strugee** [comment]
Not sure what you mean by this:

> I set environment variables in (hubot) adapter.

It depends on exactly how you set your environment variables, but generally speaking something sets them when Hubot starts up and even if you change the thing that initializes them, that thing has already run so Hubot's environment isn't changed. (Or in other words: even if Hubot and _all plugins_ took care to pick up changes in the environment, the environment of the live, running Hubot wouldn't change even if you changed the configuration.)

**Comment by mose** [comment]
Actually it all depends the code. If the env vars are read to initialise an object, then changing vars won't help. But the code can read process.env rather, each time it's needed, in such case, changing env works.

I use this to change the loglevel in some custom plugin:

```
  robot.respond /setenv ([_A-Z]+) (.*)$/, (msg) ->
    if robot.auth?.isAdmin(msg.envelope.user)
      key = msg.match[1]
      value = msg.match[2]
      process.env[key] = value
      msg.send "Ok. #{key}=\"#{value}\""
    else
      msg.send "Unauthorized."
```

**Comment by strugee** [comment]
@mose no, environment configuration comes from whatever starts Hubot. As I said in my comment above:

> It depends on exactly how you set your environment variables, but generally speaking something sets them when Hubot starts up and even if you change the thing that initializes them, that thing has already run so Hubot's environment isn't changed.

You _are_ totally correct about process.env usage, however. But OP was asking for a way too reread ALL configuration without restarting, which your example doesn't really have anything to do with.

**Comment by technicalpickles** [comment]
> How do I get hubot to reload/reread the environment variables without restarting hubot?

As hubot works currently, you can't.

There'd definitely be some complications to supporting it. Scripts would need to be able to be reloaded. I thought there was an issue for this, but I'm not able to find it off hand. The biggest problem is that scripts can have side effects, so it's less that scripts would be reloaded as they would be run again.

Probably not a satisfying answer, but what are you trying to achieve or workaround by not restarting hubot for change config? Happy to try to offer alternatives or suggestions.

**Comment by bkeepers** [comment]
> As hubot works currently, you can't.

Sounds like this is the answer for now, so closing this. If anyone has a proposal for how to do this, feel free to open an issue that lays it out.
