### ISSUE TITLE
Add link to adapter for Symphony

### ISSUE THREAD

**Issue by jonfreedman** [github/hubot#1216]
The symphony software foundation are working on a hubot adapter for the Symphony chat system @ https://github.com/symphonyoss/hubot-symphony

It would be great to get this listed on the docs

**Comment by jonfreedman** [comment]
FYI the adapter is fully functional - we're using it live

**Comment by bkeepers** [comment]
Add `hubot-adapter` topic

The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320
