### ISSUE TITLE
Turn off 1 on 1 conversations

### ISSUE THREAD

**Issue by chutes** [github/hubot#1217]
I want the ability to turn off 1 on 1 conversations, forcing interactions with the bot through rooms only

**Comment by pchaigno** [comment]
@chutes You could probably achieve that with [a middleware](https://github.com/github/hubot/blob/master/docs/scripting.md#receive-middleware) by ignoring any command from a direct message. As far as I know, how to detect direct messages depends on your adapter however.

**Comment by chutes** [comment]
@pchaigno oh ok.  I'm using middleware already.  I'll look into how to detect direct messages. thanks.

**Comment by bhuga** [comment]
@chutes I agree with @pchaigno that this is probably not a 'core feature', but I would be very :+1: to adding an example to `docs/patterns.md` if you write up some middleware for this. I've wanted to be able to identify DMs and treat them differently too.

**Comment by pchaigno** [comment]
FYI, this is how I detect DMs with the `irc` adapter:
```coffee
is_direct_message = typeof res.envelope.room is "undefined"
```

**Comment by bhuga** [comment]
Neat. What adapter is that for?

**Comment by chutes** [comment]
@pchaigno I'm using hip chat.

robot.receiveMiddleware (context, next, done) ->

I'm also looking into figuring out how to tell where the message is coming from

**Comment by pchaigno** [comment]
> What adapter is that for?

@bhuga [hubot-irc](https://github.com/nandub/hubot-irc)

**Comment by chutes** [comment]
I'm unsure of how to get the room off of the context.
To get the user name from a message I can:
`context.response.message.user.name`

**Comment by bkeepers** [comment]
@chutes looks like @pchaigno and @bhuga made some suggestions that will work, but let us know if you have any other questions.
