### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by CorruptComputer** [github/hubot#1226]
It would be great if hubot could work with discord!

**Comment by DJgamer98** [comment]
There's an adapter for that! :smile: 

https://github.com/thetimpanist/hubot-discord

**Comment by 3rd-Eden** [comment]
This should be added to the documentation page.

**Comment by bkeepers** [comment]
Add `hubot-adapter` topic

The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320
