### ISSUE TITLE
#803 breaks tests that assume `receive` is sync

### ISSUE THREAD

**Issue by sheluchin** [github/hubot#1230]
While client code remains backwards compatible with the introduction of #803, test code that assumes `receive` is sync breaks as of that PR. The fix is to make those tests async. In short, the way to do this is to move all of your assertions into a callback as can be seen [here](https://github.com/github/hubot/blob/c97071161206b8f8e236a348a6cb85164bd01da2/test/robot_test.coffee#L180).

One such example of tests being impacted can be found here: https://github.com/appneta/hubot-fabric/issues/5

**Comment by mose** [comment]
hmm, `hubot-fabric` tests are all passing with current version of hubot `2.19.0`. I'm closing this issue, but thanks for the heads up on this, maybe it will help other plugin maintainers.
