### ISSUE TITLE
Redis Brain causing FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory?

### ISSUE THREAD

**Issue by mchristensen76** [github/hubot#1234]
Would a large amount of users in Slack cause a process out of memory error in hubot?  We have about 9400~ slack users on our team.  Whenever the process fails I always see redis-brain.coffee in the trace.

Any ideas on how to fix?  What's the best way to add more process memory to hubot?

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

<--- Last few GCs --->

  616036 ms: Mark-sweep 1358.2 (1450.2) -> 1359.6 (1450.2) MB, 95.8 / 0 ms [allocation failure] [scavenge might not succeed].
  616137 ms: Mark-sweep 1359.6 (1450.2) -> 1358.2 (1450.2) MB, 101.3 / 0 ms [allocation failure] [scavenge might not succeed].
  616233 ms: Mark-sweep 1358.2 (1450.2) -> 1359.6 (1450.2) MB, 96.2 / 0 ms [last resort gc].
  616337 ms: Mark-sweep 1359.6 (1450.2) -> 1358.2 (1450.2) MB, 103.8 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x278b74be3ac1 <JS Object>
    1: stringify [native json.js:160] [pc=0xbd8a4489f24](this=0x278b74bdbf71 <a JSON with map 0x43ee200a8d1>,u=0xfffd006b8f1 <an Object with map 0x3f014ca51fc9>,v=0x278b74b04189 <undefined>,I=0x278b74b04189 <undefined)
    2: arguments adaptor frame: 1->3
    3: /\* anonymous */ [/home/mikedc/gobot/node_modules/hubot-redis-brain/src/redis-brain.coffee:63] [pc=0xbd8a74ad9c2] (this=0xfffd00663b9...

**Comment by eornst** [comment]
I have the very same error (with line 63 in redis-brain.coffee showing up on the trace) for a legacy hubot that I just started to maintain and hasn't been further updated since 2016. The amount of users in my workspace is around 4k. Have anyone found any workaround for this?
