### ISSUE TITLE
Azure deployment instructions

### ISSUE THREAD

**Issue by kevinkuszyk** [github/hubot#1243]
I noticed there is an [azure.md](https://github.com/github/hubot/blob/master/docs/deploying/azure.md), but it's not included in the site menu.  Also the Azure instructions are a little out of date as the `azure` command now defaults to ARM mode instead of ASM.  So...

1. Will you accept a PR to add Azure to the deployment menu.  If so can you point me at the file to change?
2. Will you accept a PR to update the Azure deployment instructions?

Thanks!

**Comment by technicalpickles** [comment]
> Will you accept a PR to add Azure to the deployment menu. If so can you point me at the file to change?

It's currently in a private repo for the hubot.github.com website for some historic vagaries, and should be migrated to this repo. In the interim, I've updated the site.

> Will you accept a PR to update the Azure deployment instructions?


Yes 😁

**Comment by kevinkuszyk** [comment]
Thanks for fixing the menu.  When I get a moment I'll get those instructions updated.
