### ISSUE TITLE
Studying the evolution of hubot' project

### ISSUE THREAD

**Issue by gustavopinto** [github/hubot#1244]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. hubot was in my list. 

To further analyze the impacts of hubot's migration, we analyzed the git log commit history of your project in terms of _number of contributions_, _number of newcomers_, and _number of contributors per month_. The following figure presents a temporal perspective regarding these three measures. 

![hubot-com-con](https://cloud.githubusercontent.com/assets/235062/19274153/985b856e-8fa5-11e6-83d2-c74e459752a1.jpg)

Given the numbers presented in the graphic, we would like to ask hubot developers the following questions:
1. What motivated the project to open its source code at Github? How do you evaluate the benefits of this migration?
2. Does this snapshot make sense? Did you find any inconsistency on the data?
3. Do you have any internal policy to promote/attract/retain newcomers? If so, do them succeed?
4. Why did the number of active contributors and contributions decrease after the project became open-source?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by gustavopinto** [comment]
hi @technicalpickles and @tombell, 

do you have any comments on this issue?

Thanks

Gustavo

**Comment by technicalpickles** [comment]
@gustavopinto yes, but I've been dealing with aftermath of Hurricane Matthew, and I'm only working part-time right now as part of my paternity leave. I will write something when I am able.

**Comment by bkeepers** [comment]
Hey @gustavopinto, thanks for the question. I'm guessing we missed the opportunity to reply here, but let me know if it's not too late.

**Comment by gustavopinto** [comment]
Hi @bkeepers. Actually, this time is somewhat perfect. I just get back to this project.

**Comment by gustavopinto** [comment]
Hi @bkeepers, @technicalpickles, if you don't mind, we have additional questions about the motivations for going open-source. 

For example, was the main motivation of the companies to attract and retain new contributors?  Or was the main motivation perhaps to promote a profile of open-source-friendliness and get goodwill from the community? 

Could you please elaborate a bit over it?

Additionally, were there instances that companies recruited people from the community after they contributed to the (now open-sourced) project? 

Were there discussions between the companies and the community that indicate a communication between them? 

Finally, what are the recommendations for policies to create a sustainable community?
