### ISSUE TITLE
query: how to call a function written in 1 file from other file

### ISSUE THREAD

**Issue by p00j4** [github/hubot#1245]
I understand its coffeescript specific however somehow I didn't find straight syntax answer anywhere so kindly please bare with me as i'm newbie in cofferescript
I have 2 hubot coffescript files, in bot I want to use 1 common function so I want to generalize code by having all reusable functions in 3rd file. 
so how do I import my_reusable_function from ReusableFile.coffee into both other coffescripts?

```
file1.coffee

robot.respond /blah/i, (msg) ->
  words = res.match[1]
  res.reply my_reusable_function(words,res)



file1.coffee
robot.respond /blah/i, (msg) ->
  words = res.match[1]
  value = my_reusable_function(words,res) 
  if value > 2
    # do blah blah
 else 
   # do nothing


ReusableFile.coffee
my_reusable_function = (words,msg) ->
  # do common tasks here and calculate value
  return value
```

**Comment by technicalpickles** [comment]
In `ReusableFile.coffee`, you have to export the functions, and then you have to require them in `file1.coffee`. https://www.sitepoint.com/understanding-module-exports-exports-node-js/ talks a bit about it, but this is a general nodejs thing and not specific to hubot. That should give you a specific example to follow for exporting a function and then using it in another file.

**Comment by p00j4** [comment]
thanks @technicalpickles for the right links, will understand and use. 
and **big thanks** 👍  for actively committing such an amazing library. i'm experimenting many things on top of it to robot most of the repetitive asks.

**Comment by bkeepers** [comment]
Looks like @technicalpickles answered your question, but let us know if you have any others.
