### ISSUE TITLE
Sending a private message / DM to a user

### ISSUE THREAD

**Issue by kevinkuszyk** [github/hubot#1246]
Is there any guidance / best practice on how to send a private message to a user?  There doesn't seem to be method on `robot` designed for this.

It looks like the chat adapters have added their own methods to do this.  For example Rocket.Chat have a `sendDirect()` method (see RocketChat/hubot-rocketchat#176).

**Comment by technicalpickles** [comment]
On Slack at least, you can do:

```coffeescript
robot.messageRoom "username", "some message here"
```

**Comment by kevinkuszyk** [comment]
Thanks @technicalpickles.  Is the intent that this should also send a private message:

```coffeescript
robot.send user, message
```

**Comment by technicalpickles** [comment]
@kevinkuszyk I don't know about intents, but that wouldn't work. If you look at `robot.messageRoom`, it's using the same code as `robot.send`, but it's building a message to a specific room: https://github.com/github/hubot/blob/master/src/robot.coffee#L534-L562

**Comment by mose** [comment]
This issue seems to be answered. I'm closing it. Feel free to come back with a new ticket if there is need for more info.
