### ISSUE TITLE
coffee-script version is too low

### ISSUE THREAD

**Issue by richardyanhao** [github/hubot#1248]
origin:
```
"coffee-script": "1.6.3"
```
why not
```
"coffee-script": "^1.6.3"
```
cause 1.6.3 is too low to fullfill requirement
When we want use co and promise to avoid pyramid of doom, we find that yield is reserved by hubot. However, 'yield' is not reserved by coffeescript now.

**Comment by technicalpickles** [comment]
You can `npm install --save coffee-script` to use a newer version of coffeescript with your particular hubot.

cc https://github.com/github/hubot/issues/1112

**Comment by richardyanhao** [comment]
@technicalpickles  thanks a log
