### ISSUE TITLE
hubot not responding to redis

### ISSUE THREAD

**Issue by jy2008** [github/hubot#1249]
my hubot rocket.chat adapter works well except for every time i started hubot, I had to reset the following items:
```
export ROCKETCHAT_USER=bot
export ROCKETCHAT_PASSWORD=bot
export ROCKETCHAT_AUTH=password
export HUBOT_YOUTUBE_API_KEY=<your token>
```
I get the feel hubot is not really responding to redis that i installed. I do have `hubot-redis-brain` installed as well. Is there any other setting I need to do in order to make it work? Or should i just re-install the whole thing? what might be the possible reason?

**Comment by technicalpickles** [comment]
Closing for https://github.com/hubot-scripts/hubot-redis-brain/issues/22
