### ISSUE TITLE
Refreshing robot.brain.data.users

### ISSUE THREAD

**Issue by zackrowe** [github/hubot#1250]
Is there away to refresh the list. I'm using Hubot with Slack and robot.brain.data.users contains some users that have been removed from Slack.

I searched both Google and the issues list and I couldn't find anything relevant sorry if this is a repeat.

Thanks!

**Comment by technicalpickles** [comment]
Not currently.

It's also worth noting that Slack doesn't ever remove users, just marks them as inactive.

**Comment by bkeepers** [comment]
@zachrowe looks like @technicalpickles answered your question, but let us know if you want to talk more about it.
