### ISSUE TITLE
NPM modules loaded after Hubot Scripts?

### ISSUE THREAD

**Issue by thebeline** [github/hubot#1251]
I imagine this is expected behavior, but I am remiss on how to work with it.  I have an NPM package for Hubot that adds a function to the `robot` object that is/would be required by a Hubot Script, however, the NPM modules are loaded after Hubot Scripts, so the function is not available when the Hubot Script exports.

module.js

```
module.exports = function(robot){
    robot.a_function = function(msg) {
        console.log(msg)
   }
}
```

hubot-script.coffee

```
module.exports = (robot) ->
    #function not available
   robot.a_function 'test'
```

Fairly new to Node.js, I will admit that, but how should I work with this (beyond just making it a Hubot Script).  :-/

**Comment by technicalpickles** [comment]
Could you link to the module in question if it's open source? That would help me understand how you are packaging and trying to load it into hubot.

That said, there's not really a _clean_ way to extend hubot's `robot` with a normal npm package. You can make a [script package with a hubot script](https://hubot.github.com/docs/scripting/#creating-a-script-package), and manipulate the `robot` object. You'd just need to ensure it's loaded first.

**Comment by bkeepers** [comment]
@thebeline closing as stale, but let us know if you can link to the project or can share an example.
