### ISSUE TITLE
http calls from es2015 script doesn't work

### ISSUE THREAD

**Issue by muskacirca** [github/hubot#1253]
Hello,

I'm new to Hubot and I'm trying to writre scripts in es2015. I got it working well with basic example, but I got stuck trying to make http calls.

here's my code :

```
export default (robot) => {
    robot.hear(/swapi/i, (res) => {
        robot.http("http://swapi.co/api/people/1/")
            .header("Accept", "application/json")
            .get((err, res, body) => {
                console.log("body : " + JSON.stringify(body));
            })
        res.send(`youhou`)
    })
}
```

I always got undefined in the console.log

However it works perfectly in cofeescript :

```
module.exports = (robot) ->
  robot.hear /badger/i, (res) ->
    robot.http("http://swapi.co/api/people/1/")
    .header("Accept", "application/json")
    .get() (err, res, body) ->
      console.log(JSON.stringify(body))
```

Am I doing something wrong ?

Thank you for your answers
Vincent

**Comment by ngenerio** [comment]
@muskacirca I think what you want to do is this.

```javascript
export default (robot) => {
    robot.hear(/swapi/i, (res) => {
        robot.http("http://swapi.co/api/people/1/")
            .header("Accept", "application/json")
            .get()((err, res, body) => {
                console.log("body : " + JSON.stringify(body));
            }))
    })
}
```

**Comment by muskacirca** [comment]
@ngenerio ok tahnk you a lot it works !
But I'm a bit confused, is it standard javascript or specific to hubot ? 

I was trying to use axios to make http calls :

````
axios.post(TEAMCITY_URL + "/httpAuth/app/rest/buildQueue", data, {headers: header})
            .then((response) => {
                console.log(JSON.stringify(response));
            })
````

but it doesn't work

**Comment by ngenerio** [comment]
I am probably not getting your question very well but hope this helps:

Hubot uses [scope-http-client](https://github.com/technoweenie/node-scoped-http-client) for its  requests.  The `get` method returns a function that you can pass your callback.  

I don't see anything wrong with your code but the data from the response can be found by : `response.data`.

**Comment by mose** [comment]
It seems this question got answered, but feel free to re-open it if you feel the need to get more help about it.
