### ISSUE TITLE
Hubot for Splunk

### ISSUE THREAD

**Issue by arindamdc** [github/hubot#1254]
Hi,

I am trying to integrate Hubot with Splunk SDK. to fire off splunk searches. I have seen the integration with Splunk Mint.
How easy it would be to call the Splunk Service from the coffee script?
Will keep you all posted.

Thanks,
Arindam

**Comment by technicalpickles** [comment]
Which SDK specifically are you talking about?

> I have seen the integration with Splunk Mint.

For reference, I'm guessing you mean https://github.com/barbosa/hubot-splunk-mint

> How easy it would be to call the Splunk Service from the coffee script?

Is Splunk Service a proper noun? I don't know anything of this, so can't really offer much advice one way or the other. I will say that you can write scripts as javascript also. If it's an HTTP service, its' easy enough to make HTTP requests with coffeescript: https://hubot.github.com/docs/scripting/#making-http-calls

You could also look how that hubot-splunk-mint is implemented.

**Comment by bkeepers** [comment]
@arindamdc closing as stale, let us now if you got it working or have any other questions.
