### ISSUE TITLE
Update Campfire adapter to support Basecamp3 Chatbot API

### ISSUE THREAD

**Issue by miklb** [github/hubot#1259]
Campfire is now integrated into Basecamp3 and has a new [API](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#chatbots)

Wondering if there is any plans for the core Campfire adapter to support this or if anyone has built a new adapter for it. Currently the bots are only call/response, no option to listen in the channel. I've pretty much figured out how to receive the POST response, but not clear on how to respond with a reply to that. Seems like basically that's what is required.

**Comment by miklb** [comment]
Seems the discussion in #925 is relevant, specifically [this comment](https://github.com/github/hubot/issues/925#issuecomment-114112981).

**Comment by miklb** [comment]
fwiw, there is now a basic [Basecamp 3 adaptor](https://github.com/williammck/hubot-basecamp-3)

Some of the features on the roadmap I believe would enhance, especially rich messages.

**Comment by mose** [comment]
Superb!
