### ISSUE TITLE
robot.hear not working for scripts written in js

### ISSUE THREAD

**Issue by imayobrown** [github/hubot#1261]
Hi All,

When writing scripts in javascript instead of coffeescript the robot.hear() method does not match the regex pattern given.

```javascript
robot.hear('/test/i', function(res) {
        res.send('This is a test.');
});
```

```coffeescript
robot.hear /test/i, (res) ->
  res.send 'This is a test.'
```

Both the above should have the same effect but only the coffee is being correctly matched. I think this is due to the coffee passing a RegExp object for /test/i and the javascript is not. I have a pr to fix the issue but I was hoping someone could confirm they experience this behavior as well.

**Comment by puresmash** [comment]
Try modifying your javascript code like below?
```js
robot.hear(/test/i, function(res) {
        res.send('This is a test.');
});
```

**Comment by imayobrown** [comment]
@puresmash Thanks! That worked perfectly. Appreciate the help.
