### ISSUE TITLE
subfolders in scripts directory?

### ISSUE THREAD

**Issue by TraGicCode** [github/hubot#1269]
Is it possible to organize custom scripts in the scripts directory into sub folders and have the automatically loaded by hubot?

EXAMPLE

scripts/github/...
scripts/teamcity/...

**Comment by mose** [comment]
Currently that's not possible, the script loader will read only `./scripts` and `./src/scripts` and expect to find files in there. 

But it feels it would not be too hard to modify the loader to load dirs and traverse them as well. It's there 
- https://github.com/github/hubot/blob/master/bin/hubot#L92
- https://github.com/github/hubot/blob/master/src/robot.coffee#L375

**Comment by brandonmp** [comment]
I just keep my code in neatly organized folders in `src`, then in `scripts` I have individual `.js` files, each w/ a simple:

`module.exports = require('../src/script-folder/index.js')`

so far so good

**Comment by bkeepers** [comment]
@TraGicCode looks like there are a few options here. Let us know if none of those work for youl.

**Comment by Polkien** [comment]
@brandonmp that works but now you need to have a file in the root of `scripts` folder for every script in the `src` folder jeje, is there a way for exporting all of them in a single file from `scripts` ?
