### ISSUE TITLE
Errno 111 connection refused 

### ISSUE THREAD

**Issue by willqad** [github/hubot#1270]
am receiving an error when using hubot. I checked port 8181. Hubot is not listening on that port. any ideas?

I am using hubot with stackstorm

requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8181): Max retries exceeded with url: /hubot/st2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0d4477e7d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by mose** [comment]
By default Hubot listens on port 8080, but if you want to change that, you can set the env var `EXPRESS_PORT` or `PORT` to your desired value.

**Comment by bkeepers** [comment]
@willqad let us know if @mose's suggestion didn't fix your issue.
