### ISSUE TITLE
How to run hubot as a daemon with docker?

### ISSUE THREAD

**Issue by hbrls** [github/hubot#1271]
I'm trying to run a hubot without any adapter (I think it will fallback to the default shell adapter).

If `docker run -it`, it works well.

If `docker run -d`, it seems to exit immediately.

What is the recommended way to run hubot as a daemon.

**Comment by mose** [comment]
Maybe that working example can help you? https://github.com/Dynamictivity/hewbot-docker

**Comment by pchaigno** [comment]
Another (different) example that works for me: https://github.com/pchaigno/hewbot/blob/657614144bc2898d39a45ec49c15b7765244871e/Dockerfile

**Comment by hbrls** [comment]
Thanks for your help. I'm using supervisord and not changing anything about hubot now. It works.
