### ISSUE TITLE
Http listener

### ISSUE THREAD

**Issue by krishna1990fis** [github/hubot#1277]
Hi, i am able to write a basic script for hubot for listening http request

`url = require('url')
querystring = require('querystring')
module.exports = (robot) ->
  robot.router.get "/flybot/message", (req, res) ->
    query = querystring.parse(url.parse(req.url).query)	
    user = {}
    user.room = query.room if query.room
    try
       robot.send user, "INCOMING MESSAGE: " + query.message       
       res.end "message sent: Rahul"
    catch error
      console.log "message-listner error: #{error}."`

and from the browser i am calling this way - > http://localhost:8080/flybot/message/
and it replies with message sent : Rahul

Problem: 
Please answer the following questions
1. how to read a query string from the url and reply according to the query string
2. i want to call the hubot from webpage and hubot should reply back using http listener functionality
3.  i want to have all the question and answer stuff in just one coffee script, right now i am not able to put more than one get request in single coffee script **robot.router.get "/flybot/message", (req, res) ->** for that i have to create another coffee script, this way it will become clumsy
4. give me some link which contains the proper usage of hubot http listener 
5. can we integrate hubot with yammer ?
6. now in single coffee script file, we can have multiple of below 
`robot.hear /How do I submit a question if I do not see it in the FAQs/i, (res) ->
		res.send "Use the Contact Us option on the lower left-hand side of the site in the Information Panel."` 
i am planning to have a hubot script, which will answer the questions based on different questions asked from webpage via http listener, here my questions are going to be part of the url as query parameters and these query parameters are going to be processed on hubot side and matching answer will be sent back.

Thank you so much
Krishna P

**Comment by mose** [comment]
That's a lot of questions :)

There is a Yammer adapter at https://github.com/athieriot/hubot-yammer

For the usage of the http listener, you can check https://github.com/Gandi/hubot-es-logger/blob/master/scripts/eslogger_web.coffee for inspiration maybe?

**Comment by mose** [comment]
I'm closing this issue, but if you still have more questions, can you create one issue per question? it makes it easier to process :)
