### ISSUE TITLE
Scaling hubot

### ISSUE THREAD

**Issue by GGYaX** [github/hubot#1282]
Can hubot be scalable? I mean to have multiple workers.

**Comment by jdelmerico** [comment]
That and can you support multiple adapters in the same Hubot server instance?  I'd like to support Slack and Hipchat with one Hubot instance, then create a farm of servers for scalability/ redundancy. 

Anyone attempted to do this?

**Comment by GGYaX** [comment]
@jdelmerico I tried to launch two instance for slack and hipchat. Didn't find a way to do it with a single instance.

**Comment by jdelmerico** [comment]
@GGYaX thanks very much for the info.

For any of the devs working on this project is the ability to support multiple adapters in one Hubot instance on the roadmap or are the reasons you don't want to do this?  1 adapter per Hubot deployment seems to reduce the usefulness of a framework like this.

**Comment by GGYaX** [comment]
I would also like to know if there is any roadmap.

**Comment by mose** [comment]
Last week we rebooted hubot with a fresh roadmap and now we are going to see much more activity down there. see https://github.com/github/hubot/blob/master/ROADMAP.md

It includes:

    Support for running multiple adapters and archetypes

**Comment by Rima** [comment]
I have managed to get it to work with multiple adapters, and multiple clients. by extending it. I'm just a little worried about its performance under high volumes, did anyone stress test hubot? ie how far can it scale? 1000 clients? 1m clients?

**Comment by timkinnane** [comment]
@Rima Can you share how you did that? I don't care how patchy it is, if you can make it public or invite me to a repo I'm happy to work through any quirks. Really interested to see your approach.

**Comment by joeyguerra** [comment]
I took a stab at scaling hubot. Built a Hubot script that adds messages to a Redis stream (INBOX) where consumer groups can pick them up and send back through a Redis stream (OUTBOX). [hubot-redis-inbox](https://github.com/hubot-friends/hubot-redis-inbox)
