### ISSUE TITLE
Trying to create an adapter @robot.receive never invokes reply or send

### ISSUE THREAD

**Issue by maxpert** [github/hubot#1291]
Hey guys, so I followed the tutorial given (here)[https://hubot.github.com/docs/adapters/development] I am finally able to invoke hubot with my adapter but now I am running into problem where even the sample adapter doesn't work, here is my code:

```coffeescript
{Robot,Adapter,TextMessage,User} = require 'hubot'

class Sample extends Adapter

  constructor: ->
    super
    @robot.logger.info "Constructor"

  send: (envelope, strings...) ->
    @robot.logger.info "Send"

  reply: (envelope, strings...) ->
    @robot.logger.info "Reply"

  run: ->
    @robot.logger.info "Run"
    @emit "connected"
    user = @robot.brain.userForId 1001, name: 'Sample User'
    message = new TextMessage user, 'Some Sample Message', 'MSG-001'
    @robot.receive message

exports.use = (robot) ->
    new Sample robot
```

When I invoke my bot with commandline `hubot -a sample` I get following console logs:

```
[Fri Feb 03 2017 08:13:58 GMT-0800 (Pacific Standard Time)] INFO Constructor
[Fri Feb 03 2017 08:13:58 GMT-0800 (Pacific Standard Time)] INFO Run
```

The Reply or Send is never invoked. However through some magic if I invoke the shell adapter everything works!!! What am I doing wrong?

**Comment by bettinatop22** [comment]
How do you trigger the send function from your bot script? Have you registered any listeners to your robot (e.g robot.hear /hello/)?

**Comment by maxpert** [comment]
Turns out my package was having it's own subpackage of hubot causing the issue. Fixed it now.
