### ISSUE TITLE
ERROR ReferenceError: body is not defined

### ISSUE THREAD

**Issue by tuyendt6** [github/hubot#1292]
when I try to do the http get to server from hubot , but when i log the body , res , err , all of them always say   
 ERROR ReferenceError: ...... is not defined

please see my code and help me 

module.exports = (robot) ->
  robot.respond /sansan help/i, (msg) ->
    msg.send " 1. searchCard ==> Acquire Business Card Set (Term Specified) \n 2. bizCards ==> Acquire Business Card Set (Conditions Specified \n 3. bizCardsImage ==> Acquire Tag Set assigned to a Business Card \n 4. bizCardTags ==> Acquire Tag Set assigned to a Business Card "

  robot.respond /searchCard/i, (msg) ->
    url = "https://api.sansan.com/v1.1/bizCards/search"
    msg.send "request accepted ...."
    options =rejectUnauthorized: false
    robot.http(url,options)
      .headers('X-Sansan-Api-Key:1234456789')
      .get() (err, res, body)->
    msg.send body
       

thank you !

**Comment by tuyendt6** [comment]
this code also not run 


module.exports = (robot) ->
  robot.respond /sansan help/i, (msg) ->
    msg.send " 1. searchCard ==> Acquire Business Card Set (Term Specified) \n 2. bizCards ==> Acquire Business Card Set (Conditions Specified \n 3. bizCardsImage ==> Acquire Tag Set assigned to a Business Card \n 4. bizCardTags ==> Acquire Tag Set assigned to a Business Card "

  robot.respond /searchCard/i, (msg) ->
    url = "https://api.sansan.com/v1.1/bizCards/search"
    msg.send "request accepted ...."
    robot.http(url)
      .headers('X-Sansan-Api-Key:66b608e9b7ca46bc988b23481fe7420a')
      .get() (err, res, body)->
    msg.send body

**Comment by mose** [comment]
It may come from the fact that the `.header` needs a hash ?

Try this:
```
    robot.http(url. options)
      .headers({ 'X-Sansan-Api-Key': 1234456789 })
      .get() (err, res, body) ->
        msg.send body
```

**Comment by tuyendt6** [comment]
I am crazing with hubot , :(( , same time this code working as well , some time say msg is not defined ,
I am using Netbean , and already enable coffee plugin . any body help me ? thanks in advance .

module.exports = (robot) ->
robot.respond /SearchCard/i, (msg) ->
  url = "https://api.sansan.com/v1.1/bizCards/search"
  msg.http(url)
  .header('X-Sansan-Api-Key','12345678')
  .get() (err, res, body) ->
  msg.send body

**Comment by technicalpickles** [comment]
Coffee script is super sensitive to whitespace, in particular indentation. Would you mind pasting your code in a [highlighted code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/) or a [gist](https://gist.github.com/) to show how you have the code is formatted?

**Comment by tuyendt6** [comment]
thank you for your help , I already try with my self , and as same with your suggestion , and I decided to close this issue , reason is white space .
