### ISSUE TITLE
Hubot not installing

### ISSUE THREAD

**Issue by shubham-srivastava-goku** [github/hubot#1293]
Throwing below error 

npm ERR! Linux 3.10.0-514.6.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "--save"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! path /root/.npm/hubot-help
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/root/.npm/hubot-help'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, mkdir '/root/.npm/hubot-help'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/root/.npm/hubot-help',
npm ERR!   parent: 'meenamma' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/myhubot/npm-debug.log

How can I resolv this issue. Please help, I'm new to it.

-- Thanks in advance

**Comment by youhide** [comment]
u have permissions issue's
try running with "sudo"

**Comment by serembon** [comment]
Or this https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by bkeepers** [comment]
@shubham-srivastava-goku let us know if these don't fix it for you
