### ISSUE TITLE
Scripting Patterns link in docs is giving 404

### ISSUE THREAD

**Issue by itomaldonado** [github/hubot#1294]
Some of the pages in the Hubot docs are linking to the url seen below and it does not exist (404 error).

`https://hubot.github.com/docs/scripting/patterns/`

**Comment by mose** [comment]
You are right indeed, but I found only one such erroneous link. Thanks for reporting!

**Comment by mose** [comment]
Actually the link was working. If you can find precisely where the link is broken, can you report it again? Maybe it has been actually fixed in the while. Thanks anyways :)
