### ISSUE TITLE
New Hubot adapter for BearyChat

### ISSUE THREAD

**Issue by aphawk** [github/hubot#1295]
BearyChat offers  services similar to Slack and Hipchat. 
The adapter is battle tested.
The official github repo is https://github.com/bearyinnovative/hubot-bearychat

**Comment by loddit** [comment]
this adapter works well.

**Comment by bkeepers** [comment]
Add `hubot-adapter` topic

The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320
