### ISSUE TITLE
Error: Cannot find module 'hubot-Campfire'

### ISSUE THREAD

**Issue by shotah** [github/hubot#1296]
Trying to get hubot up and running on windows. I seem to be stuck at the final piece. Also I'm having issues passing any parameters into yo for hubot, it requires me to manually do the selection. Here is what I have so far as a snippet. 

if(!(test-path c:\hubot))
{
    cd 'C:\'
    git clone https://github.com/github/hubot.git
}
if(!(test-path c:\reqbot))
{
    new-item c:\reqbot -ItemType Directory
}
if (!((choco list --localonly nodejs.install) -match "nodejs"))
{
    choco install nodejs.install -y
}
if(!(test-path "C:\npm"))
{
    new-item "c:\npm" -ItemType Directory
    pushd "C:\npm"
    . npm install yo generator-hubot
    popd
}
pushd C:\reqbot
C:\npm\node_modules\.bin\yo --owner="Bot Wrangler myname@domain.com" --name="reqbot" --description="ServiceNow Bot" --adapter=campfire --defaults
popd

**Comment by mose** [comment]
Actually campfire being the default adapter, you could try without the `--adapter=campfire `.

If you still have issues after that, could you open a ticket on https://github.com/github/generator-hubot/issues ? This is where the generator code is maintained.
