### ISSUE TITLE
Whitelist proxy domains

### ISSUE THREAD

**Issue by rhoml** [github/hubot#1301]
Hi there,

I am running hubot behind a proxy as per https://github.com/github/hubot/blob/master/docs/patterns.md#forwarding-all-http-requests-through-a-proxy but i have the following use case:

Hubot connects to Slack and other http services through the proxy, but i'd also like to write plugins to work with our internal APIs. 

Is there a way to whitelist domains? Something like the `nonproxyhost` So i can send the requests to my internal services directly?

**Comment by rqc** [comment]
It should respect the `no_proxy` and `NO_PROXY` values that you setup in your environment.

**Comment by rhoml** [comment]
Gotcha, it also doesn't seem to like the proxy as it never connects to slack

**Comment by mose** [comment]
Looks solved. If there is still issues, please can you open a new one :)
