### ISSUE TITLE
Hubot to respond the user for the query with alias name of http cluster

### ISSUE THREAD

**Issue by Akhilesh-Anb** [github/hubot#1310]
I have integrated Slack - Hubot - Elasticsearch. This for querying elasticsearch from slack.

First we are giving alias name to our cluster in hubot to add into its brain.

Now, i mentioned one query in coffescript as below,

 

```
robot.hear /nodes (.*)/i, (msg) ->
    if msg.message.user.id is robot.name
      return

    catNodes msg, msg.match[1], (text) ->
      msg.send text
```

When user querys something in slack and where any work matches with nodes, should give me the output.

When i query as " provide me the list of nodes iris" , its giving me correct output.

If someone query as "provide me the list of nodes in iris" its giving me

> Do not recognise the cluster alias: in iris

whatever i give after nodes in query is throwing error output.

How can i solve this...

**Comment by davidlinse** [comment]
I think this is no issue with hubot itself but maybe your regular expression or something else.
I'd prefer to ask on a mailing list ir IRC channel.

**Comment by Akhilesh-Anb** [comment]
There is no issue with hubot. But i want to know how to change the code of robot.hear to get my output.

**Comment by mose** [comment]
Maybe you could use something like

    robot.hear /nodes(?: in| for| at| on}? (\w+)/i, (msg) ->

**Comment by bkeepers** [comment]
@Akhilesh-Anb it looks like @mose's suggestion should solve your problem. Let us know if it doesn't.
