### ISSUE TITLE
Hubot DCPP Adapter

### ISSUE THREAD

**Issue by ParthKolekar** [github/hubot#1318]
Hi,

I have made an adapter for the [Direct Connect](https://en.wikipedia.org/wiki/Direct_Connect_(protocol)) protocol. Which we use in campus. 

It is located [here](https://github.com/ParthKolekar/hubot-dc/). If it is agreeable, could it be added to the list of the third party adapters?

**Comment by bkeepers** [comment]
The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320

**Comment by ParthKolekar** [comment]
Seems good.
