### ISSUE TITLE
Setup a Slack team for maintainers and contributors

### ISSUE THREAD

**Issue by bkeepers** [github/hubot#1322]
From the [ROADMAP](https://github.com/github/hubot/pull/1321)

> - [ ] Choose a chat platform for maintainers and contributors, and post notices in various existing places (#hubot on freenode, github/hubot on Gitter). Slack is the obvious choice here.

- [x] create a Hubot slack team
- [x] [Create and configure a hubot instance](https://github.com/hubot-scripts/hubot-for-hubot)
- [x] Setup IRC gateway to connect Slack and #hubot on Freenode.
- [x] Setup [slackin](https://github.com/rauchg/slackin)
- [x] Create default channels
  - [x] #help - for users getting help with the project
  - [x] #contributors - for discussions amongst maintainers & contributors
  - [x] #maintainers - rarely used private channel for confidential discussions
  - [x] #random - for random discussions about bots, technology, and sandwiches
- [x] ~~Wait until Code of Conduct has been added to the project~~
- [x] Add link to join Slack to the README
- [x] Post notice in #hubot on IRC
- [x] Post notice in Gitter

**Comment by bkeepers** [comment]
> - [ ] ~~Wait until Code of Conduct has been added to the project~~

I'm going to go ahead without this right now and we'll apply the code of conduct separately.

**Comment by technicalpickles** [comment]
There's a few items left.

**Comment by bkeepers** [comment]
> - [x] Wait until Code of Conduct has been added to the project

Done in #1334 

> - [x] Post notice in Gitter

Done and set the topic to link to slack
