### ISSUE TITLE
example.js

### ISSUE THREAD

**Issue by nishizuka** [github/hubot#1324]
Many hubot-scripts are written by CoffeeScript ,
Since JavaScript is also supported,
I think that it is better to also make example.js.

**Comment by mose** [comment]
Well, in version 3 hubot will probably use pure modern js. But can you be more specific about which file you are talking about? Can you give an url?

**Comment by technicalpickles** [comment]
@mose I believe it's the `scripts/example.coffee` that is created by the [generator](https://github.com/github/generator-hubot). https://github.com/github/generator-hubot/blob/master/generators/app/templates/scripts/example.coffee the source for that.

**Comment by mose** [comment]
ohhh right, so this request would make more sense on https://github.com/github/generator-hubot/issues I suppose.

**Comment by nishizuka** [comment]
I see, thanks a lot for your support.

**Comment by mose** [comment]
This topic to switch to js actually is brought up on https://github.com/github/generator-hubot/issues/86 :)
