### ISSUE TITLE
Hubot ignores certain users

### ISSUE THREAD

**Issue by gms8994** [github/hubot#591]
We had a new employee start. Since then, Hubot doesn't see public messages from this user. Hubot sees private messages, but has no idea who the user is.

Is there a way to force Hubot to know who a user is?

**Comment by michaelansel** [comment]
@gms8994 Are you still experiencing problems after updating to the latest HipChat adapter? If not, can you close this out?

**Comment by michaelansel** [comment]
@technicalpickles Sounds like this is no longer an issue; would you mind closing it?
