### ISSUE TITLE
Advocate using yeoman generator as recommended method of writing scripts

### ISSUE THREAD

**Issue by patcon** [github/hubot#605]
https://github.com/desmondmorris/generator-hubot-script

There's still a little cleanup work to do on the project, but any thoughts on using it as the official unofficial way of kickstarting script dev?

It makes writing a script as simple as:

```
npm install -g yo
npm install -g generator-hubot-script
mkdir hubot-myscript && cd hubot-myscript
yo hubot-script
# SETUP WIZARD TRA-LA-LA SUNSHINE DONE
```

If so, we can convert this into a PR on the scripting doc. If it sounds like a good idea, feel free to jump into the queues and make any recommendations on what you'd like to see in it before merging this in.

cc: @desmondmorris

**Comment by mose** [comment]
This thread is quite old and I think it's fixed, as the usage of the generator is included in the current documentation and helpers.
