### ISSUE TITLE
Better documentation / new bot generation concerning redis

### ISSUE THREAD

**Issue by technicalpickles** [github/hubot#621]
A lot of users have reported issues around hubot failing to start because of redis not being running. There's a few options for it:
- better redis-brain error checking https://github.com/github/hubot-scripts/issues/1257
- better documentation in README about needing redis (by default)
- improved generator for making redis-brain optional

Basically, we'd want all of these things. The first two are straightforward, but the generator is more complex. We support  deploying to heroku out of the box, which is why redis-brain is included by default. This isn't really obvious though, so people self hosting usually run into problems.

If we are going to hack much on the generator, I rather see something like yeoman used cc https://github.com/github/hubot/issues/606 @patcon

**Comment by mose** [comment]
I have the feeling this problem is not current anymore. Closing it :)
