### ISSUE TITLE
Routed URLs are inconsistent.

### ISSUE THREAD

**Issue by ChristianGaertner** [github/hubot#622]
The HTTP interface is inconsistent!
Let's have a look (lets say our bot is called "homer"):

/hubot/version
/hubot/ip
etc.
BUT:
/homer/help

Is this by design or a bug?

If it is by design maybe we should change that. I think this is really inconvient to use.

btw: I could fix these, if you guys tell me which one to use (hubot or the bot's name).

Cheers,

Christian

**Comment by michaelansel** [comment]
@ChristianGaertner Did you ever submit a PR for this? If not, I can pick it up.

**Comment by ChristianGaertner** [comment]
@michaelansel Feel free to do so :D

**Comment by michaelansel** [comment]
I did some digging, and it looks like it is exclusively external scripts that define a route of `/#{@name}/stuff` (core is all `/hubot/stuff`. I'll start putting together PRs for things in hubot-scripts, but I think the only action for the core is adding documentation.

**Comment by technicalpickles** [comment]
Closing this since we have documentation talking about using the `/hubot` namespace.
