### ISSUE TITLE
hubot on hipchat does not reply on room @mention but works on 1-1 chat

### ISSUE THREAD

**Issue by bernsie** [github/hubot#651]
whenever i throw a command at hubot in a room `@hubot help` i get nothing, but typing `help` in 1-1 chat works fine, am i missing something?

Hubot v2.7.1
hubot-hipchat v2.6.4

**Comment by matyo91** [comment]
@sableloki, @VincentvD i got the same issue, but all work fine for me since i discovered that Hipchat hubot doesn't response from mentioning himself in chat rooms (i was logged as same as bot and myself with same credentials)

here is the proof in the code : 
https://github.com/hipchat/hubot-hipchat/blob/master/src/connector.coffee#L433

**Comment by sableloki** [comment]
@matyo91 are you saying that its an issue with the connector, or with the way hipchat itself works?

**Comment by matyo91** [comment]
If it is what you suggested on your topic issue, i will say from the connector, by commenting connector.coffee#L433 ligne then hubot-hipchat did succeed to response to himself in room chat.

**Comment by VincentvD** [comment]
@matyo91 I suspected this so I gave the bot it's own credentials. Then it still didn't respond in channels.

**Comment by pusherman** [comment]
If you are using the self hosted version of hipchat make sure you

$ export HUBOT_HIPCHAT_XMPP_DOMAIN=btf.hipchat.com

This resolved the issue for me.

**Comment by rgalindo33** [comment]
@pusherman :+1:

**Comment by technicalpickles** [comment]
It sounds like we have some good workaround here. I checked the upstream bug (https://github.com/hipchat/hubot-hipchat/issues/163) and that's been marked closed, so I'm going to close this too.

**Comment by buglessdr** [comment]
Just wanted to throw out - that I had to put All as the options for the HUBOT_HIPCHAT_ROOMS - not sure why it would work with all but not a specific chat room

**Comment by ryanbmilbourne** [comment]
I encountered this issue setting up a new hipchat-adapter on our stand-alone hubot server.  @pusherman's `export HUBOT_HIPCHAT_XMPP_DOMAIN=btf.hipchat.com` did the trick for me. :+1:

**Comment by mickmcgrath13** [comment]
+1 for @pusherman's solution!
