### ISSUE TITLE
Hubot on Windows Server

### ISSUE THREAD

**Issue by ppatarinski** [github/hubot#652]
I am looking for a better way to run hubot on a Windows server. Right now I can just open node command line and run hubot -a campfire and it connects to campfire and is fully functional. That however is not really a scalable approach. I want to be able to run multiple bots on the same server and having 10+ command lines open just doesn't seem to be a good idea. Thanks in advance

**Comment by technicalpickles** [comment]
cc https://github.com/github/hubot/pull/984 for an update on the windows documentation

**Comment by technicalpickles** [comment]
https://github.com/github/hubot/pull/984 offers some better alternatives, so going to close this for now. I don't think Windows support is a priority for the maintainers right now (ie not on the roadmap), but we are happy to review & merge improvements that are submitted.
