### ISSUE TITLE
robot.load tries to load both .coffee and .js versions of script when transpiled

### ISSUE THREAD

**Issue by ppatarinski** [github/hubot#653]
Hi all,

There is an issue with the Load function 

Fs.exists path, (exists) =>
      if exists
        for file in Fs.readdirSync(path).sort()
          @loadFile path, file

The issue is present when you have both a js file and a coffee script file in the scripts folder (this happens when you transpile the coffee script (produces a js file in the same directory)). Since the for loop is not checking if a script by that name is already added it will add both the coffee script and the javascript, resulting in a duplicate. 
So when you call 
  hubot ping 
you get 
  pong 
  pong

I am very new to coffee script, so not going to try to submit a patch, but here is my 2 cents on fixing it. 

When you are iterating through the files and the ext is '.js' replace the ext with '.coffee' and check if a file by that name is already loaded. If so do not load it.

Cheers
Paul

**Comment by michaelansel** [comment]
c.f. #648 since this is probably useful information to include in the debugging docs
