### ISSUE TITLE
Is there a way for hubot to find out whether a user is online or not ??

### ISSUE THREAD

**Issue by rachitgarg** [github/hubot#680]

**Comment by technicalpickles** [comment]
There isn't currently.

You might be able to use the underlying libraries for your adapter (ie [node-irc](https://github.com/nandub/node-irc) for [hubot-irc](https://github.com/nandub/hubot-irc). If enough adapters supported it, I could see adding another method to `Adapter` for checking online-ness, and then exposing that in `Robot`.
