### ISSUE TITLE
Flowdock Multi-Messages out of order

### ISSUE THREAD

**Issue by JoshCheez** [github/hubot#691]
Im running hubot in a flowdock chat instance and I have a script that sends several msg.send into flowdock chat from a loop. When I run the script in the console, the messages display in order, but when I run the script in flowdock, the messages come in seemingly random order. This seems like an issue with flowdock, but I was wondering if there was anything I can add to my code to make sure they send in order.

**Comment by technicalpickles** [comment]
@Mumakil I checked hubot-flowdock for PRs around this, but didn't see any: https://github.com/flowdock/hubot-flowdock/pulls?utf8=%E2%9C%93&q=author%3AMumakil . Did you mean this for another issue?

**Comment by Mumakil** [comment]
@technicalpickles this was fixed last september https://github.com/flowdock/hubot-flowdock/issues/54

**Comment by technicalpickles** [comment]
@Mumakil great, thanks!
