### ISSUE TITLE
Is there a way to synchronize messages posted by hubot ?

### ISSUE THREAD

**Issue by rachitgarg** [github/hubot#694]
What I want is that hubot should post a particular message when all the messages have been posted...but currently that last message gets jumbled up with other messages...suggest some way of doing it..

**Comment by technicalpickles** [comment]
Closing this, since we've answered the initial question. It's not currently possible to call `send` or `reply` multiple times and get a consistent ordering. Adapters can implement `send` and `reply` to send an array of messages in a specific order though.
