### ISSUE TITLE
Newbie First Time Install Probs

### ISSUE THREAD

**Issue by ductapehondo** [github/hubot#706]
Hey there,
If this isn't the right place for this, please let me know and if possible point me in the right direction. Many thanks in advance. 
I'm very well over my head here, but really want to start using hubot to automate some routine tasks and grow it to be ridiculously powerful over time...I can't wait!  buuut...I need some beginner help first.

I'm installing on CentOS 6.3.
I'm pretty sure node.js and npm are installed as required per: https://www.digitalocean.com/community/articles/how-to-install-and-run-a-node-js-app-on-centos-6-4-64bit

I Installed Hubot and Coffeescript per:
https://github.com/github/hubot/blob/master/docs/README.md
and that seemed to work and created my own hubot, rbot:
# hubot --create rbot

I then setup my initial git commit per the instructions. 

but when i ran bin/hubot i got the following 2 errors:
[root@ops-rbot01 rbot]# bin/hubot
Hubot> [Mon May 19 2014 22:10:33 GMT+0000 (UTC)] WARNING The HUBOT_AUTH_ADMIN environment variable not set
[Mon May 19 2014 22:10:34 GMT+0000 (UTC)] ERROR [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED]

1) For the Auth_Admin, I renamed roles.coffee to rolesBKP.coffee, thinking it wouldn't pick it up (per a forum post I found on the error).  But no luck, same error when I tried to restart hubot.
How do I explicitly set HUBOT_AUTH_ADMIN environment variable to auth.coffee?

2) Probably a dumb question, but shows my general confusion, I thought I created my own hubot called rbot.  So, once I get it all working, do I start my own rbot (bin/rbot), or do I still start hubot (bin/hubot) and then 'call' for lack of a better expression, rbot?

3) For the Redis connection error, I googled and found a post recommending to install Redis. So I did all that, but still no help.  None of the Hubot install docs mention Redis, so  I'm not sure how it fits in.
Any direction here?

Thanks all,
-ec

**Comment by bkeepers** [comment]
Hi @ductapehondo

> With respect to renaming Hubot> to rbot> by using name param, sbin/hubot --name rbot
I noticed that anytime I start Hubot I'll have to use the name param to 'customize' to rbot.
That makes sense, but just want to verify.

Yeah, you can edit the last line in `bin/hubot` to make it permanent:

```
exec node_modules/.bin/hubot --name "rbot" "$@"
```

Let us know if you have any other questions.
