### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by stresler** [github/hubot#727]
If I'm looking at this properly, it appears that you're using express to provide an http listener but aren't providing an SSL option. 

I'm not a node.js guru, but I'm seeing how to do this here: http://www.backwardcompatible.net/155-Setting-up-real-SSL-Nodejs-Express

Gonna give it a shot and will PR if this works.

**Comment by technicalpickles** [comment]
cc https://github.com/github/hubot/issues/858 which could help with initializing node things for SSL, outside of hubot's core

**Comment by victorhooi** [comment]
Another thing - would love to be able to use Google's Pub/Sub API with Hubot.

However, the Pub/Sub API needs SSL - https://cloud.google.com/pubsub/prereqs:
```
Set up an HTTPS server to handle the messages. Messages will be sent to the URL endpoint that you configure, representing that server's location. Your server must be reachable via a DNS name and must present a signed SSL certificate. (App Engine applications are preconfigured with SSL certificates.)
```
Is this feature still on the radar? =)

And does anybody know of an interim workaround? (I was thinking `stunnel` to act as a SSL -> non-SSL proxy, not sure if that would work here).

**Comment by michaelansel** [comment]
#858 and removing Express from the core are the path forward. I probably won't have time to do that for a while though... (middleware, then new script interface, then testing patterns, then programmatic loading, then removing Express)

**Comment by victorhooi** [comment]
@michaelansel Thanks for the update - so by removing Express from the core, and splitting it off into its own package (e.g. `hubot-express`), the hope is that they'll be more development on `hubot-express`, including SSL support, right?

Hmm, curious if there's a workaround right now - I mean, I suppose there's nothing stopping us from importing Express in directly, setting up SSL, and using from a Hubot script? Or is that not going to work?

**Comment by michaelansel** [comment]
Sort of; the hope is that by splitting it off and adding a programmatic launch system, you could configure Express however you want, instead of it being a fixed config.

For a workaround, I *think* there is a way to disable Express, at which point, you could just initialize it manually. I'm a little short on time right now, but I'll dig if you aren't able to figure it out. If you *do* figure it out, please throw together a PR for `patterns.md` with details.

**Comment by victorhooi** [comment]
To be honest, I don't think I'll be able to work this one out properly on my own - if you could give some help, or even some pointers in the right direction, that would be awesome.

I mean, I can see where Express is defined:

https://github.com/github/hubot/blob/879ef5aaf001f08b34f9ed9bc9fd1f7180da1448/src/robot.coffee#L307

Would it somehow be possible to add in SSL support to here?

**Comment by technicalpickles** [comment]
At this point, I'm not interested in seeing hubot support for SSL in it's core. There are just too many possible options for Express in general, let alone configuring a SSL certificate.

I believe https://github.com/github/hubot/issues/858 is going to be the way forward with allowing users to configure their bot in code. That would open the door for full customization, as well as having places for other packages to extend hubot (ie adding SSL support)
