### ISSUE TITLE
Using hubot behind a proxy server

### ISSUE THREAD

**Issue by juanpaulo** [github/hubot#731]
Use hubot behind http proxies. Possibly replace current http client to request (https://github.com/mikeal/request).
Consider backward compatibility for scripts, etc.
Consider how to pass proxy info as well.

**Comment by technicalpickles** [comment]
I've never worked behind a HTTP proxy before, so it's going to be hard for me to fix this. If I knew what type of proxies are being used, could probably work out a vagrantfile to bring up a development environment behind one.

**Comment by nottinhill** [comment]
When will this be possible? I am sorry to hear that devs in here actually have never worked behind a proxy - it is almost unbelievable - am I the only one employed here?

**Comment by technicalpickles** [comment]
@nottinhill it is a pretty low priority for my hubot needs so I'm not going to get to it anytime soon.

I'm happy to review and merge pull requests to support it though!

**Comment by michaelansel** [comment]
@nottinhill We have pretty hard proxy requirements and using the above gist has been enough to get everything working. I'll look at making the injection method less of a hack, but the gist should be enough to allow you to move forward.

**Comment by nottinhill** [comment]
Sorry to say - I long moved toward different kind of Software with Proxy feature build in.

**Comment by MitchK** [comment]
@nottinhill Check my fix for this: https://github.com/github/hubot/issues/287#issuecomment-78453521
