### ISSUE TITLE
ERROR Campfire HTTPS status code: 404

### ISSUE THREAD

**Issue by dkovar** [github/hubot#757]
Greetings,

I am trying to set up a new instance with heroku. Everything but campfire seems to be working. I figured out that I need to use the room ID and not the name, and I figured out that I needed to be logged out and not to use the same user as hubot. But still getting these errors:

2014-09-03T22:48:13.961121+00:00 app[web.1]: [Wed Sep 03 2014 22:48:13 GMT+0000 (UTC)] ERROR Campfire HTTPS status code: 404
2014-09-03T22:48:13.971905+00:00 app[web.1]: [Wed Sep 03 2014 22:48:13 GMT+0000 (UTC)] ERROR Campfire HTTPS response data:  

HEROKU_URL:             http://pacific-citadel-xxxx.herokuapp.com
HUBOT_CAMPFIRE_ACCOUNT: <my acct>
HUBOT_CAMPFIRE_ROOMS:   <my room>
HUBOT_CAMPFIRE_TOKEN:   <my token>
REDISCLOUD_URL:         redis://rediscloud:wwzxxxxxljoXjjclq@pub-redis-xxxxx.us-east-1-2.3.ec2.garantiadata.com:xxxxx

Is there any way to tell what URL it is trying to use?

Thank you.

-David

**Comment by technicalpickles** [comment]
A few more ideas:

* if getting a 404 from campfire when connecting, log the thing that was trying to be accessed. That might make it more obvious it's a subdomain
* consider changing HUBOT_CAMPFIRE_ACCOUNT to HUBOT_CAMPFIRE_SUBDOMAIN

**Comment by mose** [comment]
The issue seems fixed. The doc is actually explicit about the account being the subdomain and rooms being ids.
