### ISSUE TITLE
Provide method for external authorization policy

### ISSUE THREAD

**Issue by michaelansel** [github/hubot#768]
Building off of the filtering mechanism in #724, I'm trying to build a mechanism for setting an authorization policy outside of individual scripts. I want to do this so I can specify my own policy around who can execute commands (and potentially what level of identify verification is required) without forking every script and injecting my own company-specific code.

I think the rough end-result is something like RBAC with a permissions file that maps individual listeners to permitted users/groups. In that model, I need a way to reliably reference individual listeners so that I can apply policy to them.

The most precise, but least stable, method I can think of would be to reference each listener by regex. This feels very dirty though...

The most stable method would be to add an explicit, unique identifier to every command. This could be accomplished by tweaking the respond/hear API to include an identifier field and putting together a PR for every script I intend to use. Not a terrible solution, but it would be a lot of work and requires lots of upstream acceptance.

An in-between option would be to specify an example message and then search for all listeners that match the message. This isn't perfect, but accomplish the goal well enough.

I'm sure other concerns will come up along the way, so opening the issue now to start collecting feedback and posting updates as I work on this.

**Comment by technicalpickles** [comment]
> Going to leave this open until the listener middleware merges.

It's been merged for awhile 😂
