### ISSUE TITLE
How do I update hubot

### ISSUE THREAD

**Issue by njia** [github/hubot#771]
hubot -c  to create a deployable hubot but once I created my copy of hubot, how can I update it ?

**Comment by technicalpickles** [comment]
Given this question, I think it'd make sense to have documentation on 'care and feeding', or maybe a 'hubot operating manual' or similar.

**Comment by victorhooi** [comment]
I second this - it would certainly be awesome if README.md had a section on "How to upgrade Hubot", or "Keeping your Hubot up to date".

As it stands, in `package.json`, I saw a version of hosted-hubot, and another for hubot - it wasn't clear what the impact of upgrading one of them versus both were, or what the relationship between the two version numbers was.

**Comment by victorhooi** [comment]
Also, how should you upgrade all the other dependent packages - e.g. hubot-redis-brain, hubot-help etc.

**Comment by technicalpickles** [comment]
Once you have a hubot installed, it's a matter of using npm to update the packages, like: `npm update --save hubot-help`.

**Comment by technicalpickles** [comment]
You can also manually update `package.json`, but you'd need to know what version you are upgrading to. I've found the `npm update --save` trick works a bit better, since it just updates to the latest, and updates package.json (that's what the `--save` means).

**Comment by mose** [comment]
This looks like pretty much covered. I'm closing this issue.

**Comment by ananthaa-advisory** [comment]
Hi ,

I did the samething. Nothing turned out for me .

root@hubot:/opt/hubot# npm update --save
root@hubot:/opt/hubot# bin/hubot
Hubot> hubot help
Hubot> hubot-help
Hubot>

I am trying to exeute hubot help, nothing worked out.

Aravind
