### ISSUE TITLE
Ability to disable commands and/or throttle output by room/channel?

### ISSUE THREAD

**Issue by victorhooi** [github/hubot#778]
Is there an easy way to disable the in-built commands short of just removing the scripts?

Perhaps something more fine-grained way to disable certain commands (e.g. image me) for certain rooms/channels?

The use case for us - we want to prevent somebody "accidentally" posting inappropriate images in certain public channels (but we want the other Hubot functionality scripts to work in those public channels).

On another note - is there any way to easily throttle Hubot output at a global level? (i.e. without needing to edit each script).

**Comment by dylanh724** [comment]
late bump , but would LOVE restriction by room .... like canned messages? For our private channel, no need for canned msgs... but for guest channel ? Yea! For example using hubot-react

**Comment by geoffreyanderson** [comment]
Hey @dylanh724,

@michaelansel  merged some of my changes to make rate limits be tracked on a per-room basis.  I don't think it currently works for configuring different thresholds for different rooms, but that's an interesting idea.  https://github.com/michaelansel/hubot-rate-limit/ has all the deets and depends on the middleware change in #803.

**Comment by michaelansel** [comment]
cc michaelansel/hubot#2 where we are talking about response middleware (which you could use to rate limit command output)

**Comment by michaelansel** [comment]
Disable commands by room: https://github.com/kristenmills/hubot-command-blacklist

**Comment by technicalpickles** [comment]
Now that listener middleware has been out, I think it's safe to close this. At most, maybe there's an opportunity for more documentation in the patterns.md.
