### ISSUE TITLE
Update documentation and examples to use `res` instead of `msg`

### ISSUE THREAD

**Issue by technicalpickles** [github/hubot#786]
Whenever you see `robot.respond /something/, (msg) ->`, you'd think that msg is a `Message`. But it's not, it's actually a `Response`.

It's been proposed to update all existing examples and documentation to use `res` instead cc https://github.com/github/hubot/pull/764#issuecomment-56042492

It would be worth taking a pass through hubot-scripts as well, in order to remove prior art so people creating new scripts only see the new way of doing things.

**Comment by technicalpickles** [comment]
One downside of this is that most scripts everywhere refer to `msg` instead of `res`, since they followed what documentation we do have :sweat:

**Comment by Taytay** [comment]
For what it's worth, I am in strong favor of this change. Once I realized that `msg` was actually a `response` object, I started writing it as `response` in my scripts, and felt things were much clearer for it. It's true that legacy scripts will have this issue, but that's a small price to pay for future clarity.

**Comment by geoffreyanderson** [comment]
@technicalpickles is this issue good to close out now that you've merged the associated PRs, or is there some other follow up work that's needed (e.g. tweaking some basic scripts to use `res` instead of `msg`)?

**Comment by technicalpickles** [comment]
@geoffreyanderson yep!
