### ISSUE TITLE
Creating a dynamic list of robot.respond at runtime?

### ISSUE THREAD

**Issue by victorhooi** [github/hubot#813]
_NB: I'm not sure if this is quite in-scope for this issue tracker, please let me know if it's not._

Is there an easy way within Hubot to create a list of dynamic `robot.responds` at runtime?

For example, I'd like to retrieve a set of keys from a remote HTTP API (JIRA project codes, in this case).

I'd then like to create a `robot.respond` for each of the returned keys. Is there a recommended or idiomatic way of doing this in JS/Hubot?

**Comment by michaelansel** [comment]
Reopening and self-assigning. I want to redirect this towards "dynamic matchers" -- I should be able to have a combination of regex and code to determine if a Listener should match. This give the appearance of dynamic listener registration. Kind of related to #871 (could leverage the refactor to generalize listener registration).

**Comment by michaelansel** [comment]
This could be enabled by building on top of #986. There would likely be a little code duplication around regex matching, but I don't think that is terrible. All of the complicated logic (generating a respond pattern) is readily available.

Alternatively, you could use the idea @technicalpickles originally proposed now that #801 has merged.

**Comment by bkeepers** [comment]
> This could be enabled by building on top of #986

Closing since this can be built on top of existing functionality.
