### ISSUE TITLE
Manually call a .respond listener

### ISSUE THREAD

**Issue by lukerollans** [github/hubot#823]
I'm wondering if there's a best practice way of manually calling a `.respond` listener. In some instances, it would be great if I could manually call one and let params go through as default (eg, `msg.match[1]` for example will match nothing and fallback to default).

Normally, the action performed by the listener being called would be abstracted out but I'm just curious if anyone else has gone this way.

For example

``` coffeescript
module.exports = (robot) ->
  robot.respond /hello!/i, (msg) ->
      msg.send "Hello to you too, sir!"
      # Something here to call the below listener and have Hubot also wish the user a great day

  robot.respond /have a great day/i, (msg) ->
      msg.send "I wish upon you a fantastic day, as well!"
```

**Comment by michaelansel** [comment]
As soon as #803 merges, I've got a [commit queued up](https://github.com/michaelansel/hubot/commits/issues/823) to add `robot.listenerById` which will retrieve a specific listener based on its ID (a new metadata field introduced in #803). You would then be able to execute the listener directly using the private API `call`.

In a unit test scenario:
```coffeescript
  describe 'listener "get-room-oncall"', ->
    it 'should match "who is oncall?"', (testDone) ->
      listener = @robot.listenerById 'get-room-oncall'

      # Stub out the real work; just testing the match
      listener.callback = sinon.stub() # private API

      testMessage = new TextMessage @user, "TestHubot: who is oncall?"

      listener.call testMessage, (result) -> # private API
        expect(result).to.be.ok
        testDone()
```

The relevant bit of script would be:
```coffeescript
module.exports = (robot) ->
  robot.respond /who is oncall?/, id: 'get-room-oncall', (response) ->
    # it does stuff
```

**Comment by radius314** [comment]
i'm interested in being able to do this too, it seems kind of odd that I can't arbitrarily send a message back to hubot and chain event togethers.

**Comment by michaelansel** [comment]
@radius314 What exactly are you trying to accomplish? While I hope to enable listener retrieval soon, I envision manual invocation as an edge case (`call` is a private API). Most reuse of logic should be done with functions, external modules, and [events](https://github.com/github/hubot/blob/master/docs/scripting.md#events).

**Comment by michaelansel** [comment]
Opened #1031 to add `robot.listenerById`. When that merges, I'll close this.

**Comment by spilio** [comment]
Hi all!  This type of functionality is really important when it comes down to re-using behind the scenes 3rd party script packs.  For example if I'm building a script pack for my specific business context it would be great if I could just execute one or more commands exposed by another library (e.g. google maps scripts, etc) explicitly by using their text patterns.  

This way developers can really work on the semantic layer of thing without having to worry about internal listener IDs and other low-level stuff.  @michaelansel solution is clean but cannot work with existing libraries if no IDs have been specified for each listener.

For example if my listener hears for:

**get service x location**

and I'm using _hubot_maps_ as a dependency, my service would return the location details in the controller and if I wanted to enrich the message with geo info I'd just have an extra step calling 

**hubot map me 'query'** 

passing the coordinates, get its response and return the enriched message.

Command composition is definitely a great way of leveraging re-usability.
