### ISSUE TITLE
Option to not use Heroku keep alive during creation

### ISSUE THREAD

**Issue by mal** [github/hubot#827]
We have to run our Hubot on our own hardware due to security policy, unfortunately this means we get messages about missing Heroku URLs when starting up.

I've removed the plugin from the `package.json` and `external-scripts.json` but it would good to have it as an option at creation time.

Thanks for Hubot!

**Comment by technicalpickles** [comment]
Closing in favor of an issue on generator-hubot. Thanks for reporting!
