### ISSUE TITLE
 'hubot-true' is not in the npm registry.

### ISSUE THREAD

**Issue by tomashley** [github/hubot#838]
Trying to install a fresh hubot and it tries to install hubot-true which is unavailable in npm

I cannot even find where it gets the install list from

#> yo hubot --owner "xxx" --name "xxx" --adapter "xxx"

npm ERR! argv "node" "/usr/local/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-youtube" "hubot-true" "--save"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12
npm ERR! code E404

npm ERR! 404 Not Found: hubot-true
npm ERR! 404 
npm ERR! 404 'hubot-true' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'true'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by luckval** [comment]
```--adapter=slack``` works fine, but ```--adapter slack``` does not work.

**Comment by technicalpickles** [comment]
@luckval that is good observation, thanks for sharing!

I think that means either we need to update the documentation, or see if the option handling can require a argument instead of just using assignment (ie support --adapter slack and --adapter=slack).

**Comment by tomashley** [comment]
I can confirm that adding the '=' to the option has worked for me.

Tom

**Comment by technicalpickles** [comment]
I was able to reproduce this. I'm not sure there's much that can be done about making `--adapter slack` work out of the box, as it's yeoman and its underlying Inquirer.js that are powering it. The best thing we can do is find any documentation that talks about it, and make sure it uses `=`.

**Comment by technicalpickles** [comment]
I looked into it a bit more, and it's actually https://github.com/npm/nopt that does the argument parsing. Trying to figure out if you can specify a value is a String and not a Boolean. The documentation seems to imply it.

References:


* https://github.com/yeoman/generator/blob/b611741e98710e2737080eab6e8bb5e8521fa4ee/lib/base.js#L228-L265
* https://github.com/yeoman/generator/blob/b611741e98710e2737080eab6e8bb5e8521fa4ee/lib/base.js#L322-L337
* https://github.com/npm/nopt

**Comment by technicalpickles** [comment]
https://github.com/github/generator-hubot/pull/23 should fix this. Thanks for reporting it!
