### ISSUE TITLE
Brain's mergeData method overwrites existing data

### ISSUE THREAD

**Issue by matsukaz** [github/hubot#846]
As the comment on brain.coffee says, mergeData method is not merging data correctly.

> Caveats: Deeply nested structures don't merge well.

https://github.com/github/hubot/blob/master/src/brain.coffee#88-90

it's just copying the property, so it's like overwriting instead of merging.

When I use hubot-redis-brain, mergeData method is called everytime hubot reconnects to Redis.
As a result, all the data in Redis recovered, but the data only existed in memory(such as robot.brain.data) disappeared because data's were overwritten.

**Comment by bouzuya** [comment]
#542

**Comment by matsukaz** [comment]
Looks like vthree-rethink branch has "ready" event support.
Should I wait for vthree-rethink branch to be merged into master branch and wait for redis-brain's update to follow "ready" event changes?
It seems to take a while. hmm...

Also vthree-rethink branch still implements mergeData method in public, so problem may still occurs :disappointed_relieved:

**Comment by technicalpickles** [comment]
@matsukaz that branch is basically dead, unfortunately :sweat:  It tried to do too much at once, so was really difficult to ever release. Some parts have been extracted from it though, so might be worth doing that with the ready event.

Maybe we could use something like https://github.com/KyleAMathews/deepmerge ?
