### ISSUE TITLE
How to instrument Newrelic APM with hubot?

### ISSUE THREAD

**Issue by brodock** [github/hubot#847]
Newrelic APM requires that we require 'newrelic' npm at the very beginning. I can't do so without forking hubot npm.
I was thinking of that we could create a folder similar to "scripts" to handle this type of situations, being required before everything else.

Here is the desired behaviour:
- initializers (folder)
- hubot start code will look for anything inside initializers and will require it based on the filename
- hubot will proceed to the current behavior after that.

**Comment by technicalpickles** [comment]
That would be really cool to instrument hubot with newrelic!

The way I have thought about it is instead of adding a new special case 'initializers' folder, is to just use plain old coffee-script, and have something like a `index.coffee` in the root of a hubot script. That way, you can have full control over the environment, and could programmatically do whatever you want (load libraries, external scripts, etc).

I think there would need to be quite a bit of refactoring around `bin/hubot`, `index.coffee`, and `src/robot.coffee` to support that though.

**Comment by JosephEarl** [comment]
Is there a way to instrument Hubot using different tools?

I've tried using NewRelic with Hubot as-is, and it doesn't work https://discuss.newrelic.com/t/error-integrating-newrelic-with-hubot/8178

**Comment by michaelansel** [comment]
Maybe something like this? The error in the linked discussion is caused by `newrelic.js` not returning a function.

`000-newrelic.coffee`:
```
require 'newrelic'
module.exports = (robot) ->
```

**Comment by JosephEarl** [comment]
I'll give it a try and let you know, thanks @michaelansel

**Comment by JosephEarl** [comment]
Thanks @michaelansel that worked!

For others:
1. Copy the newrelic.js into the root folder from node_modules/newrelic/newrelic.js and edit it to add your license key
2. Add a newrelic.coffee into scripts/ with the content from @michaelansel's comment above
3. Add "newrelic" to hubot-scripts.json

**Comment by JosephEarl** [comment]
However you will see this warning in New Relic

    Some modules were uninstrumented during the current time window: express, connect. Make sure require('newrelic'); is the first line of the application's main module.

**Comment by nickgrossman** [comment]
Thanks -- I got this far, and did in fact see the warning that @JosephEarl mentioned.

I can't quite tell what's going on now -- clearly New Relic is picking up my hubot app, but it doesn't seem to be recording any transactions.

Anyone get this all the way working?

Thanks,
Nick

**Comment by JosephEarl** [comment]
@nickgrossman Same for me. I think #858 needs to be done for that to work. I ended up giving up on this for the time being.

**Comment by nickgrossman** [comment]
Gotcha
Thanks for the reply 

--

http://nickgrossman.is on the fly




On Sun, Nov 29, 2015 at 11:37 PM -0800, "Joseph Earl" <notifications@github.com> wrote:












@nickgrossman Same for me. I think #858 needs to be done for that to work. I ended up giving up on this for the time being.

**Comment by technicalpickles** [comment]
I did some work towards https://github.com/github/hubot/issues/858 over in https://github.com/github/hubot/pull/1110

If anyone is interested in NewRelic support, that'd be a good branch to try out.

**Comment by technicalpickles** [comment]
I think the original question was addressed, with #858 working towards a better solution longer term.
