### ISSUE TITLE
Sort Help Commands by Script?

### ISSUE THREAD

**Issue by cycomachead** [github/hubot#862]
I know the help list is intentionally sorted alphabetically, but so far in my experience, at least with a large number of commands, it would be helpful if these were grouped by the scripts they come from. 

I don't think there's a current way to easily do this, and I'd be willing to experiment with implementing this if others are interested.

**Comment by technicalpickles** [comment]
That is a really good point. I think if you are viewing all commands (like with just `hubot help`), then having them sorted by script can make sense. If you are searching for something though (like with `hubot help pager`), then maybe it's better to have it in purely alphabetical order.

Some places you can check out to experimenting:

* https://github.com/hubot-scripts/hubot-help
* https://github.com/github/hubot/blob/master/src/robot.coffee#L346-L375

You can see in the snippet above, we do actually store documentation sections per file as it's parsed, but we don't persist it anywhere outside that call. Things only get added onto `robot.commands`.


The help script lives over

**Comment by cycomachead** [comment]
I think I got around to getting this to work, and PR #917. However, my current solution can't quite get around sorting when a term is provided since that is done by a separate help script. I can also make a PR to hubot-help. It will slightly change the behavior of anyone who uses a help script that isn't a package, but searching still works so nothing is broken. I could also add some appropriate docs somewhere if desired.
