### ISSUE TITLE
hook up hubot to socket.io chat application

### ISSUE THREAD

**Issue by abderrahmengharsallah** [github/hubot#874]
i''ve managed to install hubot locally but couldn't deploy it in a local socket.io chat application how should i proceed

**Comment by technicalpickles** [comment]
@abderrahmengharsallah would you mind elaborating a bit? There are a couple ways you could mean.

Hubot has builtin [expressjs](http://expressjs.com/) support, so feasibly, you could add socket.io to that. Or do you mean you want to include hubot in your socket.io? That has been asked for over in https://github.com/github/hubot/issues/815 but there's not really a good solution yet.

**Comment by technicalpickles** [comment]
> Hubot has builtin expressjs support, so feasibly, you could add socket.io to that. 

I haven't tested it, but you can make a new script, and just include socket.io code in it:

```coffeescript
# in scripts/socketio.coffee
module.export = (robot) ->
  app = require('express')()
  http = require('http').Server(app)
  app.get '/', (req, res) ->
    res.send('<h1>Hello world</h1>')

  http.listen 3000, () ->
    console.log('listening on *:3000')
```

That's basically copying the example from http://socket.io/get-started/chat/ and writing it as coffeescript.

**Comment by technicalpickles** [comment]
Actually, another reading of your question is that you have a socket.io chat application, and you want to have hubot connect to it as a client. In that case, you'd want to write a hubot adapter (similar to hubot's support for campfire, irc, slack, etc).

Unfortunately that is not super documented right now. Check out https://github.com/github/hubot/blob/master/docs/adapters.md for some quick pointers, but your best reference is going to be existing adapters.

A friend recently went through the process of writing an adapter, so he might have some notes to share cc @leefaus

**Comment by technicalpickles** [comment]
> A friend recently went through the process of writing an adapter,
https://github.com/leefaus/hubot-bunny/pull/1 is the adapter being worked on

**Comment by leefaus** [comment]
I will be writing a "Building a Hubot Adapter" document during open source Friday next week.  Looking forward to hanging out with the OSS peeps. @abderrahmengharsallah If you want some pointers before next Friday, just ping me here or start a public repo on .com and invite me to the the project.

**Comment by abderrahmengharsallah** [comment]
woow ! this community is amazing i didn't expect to get all this help, in fact I am still a noob in programming but this project i'am working on is about developing a chat application that allow you to  communicate with your house(hubot) then creating a customized script for that.
I guess my problem now is how to integrate the hubot in the socket.io chat application so basically i need to build an adapter for that. @leefaus is it hard or time consuming to build an adapter if yes maybe then i will try to develop a simple customized bot manually 
this is what my final app should look like : https://www.youtube.com/watch?v=PplAymrv0hA

**Comment by technicalpickles** [comment]
> I guess my problem now is how to integrate the hubot in the socket.io chat application so basically i need to build an adapter for that. @leefaus is it hard or time consuming to build an adapter if yes maybe then i will try to develop a simple customized bot manually 

@abderrahmengharsallah for the purpose of your project, I would think about what you would get by having a hubot adapter for it. If you'd benefit from existing hubot scripts, or any other aspect of hubot, then it'd make sense I think.

I'd also like to link to @benbalter's https://github.com/benbalter/hubot-webscale which is a hubot adapter for socket.io. I'm not sure if that would directly be usable, but it should give you some ideas.

> this is what my final app should look like : https://www.youtube.com/watch?v=PplAymrv0hA

Now that I see it, it does kinda look like texting with your 'house' is the way to interact with it. [Twilio](https://www.twilio.com/) is a service for texting and making calls, and there's [hubot-twilio](https://github.com/neilcauldwell/hubot-twilio). If that works for you, the main thing you would have to do is implement hubot scripts for interacting with your backend server to control the house.

**Comment by technicalpickles** [comment]
>> I will be writing a "Building a Hubot Adapter" document during open source Friday next week.

Check out  https://github.com/github/hubot/pull/883 for work on this

**Comment by SukanyaDas-MeMe** [comment]
@abderrahmengharsallah Can you tell me whether you are able to connect/integrate hubot with custom made socket.io chat application?
