### ISSUE TITLE
Multiple Hubot instances on same Redis backend, but different prefix?

### ISSUE THREAD

**Issue by victorhooi** [github/hubot#878]
At the top of `redis-brain.coffee`, it says:
```
# Configuration:
#   REDISTOGO_URL or REDISCLOUD_URL or BOXEN_REDIS_URL or REDIS_URL.
#   URL format: redis://<host>:<port>[/<brain_prefix>]
#   If not provided, '<brain_prefix>' will default to 'hubot'.
```

Is it safe to run multiple Hubot instances, backed by the safe Redis backend, but using a different `brain_prefix`?

(In other issues e.g. #292 #453 it mentions not being safe to use a single Redis backend - however, I'm not sure if this was before the `brain_prefix` thing was introduced?)

Also - as an aside - a lot of configuration (e.g. how to set the REDIS port) only seem to be documented in the actual code itself, in comments - but not in actual documentation. Is there a reason for this?

Would you be amenable to PRs to add some more documentation around them?

**Comment by technicalpickles** [comment]
> (In other issues e.g. #292 #453 it mentions not being safe to use a single Redis backend - however, I'm not sure if this was before the brain_prefix thing was introduced?)

@victorhooi Those issues are both before brain_prefix was introduced. It should be okay to have two hubots using the same redis server, with different prefixes by setting different REDIS_URLs should be okay.

> a lot of configuration (e.g. how to set the REDIS port) only seem to be documented in the actual code itself, in comments - but not in actual documentation. Is there a reason for this?

Not that I can think of. I think of REDIS_URL as the canonical way to specify configuration, as it's flexible enough to specify basically everything, including port. https://github.com/hubot-scripts/hubot-redis-brain does talk about what can be set using REDIS_URL.

> Would you be amenable to PRs to add some more documentation around them?

Yep! Just keep in mind there is both docs here and in https://github.com/hubot-scripts/hubot-redis-brain around this.
