### ISSUE TITLE
Document POST format for http-listener example

### ISSUE THREAD

**Issue by 100ideas** [github/hubot#894]
I am having trouble getting the [http-listener example](https://github.com/github/hubot/blob/master/docs/scripting.md#http-listener) to work.

``` coffeescript
module.exports = (robot) ->
  robot.router.post '/hubot/chatsecrets/:room', (req, res) ->
    room   = req.params.room
    data    = JSON.parse req.body.payload
    secret = data.secret

    robot.messageRoom room, "I have a secret: #{secret}"

    res.send 'OK'
```

I put the code in `scripts/secret.coffee` and started local hubot, then tried the following with curl:

```shell
$ curl -H "Content-Type: application/json" -d '{"secret":"C-TECH Astronomy"}' http://localhost:8080/hubot/chatsecrets/general
```
maybe I need to put my json into a payload key...
```shell
$ curl -H "Content-Type: application/json" -d '{"payload": {"secret":"C-TECH Astronomy"}}' http://localhost:8080/hubot/chatsecrets/general
```
grrr, both fail like so:
```
SyntaxError: Unexpected token o
  at Object.parse (native)
  at /Users/100ideas/dev/hubot/scripts/secret.coffee:4:14, <js>:6:19
  at callbacks (/Users/100ideas/dev/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:164:37)
```

Then I realized maybe I didn't need `JSON.parse` since my data already is JSON, so:

``` coffeescript
module.exports = (robot) ->
  robot.router.post '/hubot/chatsecrets/:room', (req, res) ->
    room   = req.params.room
    data    = req.body.payload
    secret = data.secret

    robot.messageRoom room, "I have a secret: #{secret}"
    console.log req.body

    res.send 'OK'
```
It worked. In the shell adaptor w/ hubot I see
```
[Mon Mar 16 2015 21:51:30 GMT-0700 (PDT)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
I have a secret: C-TECH Astronomy.
{ payload: { secret: 'C-TECH Astronomy' } }
```

Could someone show me a POST request for this example code that depends on `JSON.parse`? i.e. I am guessing a POST made w/ jquery & json.stringify or something. It might be nice to add this POST example to `scripting.md#http-listener`. Thanks!

**Comment by tombell** [comment]
The body of the request is automatically parsed as JSON when using the `body-parser` middleware. https://github.com/github/hubot/blob/master/src/robot.coffee#L291

**Comment by 100ideas** [comment]
@tombell why does the example code include `data    = JSON.parse req.body.payload`?

**Comment by technicalpickles** [comment]
@100ideas my bet would be that the documentation wasn't updated once https://github.com/github/hubot/pull/446 (which added bodyParser) landed

**Comment by 100ideas** [comment]
@technicalpickles Thanks! That clarifies things.

Is `{"payload": {"keys":"values"}}` a JSON convention or a requirement when POSTing as `Content-Type: application/json`? 

Or does `payload` get auto-populated from a POST of `aplication/x-www-form-urlencoded` or `multipart/form-data` by the express middleware?

**Comment by tombell** [comment]
The JSON in the example is arbitrary. `req.body` will be whatever parsed JSON is posted.

**Comment by technicalpickles** [comment]
Fixed by https://github.com/github/hubot/issues/898
