### ISSUE TITLE
Document finding and adding external scripts

### ISSUE THREAD

**Issue by technicalpickles** [github/hubot#901]
I proposed this in https://github.com/hubot-scripts/packages/issues/60#issuecomment-77089849 

>Basically, since we've been doing script packages, the example (or generated) package.json has the 'hubot-scripts' keyword. I already said that in the context of having a web accessible view. But it turns out, npm has a CLI way of searching packages, as well as seeing more info:
>```
connor:examplebot technicalpickles$ npm search hubot-scripts pagerduty
NAME                   DESCRIPTION                                               AUTHOR            DATE       VERSION KEYWORDS                            
hubot-pager-me         PagerDuty integration for Hubot                           =technicalpickles 2014-12-16 2.0.2   hubot hubot-scripts pagerduty       
hubot-pagerduty-github PagerDuty Integration for checking who's on call, making… =patcon           2014-04-24 0.1.0   hubot hubot-scripts pagerduty alerts
npm home hubot-pager-me
```
>
>At that point, npm opens a browser window  for the homepage, where the user can figure out the next steps for installing.
>
> We can add that to the hubot docs, along with things like how to update hubot and scripts.

I think docs/index.md would be a good place for this, but open to ideas.

**Comment by jglovier** [comment]
@technicalpickles so if I'm following this correctly, it's just a matter of adding the instructions to the docs, then, yes?

**Comment by technicalpickles** [comment]
@jglovier that's it exactly. It's mostly finding the right place so it flows, and is easy to find.

**Comment by jglovier** [comment]
:metal:

Yeah index feels legit - at least for now.

**Comment by geoffreyanderson** [comment]
Since #956 was merged, this is probably good to close @technicalpickles @jglovier @bkeepers?

**Comment by technicalpickles** [comment]
@geoffreyanderson Yep, thanks for the reminder!
