### ISSUE TITLE
[Help] Installing scripts and deploying to Heroku in Slack

### ISSUE THREAD

**Issue by mvaneijgen** [github/hubot#902]
I have Hubot up and running in my Slack channel and everything works fine, but when I try to install a new scripts, my Hubot will build successfully, but goes offline in my Slack channel and im to much of a noob to debug what is going wrong. 

I made a screencast of my workflow and hope someone here can point me to a solution  http://youtu.be/Mfa5hAoC3iI 

This are the scripts I am trying to install 

* [yell.coffee](https://github.com/github/hubot-scripts/blob/master/src/scripts/yell.coffee)
* [Scotch.coffee](https://github.com/github/hubot-scripts/blob/master/src/scripts/scotch.coffee)
* [Wikipedia.coffee](https://github.com/github/hubot-scripts/blob/master/src/scripts/wikipedia.coffee)

**Comment by geoffreyanderson** [comment]
This is kind of a weird behavior...I don't seem to be having the same probably with a heroku-based hubot I'm running.  Can you try checking the output of the `heroku logs` command in your hubot repository after one of these deployments finishes and see if there's anything obvious coming back from heroku?  I'm inclined to say there might be some failure with one of the plugins while hubot is loading up (perhaps missing dependencies in your package.json file).

**Comment by bkeepers** [comment]
@mvaneijgen I'm going to close this out since we haven't heard back from you, but please let us know if you're still having troubles and there's anything we can help with.
