### ISSUE TITLE
Documentation Gotchas in Adapter Development

### ISSUE THREAD

**Issue by BonarBeavis** [github/hubot#907]
https://hubot.github.com/docs/adapters/development/

try 
  {Robot,Adapter,TextMessage,User} = require 'hubot' 
catch 
  prequire = require('parent-require') {Robot,Adapter,TextMessage,User} = prequire 'hubot'

Did not for for me, Hubot could not receive TextMessage, because the Adapter constructed messages from another source file than hubot. And (TextMessage instanceof Textmessage) threw false

Solution: replace 'hubot' with '../hubot'

**Comment by technicalpickles** [comment]
@BonarBeavis did you intend to close this? Or, did you work it out?

cc @leefaus who helped put together this documentation

**Comment by BonarBeavis** [comment]
@technicalpickles 
Yes I did, it was my fault, I installed hubot also into the adapter directory. So the adapter loaded another Message.coffee than the hubot.
