### ISSUE TITLE
Can no longer curl to Hubot

### ISSUE THREAD

**Issue by ezgoodnight** [github/hubot#912]
I have http-post-say.coffee installed and I have used it to post to my Slack chatroom successfully. I've not done much to extend my hubot since then and now when I use curl: 

```
$ curl -X POST http://localhost:8080/hubot/say -d message="message" -d room='#random'

curl: (7) Failed to connect to localhost port 8080: Connection refused

```

I don't have any sort of firewall enabled and I don't think I've done anything that should have stopped node from creating the page listening at localhost:8080.

I have the hubot installed in an Ubuntu 14.04 VM. I'm not sure I've even done an apt-get update since I last did a successful curl, although I did start running hubot as a service with upstart and not just loading it on startup in rc.local.

Where do I start troubleshooting this? What information will help?

**Comment by michaelansel** [comment]
Nothing in the hubot core should have changed to impact this. Try looking at the logs (set HUBOT_LOG_LEVEL=debug) for any kind of errors. Also, try running `sudo netstat -lntp | grep 8080` to ensure that node is listening on port 8080.

**Comment by ezgoodnight** [comment]
grep did not return anything from that command. I assume this means node is not listening to that port anymore?

**Comment by michaelansel** [comment]
Yup, so you need to figure out why Hubot is failing to listen. Debug logs should be your friend here. Try searching for "Express"

**Comment by ezgoodnight** [comment]
Frustratingly enough I was just able to curl when I stopped the service and started it through the shell normally the way I had been doing. This didn't seem to work before. Upstart has to be doing something /running hubot as a service must be stopping something important.

Also: I have no idea what I'm searching for. I'm looking in hubot/node_modules/espress/node_modules/debug but I'm not finding any text files that look useful to debugging.

**Comment by ezgoodnight** [comment]
Damn it, that was it. Upstart script had the wrong default port set. I fixed that and there are now no issues. Thanks for getting me on the right track.
