### ISSUE TITLE
[Website] Blocked loading mixed active content "http://use.typekit.com/cjo0skc.js"

### ISSUE THREAD

**Issue by jomo** [github/hubot#913]
I couldn't find a repository for hubot *(why isn't it a gh-page?)* so I'm reporting here that Firefox is blocking the script `http://use.typekit.com/cjo0skc.js` on https://hubot.github.com.

You can use `https://use.typekit.com/cjo0skc.js` just fine.

**Comment by technicalpickles** [comment]
> I couldn't find a repository for hubot (why isn't it a gh-page?)

It's not a good reason, but mostly legacy reasons :sweat: 

Thanks for reporting here though!
