### ISSUE TITLE
Reconnecting causes double load of scripts

### ISSUE THREAD

**Issue by michaelansel** [github/hubot#919]
From [a comment on #71](https://github.com/github/hubot/issues/71#issuecomment-57559761):

Scripts appear to double load (resulting in double responses for everything) whenever connection is lost and reestablished.

My original hypothesis:

> The double load on reconnect is likely caused by the 'connected' event getting emitted again. The robot listens for 'connected' and loads all scripts at that point (assuming it will only get fired once). This would be adapter dependent (adapter decides when to emit 'connected').

However, it looks like the HipChat adapter handles this case already: https://github.com/hipchat/hubot-hipchat/blob/master/src/hipchat.coffee#L115

Not sure what is going on here...

**Comment by michaelansel** [comment]
@lukaszraczylo What adapter are you using when you see the issue?

**Comment by technicalpickles** [comment]
Other thoughts:

* could it be related to a script reloading script? ie reload.coffee in hubot-scripts
* could it be related to compiling coffeescript to javascript and both of them are loaded? I seem to recall a bug in that area in the past.

**Comment by lukaszraczylo** [comment]
@michaelansel hipchat adapter as well. Sorry for delay.

**Comment by apottere** [comment]
We've been seeing double responses intermittently for a while now, and I think this is the issue.  Bot will be up for a few days, and one morning will just start giving duplicated responses.  A restart fixes the issue.

**Comment by apottere** [comment]
Not sure if this belongs here, but these are the logs right before duplicated messages start appearing:

````
[Fri Apr 17 2015 15:17:35 GMT+0000 (UTC)] INFO Disconnected from hipchat.com
[Fri Apr 17 2015 15:17:35 GMT+0000 (UTC)] INFO Waiting 13s and then retrying...
[Fri Apr 17 2015 15:17:35 GMT+0000 (UTC)] ERROR null, null, { name: 'stream:error',
  parent: null,
  attrs: { 'xmlns:stream': 'http://etherx.jabber.org/streams' },
  children:
   [ { name: 'policy-violation',
       parent: [Circular],
       attrs: { xmlns: 'urn:ietf:params:xml:ns:xmpp-streams' },
       children: [] },
     { name: 'text',
       parent: [Circular],
       attrs: { xmlns: 'urn:ietf:params:xml:ns:xmpp-streams' },
       children: [ 'Stanza too big.' ] } ] }
[Fri Apr 17 2015 15:17:35 GMT+0000 (UTC)] INFO Connection was closed
[Fri Apr 17 2015 15:17:35 GMT+0000 (UTC)] INFO Disconnected from hipchat.com
[Fri Apr 17 2015 15:17:35 GMT+0000 (UTC)] INFO Connection went offline
[Fri Apr 17 2015 15:17:35 GMT+0000 (UTC)] INFO Disconnected from hipchat.com
[Fri Apr 17 2015 15:17:48 GMT+0000 (UTC)] INFO Attempting to reconnect...
[Fri Apr 17 2015 15:17:48 GMT+0000 (UTC)] INFO Connecting HipChat adapter...
[Fri Apr 17 2015 15:17:49 GMT+0000 (UTC)] INFO Connected to hipchat.com as ******
````

**Comment by michaelansel** [comment]
That looks like it is what I suspected: the HipChat adapter is likely double firing the `connected` event. I don't know that there is a prescribed behavior around the `connected` event when there are reconnects, so I'm not sure if this is a bug against the core or the adapter. @technicalpickles: any thoughts here?

**Comment by mfilej** [comment]
Has anyone noticed this with the slack adapter? We're seeing duplicate responses as described here, not 100% sure it's the same issue though.

**Comment by alitheg** [comment]
From the log output from my raspberry pi, it looks like the same issue using the Slack adapter. I get the "pong too old" message (even though I've increased the timeout), and it reconnects, for a total of 2 connections. We get double responses.

**Comment by michaelansel** [comment]
Interesting; sounds like it might be an issue with the adapter then?

**Comment by alitheg** [comment]
Yeah, that's actually likely. I have to change a timeout value on the pi to keep the slack adapter from dying the first time, and that stops the issue. I'll report it over there and see if they can find it.

**Comment by sravan-bala** [comment]
I am seeing the same issue. Anybody got lucky?

**Comment by technicalpickles** [comment]
I've experienced this on the Slack adapter too. https://github.com/slackhq/hubot-slack/issues/210 is an issue on hubot-slack for that, and I did some debugging around https://github.com/slackhq/hubot-slack/issues/210#issuecomment-143563700

> The double load on reconnect is likely caused by the 'connected' event getting emitted again. The robot listens for 'connected' and loads all scripts at that point (assuming it will only get fired once). This would be adapter dependent (adapter decides when to emit 'connected').

That's basically what I'm seeing.

I'm wondering if the fix is as simple as changing https://github.com/github/hubot/blob/master/bin/hubot#L135 to use `once` instead of `on` to only load once. I can't think of any cases yet that a reconnect means scripts would need to be reloaded.

**Comment by Floby** [comment]
I'm having this issue as well with the slack adapter and a very unstable connection.

This can be easily fixed by replacing `.on` by `.once` on this line
https://github.com/github/hubot/blob/99f20deac73f291c67114f27770c77fc91cdfbf2/bin/hubot#L135

**Comment by Floby** [comment]
I opened #1073 to load scripts only once.

**Comment by technicalpickles** [comment]
This was fixed in https://github.com/github/hubot/pull/1069

**Comment by GiriB** [comment]
What does 
 ```
[Fri Apr 17 2015 15:17:35 GMT+0000 (UTC)] INFO Waiting 13s and then retrying...
[Fri Apr 17 2015 15:17:35 GMT+0000 (UTC)] ERROR null, null, { name: 'stream:error',
  parent: null,
  attrs: { 'xmlns:stream': 'http://etherx.jabber.org/streams' },
  children:
   [ { name: 'policy-violation',
       parent: [Circular],
       attrs: { xmlns: 'urn:ietf:params:xml:ns:xmpp-streams' },
       children: [] },
```
mean? 
I am getting this error when I try to join 'All' the rooms available on my team (around 2200). What policy am I violating ?

**Comment by bhuga** [comment]
> I am getting this error when I try to join 'All' the rooms available on my team (around 2200). What policy am I violating ?

Unfortunately I think that's a question for your administrators at etherx.jabber.org. This error isn't generated by hubot.

**Comment by lukaszraczylo** [comment]
I strongly believe there's some magic limit on channels you can be present on at the same time ( both for IRC and Jabber ).
