### ISSUE TITLE
Triggering Hubot responds using HTTP

### ISSUE THREAD

**Issue by tudorlesan** [github/hubot#925]
Let's say I have a few functionalities to my hubot. What I'm trying to do is send the message to hubot through a POST.

I have my HTTP listener, which gets my message and sends an event to my main script, I catch the event, have the message. Now I would need to manually trigger any of my robot.respond's based on the message I sent. Is there any straightforward way of doing this? Thanks :)

**Comment by michaelansel** [comment]
There is kind of a way to trigger listeners (c.f. #823), but the "right and proper" method is to either have the logic pulled out into functions (if the route and listener are in the same script) or ideally use [events](https://github.com/github/hubot/blob/master/docs/scripting.md#events).

In your case, is there any reason you couldn't just have a single event handler that both the HTTP listener and the `robot.respond` leverage?

**Comment by tudorlesan** [comment]
Well I'm not entirely sure I get what you're saying ( don't have too much experience with hubot yet). The robot should react both to chat messages and http messages. What you're saying is to copy the robot.responds in the event handler(the one that gets the http message) as well?

**Comment by michaelansel** [comment]
Sort of, but without the copy ;-)

If you have this:
```coffeescript
module.exports = (robot) ->
  robot.responds /hi/, (res) ->
    res.say 'Well, hello there!'

  robot.router.get '/hubot/hi/:room', (req, res) ->
    # I want to trigger 'Well, hello there!' in :room
```

Make it do this:
```coffeescript
module.exports = (robot) ->
  robot.responds /hi/, (res) ->
    robot.emit 'hi', res.message.user.room

  robot.router.get '/hubot/hi/:room', (req, res) ->
    robot.emit 'hi', res.params.room

  robot.on 'hi', (room) ->
    robot.messageRoom room, 'Well, hello there!'
```

Alternatively, if everything is in the same script, you can just use a shared function in place of events.

**Comment by tudorlesan** [comment]
:+1: thanks

**Comment by michaelansel** [comment]
@tudorlesan If that solved your problem, would you mind closing the issue? Thanks!

**Comment by tudorlesan** [comment]
sure

**Comment by technicalpickles** [comment]
Might be worth documenting this as a pattern in docs/patterns.md.

**Comment by michaelansel** [comment]
Reopening so that we'll actually write the docs...

**Comment by technicalpickles** [comment]
From @illusionuk on https://github.com/github/hubot/issues/987:

> So if I send something like 
>```
>curl -X POST -d message="hubot ping" http://localhost:8080/hubot/blah
>```
>
>Hubot would return with the correct response of "Pong".

I think one way of looking at this is to run two hubots with the same code base: one with a chat adapter, and another with a http api adapter.

Alternatively, one could probably write a hubot script that exposes an end-point, and constructs a `Message` object, and then `robot.receive` it.

**Comment by michaelansel** [comment]
Another use case: have `hubot-cron` simulate a message being sent to a channel to trigger a listener.

Maybe the way to think about this is that there are multiple ways of receiving messages at all times? (HTTP, Chat, Internal). Far from a fully-baked idea, but just throwing thoughts out there.

**Comment by illusionuk** [comment]
Thanks, all ideas are welcomed. Will look into this.

**Comment by michaelansel** [comment]
Security risk I just thought of: this could allow bypassing all chat system security (no need to authenticate with the chat service). Also, we would need to create a Hubot user or something for received messages.
