### ISSUE TITLE
How often are hubot scripts run?

### ISSUE THREAD

**Issue by noahgrant** [github/hubot#932]
I have a hubot script (full disclosure: with slack adapter), that references a `_members` closure variable roughly like so:

```js
module.exports = (robot) ->
    _members = (robot.brain.get('clubMembers') || []).concat CAPTAINS
   ...
```

where CAPTAINS is a hard coded array of strings.

I'm running into an issue where the script is getting run something around once a day, but `robot.brain.get('clubMembers')` is returning a falsy value, and thus `_members` is a list that includes only CAPTAINS.  However, running `hubot show storage` reveals `clubMembers` to be persistent, as expected, containing a list of the names of all members.

I'm not really sure why `robot.brain.get('clubMembers')` would ever return a falsy value.  It's as though this script gets rerun while redis is restarting and it returns null.  Do you have any insight as to why this might happen?

Thank you!!

**Comment by michaelansel** [comment]
Are you running your bot on heroku? My first crazy idea:
* bot is running on heroku
* heroku kills the dyno due to low activity
* sending a slash command wakes up the bot
* bot hasn't finished loading when it processes the command (brain is empty)
* when you run `show storage` the bot has finished loading and gives the expected reply

Not sure if that is your issue, but an idea until I have time to think in depth.

**Comment by technicalpickles** [comment]
This is less about frequency of running, but a different possible problem with the script. The `modules.exports` method gets run pretty early in the hubot's boot up. Depending on what brain script you are using, this line might run before the brain is loaded:

```coffeescript
_members = (robot.brain.get('clubMembers') || []).concat CAPTAINS
```

To fix that, you can use this to only happen after the brain is loaded.

```coffeescript
   robot.brain.on 'loaded', () ->
    _members = (robot.brain.get('clubMembers') || []).concat CAPTAINS
```

**Comment by technicalpickles** [comment]
Actually, depending on when you `robot.brain.set('clubMembers', 'some value')`, the brain loading thing could account for when it's coming back as falsy.

**Comment by noahgrant** [comment]
ahh that makes a lot of sense, i'll try that!! thanks!!

**Comment by bkeepers** [comment]
@noahgrant Let us know if that doesn't work for you.

**Comment by noahgrant** [comment]
it did, sorry for not responding.  Thank you!!
