### ISSUE TITLE
Third-party Adapters

### ISSUE THREAD

**Issue by kasajian** [github/hubot#940]
Hi guys.  I just wanted to make a request to remove the chatwork hubot from the list.   It doesn't work.   When you try to use it, everything comes up in Japanese and there's no translations.

My proposal is to just remove it form the list so it's not confusing to people.

Thanks!

**Comment by WOLVIE97** [comment]
Hopefully.....🐂

**Comment by WOLVIE97** [comment]
Well,  I hope this works.....

**Comment by bkeepers** [comment]
@akiomik is the chatwork adapter still expected to work?

/cc https://github.com/github/hubot/pull/618

**Comment by akiomik** [comment]
@kasajian

> It doesn't work. 

What do you mean? A little while ago when I've tried the latest hubot-chatwork 0.1.0 with hubot 2.12.0, it works well.

> everything comes up in Japanese and there's no translations.

Like you said, I created only poor README as the documents, but it does NOT contain Japanese.

-----

@bkeepers Of course yes, and it works actually.

**Comment by bkeepers** [comment]
@akiomik thanks.

@kasajian let us know if it's still not working for you and if there's anything we can do to help.
