### ISSUE TITLE
Hubot doesn't join IRC channel, stuck on "INFO Using default redis on localhost:6379"

### ISSUE THREAD

**Issue by frdmn** [github/hubot#941]
I try to create a Dockerized Hubot instance, but at the moment the bot stucks on:

```
[Wed May 13 2015 12:33:43 GMT+0000 (UTC)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web_url | cut -d= -f2)`
[Wed May 13 2015 12:33:43 GMT+0000 (UTC)] INFO Using default redis on localhost:6379
```

It connects fine to the actual IRC server (I can tell, since I can `/whois <botname>` and see it's connected) but doesn't want to join the channel.

Is there any verbose switch, so I can see whats going on?

Not sure what's the problem is right now.

You can find the Docker repository over here: http://git.frd.mn/frdmn/docker-hubot/tree/master

**Comment by technicalpickles** [comment]
> Is there any verbose switch, so I can see whats going on?

You can try setting `HUBOT_LOG_LEVEL=debug` to get more output.

**Comment by drafie** [comment]
I have exactly the same issue.

**Comment by frdmn** [comment]
@technicalpickles thanks, but that didn't really help either:

    ❯  140_docker-hubot git:(master) docker logs -f --tail=all docker-hubot
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Loading adapter irc
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Loading scripts from /opt/hubot/scripts
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/scripts/example.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Loading scripts from /opt/hubot/src/scripts
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Loading hubot-scripts from /opt/hubot/node_modules/hubot-scripts/src/scripts
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Loading external-scripts from npm packages
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-diagnostics/src/diagnostics.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-help/src/help.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web_url | cut -d= -f2)`
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-heroku-keepalive/src/heroku-keepalive.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-google-images/src/google-images.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-google-translate/src/google-translate.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-pugme/src/pugme.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-maps/src/maps.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] INFO Using default redis on localhost:6379
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-redis-brain/src/redis-brain.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-rules/src/rules.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-shipit/src/shipit.coffee
    [Wed May 13 2015 12:52:12 GMT+0000 (UTC)] DEBUG Parsing help for /opt/hubot/node_modules/hubot-youtube/src/youtube.coffee

@drafie do you run Hubot in a Docker environment as well?

**Comment by drafie** [comment]
@frdmn No, I am running it on an EC2 / Ubuntu instance.  I spent a lot of time messing about with it last night and could not get it to respond.

**Comment by JPomichael** [comment]
+1

**Comment by michaelansel** [comment]
Based on those logs, the adapter believes it is connected (scripts are loaded after connect). So, it seems like something in the IRC adapter is misbehaving. I think more debug info from the adapter is needed to understand what is misbehaving.

**Comment by technicalpickles** [comment]
>  I think more debug info from the adapter is needed to understand what is misbehaving.

There's an environment variable to turn on more IRC debugging: `HUBOT_IRC_DEBUG`

**Comment by bkeepers** [comment]
Closing as stale.
