### ISSUE TITLE
Documentation on using Redis Brain

### ISSUE THREAD

**Issue by victorhooi** [github/hubot#952]
Is there some more detailed documentation on using the Hubot redis brain effectively, or good practices for it?

For example, the scripting docs (https://github.com/github/hubot/blob/f672bc03cf4bf415ce45ed60c38334d988fae8f4/docs/scripting.md) simply talk about storing and retrieving key-value strings.

However, if you look at scripts like this:

https://github.com/hubot-scripts/hubot-team/blob/4a811e2f1881e85848c5801f5ff8b665f09390fa/src/models/team.coffee

They use more slightly more complex structures (arrays, dicts etc.) - I assume these just get stringified, then stored in redis:

```
    teams = []
    for key, teamData of @store()
      continue if key is @defaultName()
      teams.push new Team(teamData.name, teamData.members)
    teams
```

They also seem to namespace things as follows (which I'd hadn't realised you could do until I saw this):

```
    @robot.brain.data.teams or= {}
```

It'd be nice if there were more examples of the redis-brain in action, or even just pointers to good example scripts where we can see good practices for these things?

**Comment by victorhooi** [comment]
OK, I take that back, I don't get how the namespacing thing works above...

**Comment by victorhooi** [comment]
I'm also a little unclear of the significance of the `data` in `robot.brain.data` - e.g.:

```
  isNotified = (keyword, username) ->
    robot.brain.data[keyword] ?= []
    robot.brain.data[keyword].some (x) -> username == x
    ...
    unless isNotified("invite", username)
      replyTo(username, "Are you looking for an atom invite?  Go to https://atom.io/ and put in your email, or join the #product-invitations room.")
      robot.brain.data.invite.push username
```

http://theprogrammingbutler.com/blog/archives/2014/02/28/robots-can-do-support-too/

**Comment by michaelansel** [comment]
In terms of "best practices", they are pretty lacking beyond what is in the scripting docs. Namespace your stuff so that you don't conflict with other scripts and use the key-value methods (`get`/`set`). Everything is persisted via `JSON.stringify`. I know @technicalpickles has talked about rewriting the brain, but I don't know what the direction was.

**Comment by victorhooi** [comment]
Hmm, but if you use `get`/`set`, how do you store more complex data structures?

For example, say you have an array:
```
{ 'tickets': [ { 'id': 'C-41', 'title': 'foo is broken', 'due_date': Date.now() }, { 'id': 'G-41', 'title': 'bar is working', 'due_date': Date.now() } ] }
```

How should you push/pop individual items to this, assuming it's been set in the redis brain?

Do you pull the whole thing out into a variable, edit it, then set the whole thing back? Or is there a better way, using get/set?

**Comment by michaelansel** [comment]
Given the way that persistence works, you can actually just maintain a pointer to an object in the brain, manipulate it all you want, and it will be persisted every `saveInterval`. So, in code:

```coffeescript
myList = []
robot.brain.set('my-list', myList)
myList.append(1)
# robot.brain.get('my-list') == [1]
```
