### ISSUE TITLE
Campfire adapter hanging

### ISSUE THREAD

**Issue by eliassal** [github/hubot#954]
I have created a new Campfire account for hubot, logged in with,I updated the 3 env variables (ubuntu box, no heroku no redis, I am testing)
 use the API key of that account, room id and my account sub-domain.
 Also, I changed the PORT to 9999 as I was getting the ERADDINUSE
 When I issue the following command
 bin/hubot -a campfire
 I have a blinking command line and nothing is displayed. I switch to my room in campfire I can see that hubot user has joined the room 
 Can you you please let me know what I need to do configure more in order to make it work, 2nd, is there any manual on how to interact from hubot commandline with campfire

Thanks
![hubotcampfire](https://cloud.githubusercontent.com/assets/8447864/7903010/3d134e1c-07cf-11e5-9afc-0f6634546ca1.jpg)

**Comment by bkeepers** [comment]
Hi @eliassal, does it work from the command line if you start it up without the `-a campfire` option? What other scripts or npm modules are you loading?

**Comment by eliassal** [comment]
Yes, when running this 
:~/myhubot$ bin/hubot
I get (which is the name I chose)
     salamnet> 
Some commands respond correctly others not, for example, when I run
      salamnet time
I get
      Server time is: Fri Jun 05 2015 12:58:54 GMT+0200 (CEST)
but when I run 
      salamnet convert me 56MB KB
nothing happens

**Comment by bkeepers** [comment]
@eliassal glad to hear that it works from the command line!

> is there any manual on how to interact from hubot commandline with campfire

When you start it up with the campfire adapter, it will look like it's just hanging, but hubot is expecting to interact with you in campfire. So I don't think you can use both the campfire adapter and the shell adapter at the same time.

When you start it up with `-a campfire` and it joins the campfire room, what happens if you type `salamnet time` in campfire? Does it respond?


> but when I run 
> salamnet convert me 56MB KB
> nothing happens

I'm guessing you saw the `convert me` command in docs on https://hubot.github.com/docs/? It looks like those are out of date and include plugins that are no longer bundled with hubot. I'll open an issue to get it updated.

You can see what your own hubot is capable of by running `salamnet help`:

```
hubot> hubot help
hubot adapter - Reply with the adapter
hubot animate me <query> - The same thing as `image me`, except adds a few parameters to try to return an animated GIF instead.
hubot echo <text> - Reply back with <text>
hubot help - Displays all of the help commands that hubot knows about.
hubot help <query> - Displays all help commands that match <query>.
hubot image me <query> - The Original. Queries Google Images for <query> and returns a random top result.
hubot map me <query> - Returns a map view of the area returned by `query`.
hubot mustache me <query> - Searches Google Images for the specified query and mustaches it.
hubot mustache me <url> - Adds a mustache to the specified URL.
hubot ping - Reply with pong
hubot pronounce <phrase> in <language> - Provides pronounciation of <phrase> (<language> is optional)
hubot pug bomb N - get N pugs
hubot pug me - Receive a pug
hubot the rules - Make sure hubot still knows the rules.
hubot time - Reply with current time
hubot translate me <phrase> - Searches for a translation for the <phrase> and then prints that bad boy out.
hubot translate me from <source> into <target> <phrase> - Translates <phrase> from <source> into <target>. Both <source> and <target> are optional
hubot youtube me <query> - Searches YouTube for the query and returns the video embed link.
ship it - Display a motivation squirrel
```

Here's an [updated calculator script](https://github.com/hubot-scripts/hubot-calculator) that you can install to get the `convert` command.

**Comment by eliassal** [comment]
I started with  -a campfire  , issued the following commands but nothing is returned back, I get only a blank line in campfire 
     salamnet ping
      salamnet pug me
except for salamnet time, i get some feedback, 11:10 PM.......etc

I have setup the updated calculator, running in the command line (without -a campfire)
     salamnet convert me 56MB KB
gives an error as follows
           salamnet convert me 56MB KB
but
      salamnet convert 34 L in gal
it works fine.

I really appreciate your help, but still not being able to understand the big picture behind HUBOT, is there any article I can read to understand what business function it satisfys
