### ISSUE TITLE
Documentation for proper way of initialising the Hubot brain?

### ISSUE THREAD

**Issue by victorhooi** [github/hubot#963]
Would it be possible to add documentation on the proper way to initialise new variables for the Hubot "brain"?

For example, a common pattern might be:
- Wait for the "brain" to be loaded
- Check if a key exists - if it doesn't, initialised it to some value (e.g. `{}` or `[]`)
- If it does exist, retrieve the value and set it to some local variable.

There's guides and presentations floating on the internet, that mention things like the `loaded` event etc, or you can trawl through scripts to see the myriad different ways people try to do it.

However, it'd be great if it was added to say, `scripting.md` as "this is how you should do it", even if it's just a short snippet example.

**Comment by michaelansel** [comment]
As we document, we should either fix or clearly explain the weird timing issues around brain loading: the 'loaded' event is only fired once and if your script loads after, you will never see the event. This is particularly apparent with the file brain (which loads synchronously).

**Comment by victorhooi** [comment]
At the very least, is anybody able to post a snippet showing a variable being initialised the proper way, as well as using that variable later on?

Or possible point to a Hubot script that uses the brain, and follows "good practices"?

That may be enough to at least get people started with helping out with improving the docs.

**Comment by technicalpickles** [comment]
This is the snippet I typically use:

```
module.exports = (robot) ->

  robot.brain.on 'loaded', ->
    robot.brain.data.whatever ?= {}

  robot.respond /whatever/, (res) ->
    # access robot.brain.data.whatever here
```

It doesn't try to address @michaelansel's concerns though.

**Comment by technicalpickles** [comment]
@michaelansel for some reason, I thought we had code that would make sure that your event handler was called if it was registered after the event happened initially. Might have been an unmerged PR though.

**Comment by michaelansel** [comment]
I haven't seen that PR and I'm fairly confident the code doesn't exist. I'm pretty sure I know how to fix it though (when I have time... :sweat:)

**Comment by victorhooi** [comment]
@technicalpickles Aha, thanks for the snippet - will test it out - I noticed you're directly accessing `robot.brain.data` - may I ask why one would do that, versus using the getters/setters mentioned in scripting.md?

**Comment by technicalpickles** [comment]
@victorhooi good point, you should use those instead. Those didn't always exist, so I just forgot about them.

Part of there reason for having was to theoretically have different brain implementations, rather than 'brain' scripts just taking `robot.brain.data` and periodically sending them to whatever datastore. But, that never quite happened
