### ISSUE TITLE
Document script generator

### ISSUE THREAD

**Issue by technicalpickles** [github/hubot#968]
I was about to [deprecate hubot-example](https://github.com/hubot-scripts/hubot-example/issues/9) when I realized there isn't actually any documentation on creating external scripts. Basically, use the generator-hubot package and `yo hubot:script`.

I think it'd be worth shuffling part of docs/scripting.md to a new file to talk about creating & maintaining scripts.

**Comment by geoffreyanderson** [comment]
I'm gonna take a quick whack at just adding an initial section into docs/scripting.md here. PR coming shortly!

**Comment by cycomachead** [comment]
I didn't realize this was available, but that's great, definitely having it in the main docs would be helpful!
