### ISSUE TITLE
Please add official hubot adapter for Rocket.Chat to the list of adapters in docs 

### ISSUE THREAD

**Issue by Sing-Li** [github/hubot#972]
Please add our hubot adapter for  Rocket.Chat  to the list of adapters in the docs.

Repo with quick-start guide is located at [official Rocket.Chat adapter](https://github.com/RocketChat/hubot-rocketchat).

We have created a docker image that can get devs hacking Rocket.Chat bots in minutes with minimal setup.

Thanks in advance.

**Comment by bhuga** [comment]
Hi Sing-Li,

This sounds great. Can you submit a pull request adding the adapter to `adapters.md`?

**Comment by Sing-Li** [comment]
@bhuga  Thanks.
