### ISSUE TITLE
hubot package installs with `.node-version` breaking nodenv

### ISSUE THREAD

**Issue by jasonkarns** [github/hubot#977]
The npm package is published with a `.node-version` file. I can't seem to find when, how or where this file is generated, but I humbly submit that it should not be included in the package (nor the git repo).

As has been discussed in the ruby community numerous times, the .node-version file should not be shared as it requires an overly strict version specifier.

Does anyone know where this file is coming from before I go further in advocating for its removal?

**Comment by technicalpickles** [comment]
I don't see it in git:

```
$ git rm .node-version
fatal: pathspec '.node-version' did not match any files
```

I generated a new bot and checked it's using 2.13.1. I did the release over the weekend, and I don't have that file locally, so I'm not sure where it's coming from.

Can you demonstrate how this is breaking nodenv? I use it myself, and have not seen a problem, since it'd be inside a projects's `node_modules`, not it's parent.

**Comment by jasonkarns** [comment]
I'm terribly confused where it's coming from:

```
$ npm i hubot
$ ls -al node_modules/hubot/.node-version 
-rw-r--r--  1 jasonkarns  wheel     6B Nov 21  2014 node_modules/hubot/.node-version
```

(modified time of Nov 21, 2014? weird)

I verified it's in the actual package from npm: http://registry.npmjs.org/hubot/-/hubot-2.13.1.tgz

It breaks on my nodenv because the contents of the node-version aren't a valid version name (`v0.10`). nodenv version specifiers don't have the `v` prefix, and include the full major.minor.patch version number.

```
$ bin/hubot 
/Users/jasonkarns/Projects/td/doubot/node_modules/hubot/node_modules/.bin
nodenv: version `v0.10' is not installed
```

**Comment by technicalpickles** [comment]
Did you generate a hubot with `yo hubot`? Try running `bin/hubot` from `/Users/jasonkarns/Projects/td/doubot` instead.

**Comment by technicalpickles** [comment]
Also, turns out there are multiple nodenvs: https://github.com/wfarr/nodenv

**Comment by jasonkarns** [comment]
> Try running bin/hubot from /Users/jasonkarns/Projects/td/doubot instead.

That *is* where I'm running `bin/hubot` from:

```
$ pwd
/Users/jasonkarns/Projects/td/doubot
$ bin/hubot 
/Users/jasonkarns/Projects/td/doubot/node_modules/hubot/node_modules/.bin
nodenv: version `v0.10' is not installed
```

> Also, turns out there are multiple nodenvs: https://github.com/wfarr/nodenv

Yep. I use @OiNutter's [nodenv](https://github.com/OiNutter/nodenv) which is a direct port of rbenv with virtually no modifications. (I'm one of the maintainers)

**Comment by tombell** [comment]
If you have a `.node-version` file in the directory, it will be picked up by `npm` as it uses its own `.npmignore` file, and delegates to `.gitignore` when it doesn't exist. `.node-version` isn't actually in the `.gitignore` so will be included when hubot is pushed to npmjs.org if one exists.

**Comment by jasonkarns** [comment]
So we need to add `.node-version` to the `.gitignore` and need to publish a new version to npm?

**Comment by tombell** [comment]
Yup, that would be a solution.

**Comment by michaelansel** [comment]
@jasonkarns, can you prep a PR and I'll merge and cut a release tomorrow?

**Comment by jasonkarns** [comment]
@michaelansel  #980

**Comment by technicalpickles** [comment]
We could also git ignore .node-version. Probably worth adding sanity check
to release to make sure there are random files in unchecked into git that'd
accidentally be included.

**Comment by jasonkarns** [comment]
#980 *does* add .node-version to gitignore. If we were to create an .npmignore, then npm would no longer use .gitignore, and we would have to duplicate ignore entries to both files.

**Comment by technicalpickles** [comment]
@jasonkarns missed the PR for my last comment, thanks!

**Comment by technicalpickles** [comment]
Fixed in https://github.com/github/hubot/pull/980 and the next release shouldn't have the same problem.
