### ISSUE TITLE
Trigger event via HTTP?

### ISSUE THREAD

**Issue by illusionuk** [github/hubot#987]
Hi All, 

I'm new to the hubot scene, but loving what I have running so far.

What I would like to do is trigger an existing event via HTTP.

For example: Using the https://github.com/github/hubot-scripts/blob/master/src/scripts/karma.coffee script as an example, if I wanted to check the top karma, by doing the following.

```
curl -X POST -d message="hubot karma best" http://192.168.0.36:8080/hubot/foo
```

I would then want to take the message (hubot karma best) and run that as if the user actually wrote it and return the response.

**Comment by technicalpickles** [comment]
There's an issue over at https://github.com/github/hubot/issues/925 that covers the same topic. Check that out and see if it helps!

**Comment by illusionuk** [comment]
Hi, 

Thanks for you reply.

I have been looking at the issue you post with regards to robot.emit and robot.on events.
The issue I have here is if I go down that route, that means I would have to edit existing scripts like the karma script to have robot.on event.

I am probably not explaining it well, but I would like the HTTP call to basically replicate a user input.

So if I send something like 
```
curl -X POST -d message="hubot ping" http://localhost:8080/hubot/blah
```

Hubot would return with the correct response of "Pong".
