### ISSUE TITLE
permission denied when deploying hubot on dokku

### ISSUE THREAD

**Issue by brpaz** [github/hubot#988]
Hi.
Has anyone managed to successfully deploy hubot on a [dokku](https://github.com/progrium/dokku) host?
I am getting the following error on deploy:

```
remote: App container failed to start!!
=====> ambrosio container output:
       Starting web...
       sh: 1: bin/hubot: Permission denied
       SIGINT received
       sending SIGTERM to all processes
```

**Comment by technicalpickles** [comment]
Are you able to start hubot locally with `bin/hubot`? It might be not be executable. `chmod a+x bin/hubot`, and commit that, and that might help.

There isn't any official documentation on dokku, so if you can link me any resources you are following, that will be helpful in debugging.

**Comment by brpaz** [comment]
Yes. bin/hubot worked fine locally. I was following this article (http://theflyingdeveloper.com/hubot-on-dokku/) but it didnt say much.
I kind of solved it by changing the Procfile to point directly to "node_modules/.bin/hubot" instead of using the bin/hubot executable.

Maybe dokku dont like that exec command in bin/hubot script, i dont know.

**Comment by technicalpickles** [comment]
I'm not familiar with dokku, so I don't think I can help a ton with debugging :sweat: It might be worth asking the author of that article. If anyone else can help, and maybe help get any changes (code or PR) needed into a PR, I'd be happy to review though!

**Comment by mose** [comment]
Well, seems the issue is solved. I hope that I will get time to make some dokku tests and doc soon.
