### ISSUE TITLE
Hubot irc and Problems with encoding on Heroku

### ISSUE THREAD

**Issue by Jaglag** [github/hubot#995]
Hi,
at the moment the latest Hubot-irc adapter use node irc 0.3.9,
this node need libicu to encode charsets via node-icu-charset-detector so atm hubot-irc cannot encode letters like äöüß and send  � instead of the right letter.
The only way to get that running atm is to take a different buildpack on Heroku i dont get it running but i hope someone here can create a custom buildpack for Hubot-irc and write a step by step guide for it.

Here is a guide for  charlock_holmes maybe this help a bit:

http://stackoverflow.com/questions/18926574/how-to-install-charlock-holmes-dependency-libicu-dev-on-heroku

**Comment by michaelansel** [comment]
I doubt that any of the maintainers will have the time or motivation to write this guide. You are welcome to put something together though as a PR and we can see about merging it.

**Comment by Jaglag** [comment]
The Problem is Not the Guide i can write that. For me it is to create that Custom buildpack for heroku.

**Comment by michaelansel** [comment]
I did a little reading on Heroku custom buildpacks, and it looks like that is something that is definitely out of scope for anything we are focusing on. If you or someone else would like to construct a custom buildpack, we can merge documentation changes with links to the buildpack and directions for using it. However, I don't think any of the maintainers are going to be interested in doing more than that.

**Comment by MrSaints** [comment]
I'm following this issue with @Jaglag. It doesn't seem to be a problem specific to Hubot or its adapter, Hubot IRC. If he doesn't mind, I think we can close this issue. It seems to be a script specific problem.
