### ISSUE TITLE
Why not use documentation generator ?

### ISSUE THREAD

**Issue by sdimkov** [github/hubot#997]
Currently there are doc comments on most of the classes and methods but they don't seem to follow a specific guide for any generator tool. 

Do you guys see value in using API documentation generator like [Codo](https://github.com/coffeedoc/codo) or [Docco](http://jashkenas.github.io/docco/) ?

I believe even though Hubot's codebase is rather terse it can still be very helpful for newcomers. Also if we opt for [Codo](https://github.com/coffeedoc/codo) besides generating very rich docs based on annotated source we get a common place to host it - http://coffeedoc.info/

The actual work to convert the current annotations to Codo style should be a breeze. I don't mind doing it myself when I have time. 

Any thoughts ?

**Comment by michaelansel** [comment]
Pretty documentation would be awesome! @technicalpickles do you have any thoughts on what format we should use for the docs? I assume we should use whatever is the coffeescript standard...

**Comment by sdimkov** [comment]
I tested Codo in this [repo](https://github.com/sdimkov/hubot-skype-web) and the results look very promising.

Here you can see the [docs online](https://cdn.rawgit.com/sdimkov/hubot-skype-web/v0.9.3/doc/index.html)

**Comment by MrSaints** [comment]
That does indeed look promising, and something I'd definitely consider having for all my scripts.

:+1:

**Comment by michaelansel** [comment]
Sounds reasonable to me. I'd like to get a :+1: from @technicalpickles before merging anything, but you can start on the PR if you want.

One note: if we can make the changes in pieces, that might be better for preventing merge conflicts with inflight PRs. Similar to https://github.com/github/hubot/issues/872#issuecomment-75852944

**Comment by sdimkov** [comment]
It looks even [better](https://cdn.rawgit.com/sdimkov/hubot-skype-web/877f84f67c092d55fe6a297ec28eed7c96867c22/doc/index.html) now with README and table of contents inside. Also try the fuzzy search by pressing T.

I'll wait to hear from @technicalpickles on this before working on PRs.

**Comment by tombell** [comment]
It actually uses http://tomdoc.org/

**Comment by technicalpickles** [comment]
They are formatted as [tomdoc](http://tomdoc.org/) like @tombell said. [Atom](https://atom.io/) uses the same format, and has some libraries like [atomdoc](https://github.com/atom/atomdoc). I spent some time awhile back trying to get that running, but one problem is it doesn't actually *output* anything, so that'd be soemthing we'd have to figure out ourself. cc @gjtorikian who I spoke with about back in March.

I'd be :+1: to getting switched over to codo though. It looks like it wouldn't change anything too fundamentally, since it still has markdown.

**Comment by gjtorikian** [comment]
> but one problem is it doesn't actually output anything, so that'd be soemthing we'd have to figure out ourself.

Indeed. [`grunt-atomdoc`](https://github.com/atom/grunt-atomdoc) can be used to simplify the spitting out of a giant *api.json* file. There is currently no known tool (that I know of!) that takes that JSON and creates static HTML. The Atom team takes that JSON and, via Ruby, indexes it into ElasticSearch and uses Rails to render to content.

The helpful nerd inside me would be totally down to work on an OSS solution for consuming the JSON file and generating static HTML. If that would take too long, though, certainly `codo` or something easier could be done for a first pass. The JSON file has a *ton* of incredibly helpful information, and to be honest, API docs need to level up their game beyond porting comments to HTML.

**Comment by ppKrauss** [comment]
Hello, some news here? Some documentation generator in use, now in 2016?

**Comment by technicalpickles** [comment]
Nothing new to report.
