### ISSUE TITLE
It it mandatory to make HTTP calls using the built-in HTTP client? 

### ISSUE THREAD

**Issue by Chris911** [github/hubot#998]
Reading the documentation it seems that the suggested and maybe only way to make HTTP calls using Hubot is by using the built-in HTTP mechanism on the robot. I'm currently specing a bot and I'd like to know if I'll be able to reuse libs we already use in our system that are built using `request` and already have all the logic for properly connecting to our apps. Can I just require those (async) scripts and use `res.send` with the result?

Thanks for your time and great project.

**Comment by michaelansel** [comment]
You are welcome to make outbound requests using any HTTP library you want. In fact, the docs even suggest using `request` as an alternative: https://github.com/github/hubot/blob/master/docs/scripting.md#advanced-http-and-https-settings

**Comment by Chris911** [comment]
Thanks @michaelansel.
